google/ground-android

README.md

I've added simple instructions to fork the repo, manage changes, and submit a PR.
I wonder—are these sitting in a good place in the file, or should we move them after the dev environment setup content. lmk!
Fixes #26

Add forking and PR instructions to the README.

---

.gitignore
gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java
gnd/src/main/java/com/google/android/gnd/ui/recorddetails/RecordDetailsFragment.java
gnd/src/main/java/com/google/android/gnd/ui/recorddetails/RecordDetailsViewModel.java
gnd/src/main/res/layout/record_details_frag.xml

This changes moves the progress bar visibility logic out of the RecordDetailsFragment and into its associated viewModel. See issue #9 
Since this is my first go at this, there may be some flubs. I followed the example of 8f4719ef. Please leave comments and push back as needed!

Move progress bar logic out of the RecordDetailsFragment.

---

README.md

Thankfully, we already recommend creating a new branch for each PR in step two. I've added a note warning readers about open PRs and automatic commit inclusion—hopefully this makes it clear. Presumably this is the proper place for it in the flow, as it comes in when the developer has completed a logical  group of changes. 
The note in question starts at line 95.
Fixes #42

Warn against unwitting PR commits in the README (#42)

---

gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java
gnd/src/main/java/com/google/android/gnd/rx/RxTask.java
gnd/src/main/java/com/google/android/gnd/service/RemoteDataService.java
gnd/src/main/java/com/google/android/gnd/service/firestore/FirestoreDataService.java
gnd/src/main/java/com/google/android/gnd/service/firestore/RecordDoc.java
gnd/src/main/java/com/google/android/gnd/ui/common/BindingAdapters.java
gnd/src/main/java/com/google/android/gnd/ui/editrecord/EditRecordFragment.java
gnd/src/main/java/com/google/android/gnd/ui/editrecord/EditRecordViewModel.java
gnd/src/main/java/com/google/android/gnd/ui/editrecord/MultiSelectDialogFactory.java
gnd/src/main/java/com/google/android/gnd/ui/editrecord/SingleSelectDialogFactory.java
gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/RecordListItemViewHolder.java
gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorViewModel.java
gnd/src/main/java/com/google/android/gnd/ui/recorddetails/RecordDetailsFragment.java
gnd/src/main/java/com/google/android/gnd/vo/FeatureUpdate.java
gnd/src/main/java/com/google/android/gnd/vo/Record.java
gnd/src/main/res/layout/multiple_choice_input_field.xml
gnd/src/main/res/layout/text_input_field.xml

Also, the meaning of "Value" is broad and conflicts with other symbols. This became apparent when implementing local db support because edits can refer to user responses but also changes to featute coordinates, for example.

Rename Record "Value" to "Response" for consistency

---

gnd/src/main/java/com/google/android/gnd/rx/Result.java

Blocking #24 
Wraps/unwraps values and errors in a stream to allow us to propagate error states without breaking chained streams.
Proposed usage (for `HomeScreenViewModel`):
```java
disposeOnClear(
featureClicks
.switchMapSingle(wrapErrors(dataRepository::addFeature))
.subscribe(unwrapErrors(this::showFeatureSheet, this::onAddFeatureError)));
```
Where `[un]wrapErrors` are statically imported.
Wdyt?

Add simple wrapper for streaming results

---

gnd/build.gradle
gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java

This change introduces the Result wrapper and fixes leaky subscriptions in the HomsScreenViewModel and HomeScreenFragment. 
I've opted to branch off and open separate PRs as I think it will be easier to go back and review each segment of change this way. I'm cherry-picking my existing work from the original pr-fix-leaky-subscriptions branch.
Counts toward #24

Fix Leaky Subscriptions in the Home Screen

---

gnd/src/main/java/com/google/android/gnd/rx/Result.java
gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/RecordListViewModel.java

Fixed leaky subscriptions in the record list view model. 
Note: I've cherry picked in the Result wrapper--what I should have done, was push those changes to issue-24/master separately, but I started down the wrong path by cherry-picking them into the home screen fragment/view model fixes branch, thus leaving me to pick the same cherries over and over in subsequent branches *sigh*. Oh well, lesson learned. 
Hopefully the approach to naming here is an improvement over the initial PRs!
Contributes toward #24

Plumb leaky subscriptions in the RecordListViewModel

---

gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java

Last teeny bit needed to close out issue #24!
After resolving this leaky subscription originally, I missed a leftover subscription to the mapAdapter. I've now removed it, taking care of the last #24 TODO.

Map Container: Remove extra subscription

---

gnd/src/main/java/com/google/android/gnd/model/basemap/tile/Tile.java
gnd/src/main/java/com/google/android/gnd/model/tile/Tile.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/LocalDatabase.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/TileDao.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/TileEntity.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/TileEntityState.java

In order to represent what tiles users have available for offline viewing, we'll make use of the local data store. We store tile state along with the id of the json feature the tile is associated with and the path at which the tile data is stored. This should allow us to keep track of what tiles are on the device, as well as resume failed or interrupted downloads.

Offline-Imagery: Add Tile classes to the local db.

---

gnd/src/main/java/com/google/android/gnd/MainActivityModule.java
gnd/src/main/java/com/google/android/gnd/ui/basemapselector/BasemapSelectorFragment.java
gnd/src/main/java/com/google/android/gnd/ui/basemapselector/BasemapSelectorModule.java
gnd/src/main/java/com/google/android/gnd/ui/basemapselector/BasemapSelectorViewModel.java
gnd/src/main/java/com/google/android/gnd/ui/common/Navigator.java
gnd/src/main/java/com/google/android/gnd/ui/common/ViewModelModule.java
gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java
gnd/src/main/res/layout/basemap_selector_frag.xml
gnd/src/main/res/menu/nav_drawer_menu.xml
gnd/src/main/res/navigation/nav_graph.xml
gnd/src/main/res/values/strings.xml

This change adds a fragment, view model, layout, and other components
to support a distinct UI for selecting offline imagery. Keeping this UI
separate ensures we can manage the feature independently, as well as
gives users a better experience (the basemap selection map doesn't
render markers, as these are noisy in the context).
This particular commit doesn't implement any interesting functionality.
It is effectively just a shell for the basemap selection UI. As a
minimal first step, we do render the map in this commit.
This UI is in the nav graph, so users can utilize the android navigation
back arrow to return to the main home screen.

Offline Imagery: Add basemap selector UI

---

gnd/src/main/java/com/google/android/gnd/persistence/local/LocalDataStore.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/TileDao.java

This change adds methods for accessing all tiles from the local data store.
Additionally, I've updated the tile DAO so that we can fetch all tiles
from the DB.

Offline Imagery: Add tile streams to data store

---

gnd/src/main/java/com/google/android/gnd/ui/basemapselector/BasemapSelectorFragment.java
gnd/src/main/java/com/google/android/gnd/ui/map/Extent.java
gnd/src/main/java/com/google/android/gnd/ui/map/ExtentSelector.java
gnd/src/main/java/com/google/android/gnd/ui/map/MapProvider.java
gnd/src/main/java/com/google/android/gnd/ui/map/gms/BasemapSelectorMapAdapter.java
gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapProvider.java

I've added an extent map adapter to differentiate between maps that support extent selections and those that don't. It implements (more or less) all the methods we'll need to handle extent selections for the offline imagery functionality. 
Additionally, I've added an Extent value class that should keep our implementation flexible, (for instance, we can easily augment the class with tile styling information to be applied on extent selection).
More PRS coming your way soon ;)

Offline Imagery: Extent map adapter

---

gnd/src/main/java/com/google/android/gnd/inject/GndWorkerFactory.java
gnd/src/main/java/com/google/android/gnd/model/basemap/tile/Tile.java
gnd/src/main/java/com/google/android/gnd/persistence/local/LocalDataStore.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java
gnd/src/main/java/com/google/android/gnd/workers/FileDownloadWorkManager.java
gnd/src/main/java/com/google/android/gnd/workers/FileDownloadWorker.java

I've made necessary updates to ensure the file download worker can manage the entirety of the tile downloading and db writing/mgmt flow. 
After this change is in, we only need to pass tile IDs to the worker from the view model, rather than have to worry about managing tiles.

Offline Imagery: Update File Download Worker

---

gnd/src/main/res/values/strings.xml

This change renames UI instances of the string record to observation, in
keeping with our adopted terminology.
Closes #121

UI: Rename "record" to "observation"

---

gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
gnd/src/main/res/menu/nav_drawer_menu.xml

Temporarily removing offline maps from the nav menu, since the
functionality is disabled.
Not sure what your plans are for this, but in case you just want to completely nix the functionality from this build, this PR temporarily removes the offline maps menu option!

Offline Imagery: Remove offline maps from menu

---

config/lint/lint.xml
gnd/src/main/java/com/google/android/gnd/persistence/local/LocalValueStore.java
gnd/src/main/res/layout/record_list_frag.xml

Related to #217 
Changing the severity to error forces the cloud build to fail. Warnings don't cause failure but do get reported in the html.

Fix minor lint warnings

---

README.md
build.gradle
cloudbuild.yaml
config/spotbugs/spotbugs-filter.xml
config/spotbugs/spotbugs.gradle
gnd/build.gradle

Add [spotbugs](https://github.com/spotbugs/spotbugs) plugin for finding common bugs in Java classes. This can also be run manually like other plugins in the IDE or command-line.

[Code health] Spotbugs plugin

---

README.md
build.gradle
cloudbuild.yaml

Running `checkCode` executes all 4 plugins (lint, pmd, checkstyle, spotbugs)
To be merged after #226

[Code health] Add gradle task checkCode  

---

config/spotbugs/spotbugs-filter.xml

Most of the issues detected by spotbugs were in the auto-generated classes. 
Filtering them out allows us to enable those checks for our source code.

[Code health] Enable excluded checks for spotbugs

---

cloudbuild.yaml

Do not kill the build if reports were not generated for any reason. (`assembleDebug` might fail).

[CI] Suppress failure if reports were not generated

---

gnd/build.gradle
gnd/src/main/java/com/google/android/gnd/GndApplication.java
gnd/src/main/java/com/google/android/gnd/GndApplicationComponent.java
gnd/src/main/java/com/google/android/gnd/MainActivity.java
gnd/src/main/java/com/google/android/gnd/ui/common/AbstractDialogFragment.java
gnd/src/main/java/com/google/android/gnd/ui/common/AbstractFragment.java

Things done:
- Replaces deprecated `Builder` with `Factory` in `GndApplicationComponent`
- Extends with `DaggerApplication`, `DaggerAppCompatActivity` and `DaggerFragment` to reduce boilerplate code
- No more `Inject` calls!

[Code Health] Update dagger + Code Cleanup

---

gnd/src/main/java/com/google/android/gnd/persistence/local/room/BaseDao.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/FeatureMutationDao.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/FieldDao.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/ProjectDao.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/RecordMutationDao.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java

Moves commonly used update and delete methods to BaseDao. Also, all DAOs now extend BaseDao

[Refactor] Move common methods to BaseDao and refactor DAOs

---

gnd/src/main/java/com/google/android/gnd/Config.java
gnd/src/main/java/com/google/android/gnd/GndApplicationModule.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/LocalDatabase.java
gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FirestoreDataStore.java
gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/GndFirestore.java

Things done:
- Add binding for Firestore instance in module.
- Move settings to `Config`
- Inject `GndFirestore` into `FirestoreDataStore`
Testing: 
- Manually verified the changes by running on emulator.
Advantages:
- Moving `FirebaseFirestore` instance call to a module would allow us to use mocks in tests.
- Code cleanup

[Refactor] Bind Firestore instance in module and inject using Dagger

---

gnd/src/main/java/com/google/android/gnd/ui/basemapselector/BasemapSelectorFragment.java
gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java
gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/FeatureSheetFragment.java
gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/ObservationListAdapter.java
gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java
gnd/src/main/java/com/google/android/gnd/ui/signin/SignInFragment.java

Clicking "add feature" sometimes crashed the app because the "add record" was present on the screen but invisible even when the sheet was closed. So when clicking near the "add feature" button, we were actually clicking "add record". This was due to data binding not working since the lifecycle owner was never set. Fixed this for this use case and other binding instances.

[Add feature] Fix force quit on "Add feature"

---

gnd/build.gradle
gnd/src/main/java/com/google/android/gnd/GndApplication.java
gnd/src/main/java/com/google/android/gnd/system/LocationManager.java

Reducing location lock priority to conserve battery. The user can always increase priority through settings. Discovering while debugging #307.

Location lock priority and related tweaks

---

gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorDialogFragment.java

[Project selector] Fix reappearing frozen project selector

---

gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorDialogFragment.java

This PR reapplies changes from PR #316, which was reverted because it caused the app to crash. 
I've fixed the issue--we were attempting to dismiss the project selector regardless of whether or not it was actually shown, causing it to have a null fragmentManager in some scenarios, which makes the app crash on a call to dismiss. 
We now make sure the selector is actually visible (and thus managed) before we attempt to dismiss it.

Dismiss project selector

---

config/lint/lint.xml
gnd/src/main/res/layout/observation_list_item.xml
gnd/src/main/res/layout/sign_in_frag.xml
gnd/src/main/res/values/strings-untranslated.xml
gnd/src/main/res/values/strings.xml

Enable lint check to detect hardcoded texts in xml layouts.
This should help us in future localization tasks.
@gino-m @scolsen I also noticed that some of strings are duplicate (like `add_feature_cancel` and `discard_multiple_choice_changes`). Any particular reason for that? Also, would it be fine to use android's resource for common strings (android.R.string.cancel) ?

[Code health] Enforce check to detect hard-coded strings in layouts

---

config/pmd/pmd-ruleset.xml

We sometimes want to move converters outside of data classes themselves to allow injection, finer separation of concerns, and easier testing, so suggesting to disable this rule. Wdyt?

Disable DataClass PMD rule

---

gnd/build.gradle
gnd/src/main/java/com/google/android/gnd/Config.java
gnd/src/main/java/com/google/android/gnd/GndApplicationModule.java
gnd/src/main/java/com/google/android/gnd/persistence/remote/FirestoreStorageManager.java
gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java
gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java
gnd/src/main/java/com/google/android/gnd/ui/util/FileUtil.java

Towards #310 
- Uploads selected photo to firestore storage 
- If offline, the sdk handles the re-uploading when the network is available
- files are uploaded using the UUID. So, they can be stored in the db without actually having to upload the photo first
- Adds picasso to load the uploaded photo using Uri (Bug: The bitmap isn't getting loaded into the ImageView, added a TODO for that)

[Photos Support] Upload photos to firebase storage

---

gnd/build.gradle
gnd/src/main/java/com/google/android/gnd/GndApplication.java
gradle.properties

- Adds timber logging library (https://github.com/JakeWharton/timber)
- Upload warning/error logs to crashlytics for non-debug builds
Next steps:
- Replace Log.* calls with Timber.*
- Enable link check to prevent usages of Log.*

Configure Timber logging

---

gnd/build.gradle

Auto running locally has been causing several issues so disabling for now. @shobhitagarwal1612 FYI. See also conversation on #342 and in https://gitter.im/ground-platform/ground-contributors.

Stop running checkCode on install

---

gnd/build.gradle
gnd/src/main/java/com/google/android/gnd/persistence/geojson/GeoJsonExtent.java
gnd/src/main/java/com/google/android/gnd/persistence/geojson/GeoJsonParser.java

**N.B.**: Includes changes from pr #390 (wait until that's submitted)
- Fix an error in handling of coordinate values in GeoJsonExtent (coordinates were nested more deeply in an array in the source than I anticipated)
- Use Apache Commons to read in Json data.﻿

Use Apache Commons in GeoJsonParser; Fix GeoJsonExtent

---

build.gradle
gnd/build.gradle

- Config task updateDependency
- Set output dir to /gnd/build/reports/ so that the reports are uploaded to GCS
- Add TODO for future task

[Code-health] Add task for dependency check to Cloud Build

---

gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapAdapter.java

This PR contains two minor clean up changes to the MapAdapter:
- Use timber for logging
- Remove the renderJsonLayer -- we don't need it anymore since we now take a viewport based approach to offline area selection﻿

Clean up MapAdapter

---

cloudbuild.yaml

Things done:
- remove unused flag
- maintain styling consistency
- Update ACLs only if dependency status is updated
- print STDOUT to console and only save STDERR to `*.txt`. This would be useful when trying to search for an error directly from the console output.
- add file exists check before attempting to read it

[Cleanup] Fix cloudbuild config

---

gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
gnd/src/main/res/layout/feature_sheet_chrome.xml
gnd/src/main/res/layout/home_screen_frag.xml
gnd/src/main/res/layout/observation_list_frag.xml

Screenshot of fixed layout: 
Change includes: 
- Fix to height of bottom sheet scroll view so that it perfectly fills the screen when expanded
- Fixed a related bug where the `RecyclerView` didn't fill the entire container (it was being clipped to its padding), see screenshot showing issue below. 
- Change navigation bar to a light grey to make the buttons easier to see (previously it was white)
- Added a few comments

Fix the height of the bottom sheet scroll view

---

gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java
gnd/src/main/res/layout/map_container_frag.xml
gnd/src/main/res/values/dimens.xml

Closes #422, Closes #426
- Instead of moving the button layout in y-direction, we are now setting the top/bottom padding equal to the inset size for accurate positioning
- removed extra left / right margin (2nd screenshot, comparing with google maps)

[Home screen] Fix map type button margin

---

.github/pull_request_template.md

The PR editor opens in  "Write" mode, so developers don't see the text as Markdown formatted when writing the PR desc. Reformatted to reflect this.

Reformat PR template for reading as unformatted markdown

---

gnd/src/main/java/com/google/android/gnd/rx/RxDebug.java

Useful when debugging Single streams. These helpers are not actually used in code production code, only during development.

Add helper for debugging Single events

---

gnd/src/main/java/com/google/android/gnd/Config.java
gnd/src/main/java/com/google/android/gnd/model/layer/Layer.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/LayerEntity.java
gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/LayerConverter.java
gnd/src/test/java/com/google/android/gnd/repository/InMemoryCacheTest.java

Fixes #443. Older projects didn't have defaultStyle set for all layers, causing the app to crash.

Fix app crashes on missing default layer style

---

gnd/build.gradle
gnd/src/main/java/com/google/android/gnd/persistence/local/LocalDataStore.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/dao/OfflineAreaDao.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/OfflineAreaEntity.java
gnd/src/main/java/com/google/android/gnd/repository/OfflineAreaRepository.java
gnd/src/main/java/com/google/android/gnd/ui/offlinearea/OfflineAreaListAdapter.java
gnd/src/main/java/com/google/android/gnd/ui/offlinearea/OfflineAreasFragment.java
gnd/src/main/java/com/google/android/gnd/ui/offlinearea/OfflineAreasViewModel.java
gnd/src/main/res/layout/offline_areas_list_item.xml

Currently we just list the ID of each area. Eventually, we'll give users controls to delete and manage areas from this UI.
towards #308
@gino-m @shobhitagarwal1612 
Almost done -- just did a quick check and have to ensure the last item on the list is working.

Added Support for Listing Downloaded Offline Areas

---

gnd/src/main/java/com/google/android/gnd/ui/home/BottomSheetChromeBehavior.java
gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
gnd/src/main/res/layout/feature_sheet_chrome.xml
gnd/src/main/res/layout/feature_sheet_frag.xml
gnd/src/main/res/layout/observation_list_frag.xml

Move header into bottom sheet and stop requiring negative expanded offset. This unblocks upgrading to latest Material components and upcoming simplifications and cleanup. See commit history for details.

[Feature sheet] Simplify bottom sheet header design

---

cloudbuild.yaml

A dummy `google-services.json` is used for building apks on GCB. This is fine for unit tests as we don't install the apk. But it can't be used on a real device.
So, let's disable this until the issue is resolved

Disable saving artifacts to cloud storage

---

gnd/src/main/java/com/google/android/gnd/Config.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/MultipleChoiceEntity.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/OptionEntity.java

Fixes #491.
Update primary keys for OptionEntity and MultipleChoiceEntity.
Verified by following the steps in issue and confirmed that duplicate entries were not saved.
@gino-m  PTAL?

[Bug] Prevent duplicate entries of multiple choice fields

---

gnd/src/main/java/com/google/android/gnd/persistence/geojson/GeoJsonExtent.java

The GeoJson spec states that positions must be described by a longitude followed by a latitude; we previously assumed the reverse order, leading to errors.

Fix GeoJson coordinate parsing

---

gnd/src/main/java/com/google/android/gnd/MainActivityModule.java
gnd/src/main/java/com/google/android/gnd/persistence/local/LocalDataStore.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java
gnd/src/main/java/com/google/android/gnd/repository/OfflineAreaRepository.java
gnd/src/main/java/com/google/android/gnd/ui/common/Navigator.java
gnd/src/main/java/com/google/android/gnd/ui/common/ViewModelModule.java
gnd/src/main/java/com/google/android/gnd/ui/offlinearea/OfflineAreaListAdapter.java
gnd/src/main/java/com/google/android/gnd/ui/offlinearea/OfflineAreasFragment.java
gnd/src/main/java/com/google/android/gnd/ui/offlinearea/OfflineAreasViewModel.java
gnd/src/main/java/com/google/android/gnd/ui/offlinearea/viewer/OfflineAreaViewerFragment.java
gnd/src/main/java/com/google/android/gnd/ui/offlinearea/viewer/OfflineAreaViewerModule.java
gnd/src/main/java/com/google/android/gnd/ui/offlinearea/viewer/OfflineAreaViewerViewModel.java
gnd/src/main/res/layout/offline_area_viewer_frag.xml
gnd/src/main/res/navigation/nav_graph.xml
gnd/src/main/res/values/dimens.xml
gnd/src/main/res/values/strings.xml

This PR adds a UI for viewing downloaded offline areas. When a user selects an area from the list of downloaded offline areas, they're presented with a viewer that:
The removal functionality isn't implemented yet--this PR just introduces the new UI and hooks it up to the Areas list.

Add Offline Area Viewer UI

---

build.gradle
config/spotbugs/spotbugs.gradle
gnd/build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
third_party/android-gmaps-addons/build.gradle

Upgrade to gradle plugin to 4.0.0 and some other version bumps, notably:
- Remove `android.enableUnitTestBinaryResources=true`. [No longer needed since Android 3.3](http://robolectric.org/blog/2018/10/25/robolectric-4-0/).
- Remove `android.enableSeparateAnnotationProcessing=true`. [No longer supported in Gradle Plugin 4.0.0](https://developer.android.com/studio/releases/gradle-plugin) (see section titled "Separate annotation processing feature removed")
- Update com.google.android.gms:play-services-base:17.2.1 to 17.3.0
- Update gradle version to 6.5
Problem:
Spotbugs gives an error so is currently commented out. Need expert help from @gino-m :)

[Code health] Update to gradle plugin version 4.0

---

gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FirestoreDataStore.java
gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FirestoreStorageManager.java
gnd/src/main/java/com/google/android/gnd/persistence/sync/PhotoSyncWorkManager.java
gnd/src/main/java/com/google/android/gnd/system/StorageManager.java
gnd/src/main/java/com/google/android/gnd/ui/editobservation/AddPhotoDialogAdapter.java
gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java
gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java
gnd/src/main/java/com/google/android/gnd/ui/util/FileUtil.java
gnd/src/main/res/layout/add_photo_list_item.xml
gnd/src/main/res/values/dimens.xml
gnd/src/main/res/values/styles.xml

Towards #310, #487 
- Fix regression: photo doesn't load
- Fix bug: remote path contained "N/A" instead of `formId` when creating a new observation instead of editing old one
- Fix bug: bottom sheet dialog not dismissing after making a selection
- Use `UUID` as filename in order to support multiple photos (in upcoming PRs)
- Enqueue photos for upload when synchronizing response deltas
- Remove local file after uploading to remote storage successfully

[Bugs] Improve photos support

---

build.gradle
gnd/build.gradle
gradle/wrapper/gradle-wrapper.properties

* Add a filter to `dependencyUpdates` plugin to prevent notifying update from stable to unstable version. (We hardly ever do that. Except for when testing latest libraries e.g. `hilt`). This shows the code health more accurately in the Github badge
* Bump gradle and several other dependencies
@gino-m PTAL.

[Code health] Tweak plugin and update gradle dependencies

---

gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java
gnd/src/main/java/com/google/android/gnd/ui/editobservation/PhotoFieldViewModel.java
gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java
gnd/src/main/java/com/google/android/gnd/ui/home/featuredetails/FeatureDetailsViewModel.java
gnd/src/main/java/com/google/android/gnd/ui/home/featuredetails/ObservationListViewModel.java
gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsViewModel.java
gnd/src/main/res/layout/edit_observation_frag.xml
gnd/src/main/res/layout/feature_details_chrome.xml
gnd/src/main/res/layout/feature_details_header.xml
gnd/src/main/res/layout/observation_details_frag.xml
gnd/src/main/res/layout/observation_list_frag.xml
gnd/src/main/res/layout/photo_field.xml

Slightly simplifies the view models by refactoring the "visibility" variables from ints which hold the visibility to booleans which hold the underlying state e.g. `isLoading` `isSaving` and can then be used in the layouts.

[Code Health] Move visibility logic from ViewModels to layouts

---

gnd/src/main/java/com/google/android/gnd/Config.java
gnd/src/main/java/com/google/android/gnd/model/basemap/OfflineArea.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/OfflineAreaEntity.java
gnd/src/main/java/com/google/android/gnd/repository/OfflineAreaRepository.java
gnd/src/main/java/com/google/android/gnd/system/GeocodingManager.java
gnd/src/main/java/com/google/android/gnd/ui/offlinearea/OfflineAreaListAdapter.java
gnd/src/main/java/com/google/android/gnd/ui/offlinearea/OfflineAreasViewModel.java
gnd/src/test/java/com/google/android/gnd/persistence/local/LocalDataStoreTest.java

The main motivation for this PR is to make our offline areas functionality truly offline, by persisting area names offline--before, we had run the geocoder (which requires a connection) on rendering area details. Instead, we now run it before storing an area, so that the name is saved.
I've also refactored the code accordingly, eliminating a duplicate map key bug in the areas list.

Geocoding Fixes

---

gnd/src/main/java/com/google/android/gnd/Config.java
gnd/src/main/java/com/google/android/gnd/model/basemap/tile/TileSource.java
gnd/src/main/java/com/google/android/gnd/persistence/geojson/GeoJsonParser.java
gnd/src/main/java/com/google/android/gnd/persistence/local/LocalDataStore.java
gnd/src/main/java/com/google/android/gnd/persistence/local/LocalDataStoreModule.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/LocalDatabase.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/dao/TileSourceDao.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/TileSourceEntity.java
gnd/src/main/java/com/google/android/gnd/persistence/sync/TileSourceDownloadWorkManager.java
gnd/src/main/java/com/google/android/gnd/persistence/sync/TileSourceDownloadWorker.java
gnd/src/main/java/com/google/android/gnd/repository/OfflineAreaRepository.java
gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerViewModel.java
gnd/src/main/java/com/google/android/gnd/ui/offlinearea/viewer/OfflineAreaViewerViewModel.java
gnd/src/main/res/values/strings.xml
gnd/src/test/java/com/google/android/gnd/persistence/local/LocalDataStoreTest.java

TileSource better captures what this object represents--some URL and eventually file path that points to a file that contains tileset data that we can render on the map as an overlay. The old name, Tile, suggests that the object represents a single tile, at a single zoom level, while the tileset files we use actually are pyramidal and contain tiles at multiple zoom levels.
@gino-m @shobhitagarwal1612 
Fixes #400.

Rename Tile -> TileSource

---

cloudbuild.yaml

Reverts google/ground-android#589
For some reason, sometimes `.git` is initialized by GCB and sometimes not. 
So, to be on safer side. This PR removes the existing dir (if any) and then attempts to mv safely.

Revert "Fix build"

---

gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapAdapter.java

Fixes #603 
The reason it didn't get caught by the instrumentation tests is because this error only happens once a GeoJSON layer is added to the map. Our test data doesn't contain any GeoJSON in the feature
Verified by clicking on any pin in "example" project
@gino-m  PTAL?

[Points] Use marker manager for handling click events

---

gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/FeatureConverter.java
gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/FieldConverter.java
gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/FormConverter.java
gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/FormNestedObject.java
gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/LayerConverter.java
gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/ObservationConverter.java
gnd/src/main/java/com/google/android/gnd/ui/home/AddFeatureDialogFragment.java

This is preferred since it doesn't unnecessarily create an extra Optional, and doesn't introduce another concept (Optionals) in code where they aren't used. Split off of #639.
@dturner @scolsen FYI.

[Code health] Use Objects instead of Optional to resolve null values to defaults

---

gnd/src/main/java/com/google/android/gnd/ui/common/Navigator.java

This fixes an issue where the home screen view model would end up holding a reference to a dead navigator after a screen rotation.
fixes #642

Make Navigator a singleton

---

gnd/src/main/java/com/google/android/gnd/GndApplication.java

Timber currently doesn't work before the end of `onCreate` where it's initialized. This PR initializes it in the application constructor so it can be used throughout the whole app lifecycle.

[Logging] Enable logging earlier in app lifecycle

---

gnd/src/main/java/com/google/android/gnd/model/TestModelBuilders.java
gnd/src/main/java/com/google/android/gnd/model/feature/Feature.java
gnd/src/main/java/com/google/android/gnd/model/form/Field.java
gnd/src/main/java/com/google/android/gnd/model/observation/ResponseMap.java
gnd/src/main/java/com/google/android/gnd/persistence/remote/DataStoreException.java
gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/ObservationConverter.java
gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/UserConverter.java
gnd/src/test/java/com/google/android/gnd/persistence/remote/firestore/schema/ObservationConverterTest.java

Contributes to #754. This will be used to allow date, time, and other Ground form field types to use the same remote and local representation as other field types.
@atalekar @HemanParbhakar PTAL?

[Code health] Use form definition when deserializing observations from remote db

---

gnd/src/main/java/com/google/android/gnd/persistence/local/room/LocalDatabase.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/converter/ResponseDeltasConverter.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/converter/ResponseMapConverter.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/ObservationEntity.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/ObservationMutationEntity.java

Contributes to  #754. . This change is required to allow us to pass in form metadata in a subsequent PR.
Depends on #760. Please review that PR first.

[Local persistence] Call observation response converters directly rather than via Room type converters

---

gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java
gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java
gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerViewModel.java
gnd/src/main/java/com/google/android/gnd/ui/map/MapAdapter.java
gnd/src/main/java/com/google/android/gnd/ui/map/MapGeoJson.java
gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapAdapter.java
gnd/src/main/res/values/dimens.xml

Builds on #782. 
Next steps in fast-follow PR(s):
* Parse GeoJSON at load time rather than rendering time.
* Use on shared GeoJSONLayer rather than one for each feature. Set parsed geometries on that layer.
* Let view model provide GeoJSON styles rather than setting them in MapAdapter.
* View  model updates GeoJSON styles to reflect whether feature is selected.
@scolsen This PR includes your commits as well. PTAL?

[Map] Allow GeoJSON to be tappable

---

gnd/src/main/java/com/google/android/gnd/model/observation/NumberResponse.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/converter/ResponseJsonConverter.java
gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/ObservationConverter.java
gnd/src/main/java/com/google/android/gnd/ui/editobservation/NumberFieldViewModel.java
gnd/src/main/res/layout/number_input_field.xml

This commit fixes an issue whereby number fields would sporadically move
the cursor while adjusting values.
We move numeric conversions further down the stack and treat field
values as strings, additionally specifying the correct field type for
numeric field (numberDecimal)
@gino-m 
fixes #787

fix: stop unintended cursor movement on number fields

---

gnd/src/main/java/com/google/android/gnd/ui/home/BottomSheetMetrics.java

Workaround for #828. Logs message when the crash would occur and falls back to default value. @scolsen @HemanParbhakar Could you please keep an eye out for the error message and see if you can understand when it's happening? It's seems to be hard to repro.
@HemanParbhakar Could you PTAL?

Work around negative expanded offset bug

---

gnd/src/main/java/com/google/android/gnd/repository/ProjectRepository.java
gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorViewModel.java

Couldn't repro in the emulator or physical device. This should prevent the app from crashing if this reoccurs, but we should keep an eye out for the logged errors in order to track down the root cause.
Closes #833.
@shobhitagarwal1612 PTAqL?

[Project list] Defensively check project list load state before activating

---

gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FirestoreStorageManager.java
gnd/src/main/java/com/google/android/gnd/persistence/sync/PhotoSyncWorker.java
gnd/src/main/java/com/google/android/gnd/repository/UserMediaRepository.java

Fixes #881
Default timeout for the remote fetch was very large. Which is why the local image wasn't being loaded instantly. Also, we were removing the local copy once the photo was uploaded successfully.
To solve that:
* Stop removing the local copy
* Attempt to load from local cache first for better UX
1. Enable airplane mode
2. Open app and create a new observation
3. Click a new photo and save it.
4. The image should be visible under view observation
5. Then disable the airplane mode and let the photo upload.
6. Kill the app and enable airplane mode again.
7. Open the app and load the same observation.
8. Image should still be visible
@gino-m  PTAL?

[Photos] Load image from local cache if available

---

gnd/src/main/java/com/google/android/gnd/system/CameraManager.java
gnd/src/main/java/com/google/android/gnd/system/StorageManager.java
gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java
gnd/src/main/res/layout/photo_field.xml
gnd/src/test/java/com/google/android/gnd/system/CameraManagerTest.java
gnd/src/test/java/com/google/android/gnd/system/StorageManagerTest.java

Fixes image path being sent for adding images.
As of API level 29, ACTION_MEDIA_SCANNER_SCAN_FILE is deprecated
https://developer.android.com/reference/android/content/Intent#ACTION_MEDIA_SCANNER_SCAN_FILE
Fixes #891 
Tested manually on physical device
@gino-m  PTAL?

[Photo] Fix "save to gallery"

---

cloud-builder/cloudbuild.yaml
cloudbuild.yaml
gnd/build.gradle

Things done:
- Use machine with multiple CPUs and high memory
- Remove `copying .git` step as the bug is now fixed
- Improve ids
- Disable crashlytics plugin for non-release builds
- Update `save cache` step to only cache relevant files
This also introduced < 1 min queue time as now the build depends on availability of high configuration machines.
But this gap is more than compensated by the fact that each gradle step is now 8 times faster.
@gino-m PTAL?

[GCB] Improvements to remote build

---

cloudbuild.yaml

Prevents failing of remote build because of concurrent modification error.
`tar: .gradle/caches/build-cache-1: file changed as we read it`
@gino-m  PTAL?
Contributes to #922.

[GCB] Revert cache save step

---

.idea/codeStyles/Project.xml
gnd/src/main/java/com/google/android/gnd/model/observation/MultipleChoiceResponse.java
gnd/src/main/java/com/google/android/gnd/model/observation/NumberResponse.java
gnd/src/main/java/com/google/android/gnd/model/observation/Response.java
gnd/src/main/java/com/google/android/gnd/model/observation/TextResponse.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/converter/ResponseJsonConverter.java
gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/ObservationConverter.java
gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/ObservationMutationConverter.java
gnd/src/main/java/com/google/android/gnd/ui/editobservation/AbstractFieldViewModel.java
gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java
gnd/src/main/java/com/google/android/gnd/ui/editobservation/MultiSelectDialogFactory.java
gnd/src/main/java/com/google/android/gnd/ui/editobservation/MultipleChoiceFieldViewModel.java
gnd/src/main/java/com/google/android/gnd/ui/editobservation/PhotoFieldViewModel.java
gnd/src/main/java/com/google/android/gnd/ui/editobservation/SelectDialogFactory.java
gnd/src/main/java/com/google/android/gnd/ui/editobservation/SingleSelectDialogFactory.java
gnd/src/main/java/com/google/android/gnd/ui/home/featuredetails/ObservationListItemViewHolder.java
gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsFragment.java
gnd/src/test/java/com/google/android/gnd/persistence/remote/firestore/schema/ObservationConverterTest.java

Things done: 
* Remove `field` from methods in `Response`
* Add `mutipleChoice` parameter to `MultipleChoiceResponse`
* Remove unused `field` from `Response` and its implementations
* Cleanup `PhotoFieldViewModel`
* Reuse `responseSubject` instead of creating a new flowable.
* Minor naming improvements
* Convert `debug` to `error` logging
Affected components:
* All types of responses
* Select fields
* Photo fields
Changes verified by testing all affected components manually.
@gino-m  PTAL?

[Cleanup] Refactor Photo & MultipleChoice VMs

---

build.gradle
cloudbuild.yaml

The generated reports are only used when the build is running against `master`.
So, run this task only when necessary.
@gino-m  PTAL?

[GCB] Run task "dependencyUpdates" only when running on master

---

gnd/src/main/java/com/google/android/gnd/MainViewModel.java
gnd/src/main/java/com/google/android/gnd/system/auth/SignInState.java
gnd/src/sharedTest/java/com/google/android/gnd/FakeData.java
gnd/src/test/java/com/google/android/gnd/MainViewModelTest.java
gnd/src/test/java/com/google/android/gnd/ui/MainViewModelTest.java
gnd/src/test/java/com/google/android/gnd/ui/home/featuredetails/BaseFeatureDetailsViewModelTest.java
gnd/src/test/java/com/google/android/gnd/ui/home/featuredetails/DeleteMenuVisibilityTest.java
gnd/src/test/java/com/google/android/gnd/ui/home/featuredetails/MoveMenuVisibilityTest.java
gnd/src/test/java/com/google/android/gnd/ui/tos/TermsOfServiceViewModelTest.java

Fixes #971
Things done: 
* Remove unused code
* Cleanup TermsOfServiceViewModelTest
* Cleanup MainViewModel
* Remove inconsistent tests in MainViewModelTest and replace with exhaustive unit tests for user signin flow.
* Fixes a bug in which the offline user is unable to use the app even if they are signed in and terms of service is accepted
Changes verified by running the app manually and performing sign-in / sign-out operations.
@gino-m  PTAL?

[Unit tests] Cleanup tests and improve coverage for sign-in flow

---

build.gradle

The strict mode doesn't seem to work well when there are many GeoJsonLayer on the map that results in a lot of setting listener calls to Maps SDK.

Downgrade compile and target SDK version to avoid ANR problem in Dev build

---

gnd/src/main/java/com/google/android/gnd/model/basemap/OfflineArea.java
gnd/src/main/java/com/google/android/gnd/persistence/local/LocalDataStore.java
gnd/src/main/java/com/google/android/gnd/persistence/local/LocalDataStoreModule.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/LocalDatabase.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/dao/OfflineAreaDao.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/OfflineAreaEntity.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/models/OfflineAreaEntityState.java
gnd/src/main/java/com/google/android/gnd/repository/OfflineAreaRepository.java
gnd/src/main/java/com/google/android/gnd/ui/common/ViewModelModule.java
gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerViewModel.java
gnd/src/main/java/com/google/android/gnd/ui/offlinebasemap/OfflineAreaListAdapter.java
gnd/src/main/java/com/google/android/gnd/ui/offlinebasemap/OfflineAreasFragment.java
gnd/src/main/java/com/google/android/gnd/ui/offlinebasemap/OfflineAreasViewModel.java
gnd/src/main/java/com/google/android/gnd/ui/offlinebasemap/selector/OfflineAreaSelectorFragment.java
gnd/src/main/java/com/google/android/gnd/ui/offlinebasemap/selector/OfflineAreaSelectorViewModel.java
gnd/src/main/java/com/google/android/gnd/ui/offlinebasemap/viewer/OfflineAreaViewerFragment.java
gnd/src/main/java/com/google/android/gnd/ui/offlinebasemap/viewer/OfflineAreaViewerViewModel.java
gnd/src/main/java/com/google/android/gnd/ui/syncstatus/SyncStatusViewModel.java
gnd/src/main/res/layout/offline_base_map_selector_frag.xml
gnd/src/main/res/layout/offline_base_map_viewer_frag.xml
gnd/src/main/res/layout/offline_base_maps_frag.xml
gnd/src/main/res/navigation/nav_graph.xml
gnd/src/test/java/com/google/android/gnd/persistence/local/LocalDataStoreTest.java

Rename `OfflineBaseMap` to `OfflineArea`.
This is the first in a few class renames we'll perform in relation to offline base maps functionality in order to make the code clearer.

refactor: rename OfflineBasemap -> OfflineArea

---

gnd/src/main/java/com/google/android/gnd/model/Project.java
gnd/src/main/java/com/google/android/gnd/model/basemap/BaseMap.java
gnd/src/main/java/com/google/android/gnd/persistence/local/LocalDataStoreModule.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/LocalDatabase.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/dao/BaseMapDao.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/BaseMapEntity.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/ProjectEntity.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/relations/ProjectEntityAndRelations.java
gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/BaseMapNestedObject.java
gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/ProjectConverter.java
gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/ProjectDocument.java
gnd/src/main/java/com/google/android/gnd/repository/OfflineAreaRepository.java

Renames `OfflineBaseMapSource` to `BaseMap`
This part of a few class renames we'll perform in relation to offline base maps functionality in order to make the code clearer.

refactor: rename OfflineBaseMapSource -> BaseMap

---

gnd/src/main/java/com/google/android/gnd/MainViewModel.java
gnd/src/sharedTest/java/com/google/android/gnd/FakeData.java
gnd/src/sharedTest/java/com/google/android/gnd/persistence/remote/FakeRemoteDataStore.java
gnd/src/test/java/com/google/android/gnd/MainViewModelTest.java
gnd/src/test/java/com/google/android/gnd/repository/TermsOfServiceRepositoryTest.java

Fixes #1032 
Skips the terms of service fragment if the document under "/config/tos" is missing in firestore.
Verified by removing the document from firebase and running the app locally.
@gino-m  PTAL?

Skip to home screen if terms of service is missing after signing in

---

gnd/src/androidTest/java/com/google/android/gnd/AcceptTermsOfServiceTest.java
gnd/src/androidTest/java/com/google/android/gnd/AddFeatureTest.java
gnd/src/androidTest/java/com/google/android/gnd/SetPreferencesRule.java
gnd/src/sharedTest/java/com/google/android/gnd/FakeData.java
gnd/src/sharedTest/java/com/google/android/gnd/persistence/remote/FakeRemoteDataStore.java
gnd/src/sharedTest/java/com/google/android/gnd/system/auth/FakeAuthenticationManager.java
gnd/src/test/java/com/google/android/gnd/MainViewModelTest.java
gnd/src/test/java/com/google/android/gnd/repository/FeatureRepositoryTest.java
gnd/src/test/java/com/google/android/gnd/repository/TermsOfServiceRepositoryTest.java
gnd/src/test/java/com/google/android/gnd/repository/UserRepositoryTest.java
gnd/src/test/java/com/google/android/gnd/system/ApplicationErrorManagerTest.java
gnd/src/test/java/com/google/android/gnd/ui/common/FeatureHelperTest.java
gnd/src/test/java/com/google/android/gnd/ui/home/featuredetails/BaseMenuVisibilityTest.java

Refactor, merge duplicates, and rename fake data constants.
Also simplifies setting of test project in `FakeRemoteDataStore`, removing conditional logic (https://testing.googleblog.com/2014/07/testing-on-toilet-dont-put-logic-in.html). 
Fixes #1041.

[Code health] Consolidate and rename test data

---

gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java
gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/PolygonDrawingViewModel.java

Fixes #1033
Fixes #1049
Displays a line between the last selected point and current camera target. Also includes code cleanup.
https://user-images.githubusercontent.com/8918023/142265832-d741015f-741e-4c19-8ec3-2d2396e2165c.mp4
@gino-m @atalekar  PTAL?
P.S. I'll try to add unit tests later in a separate PR.

[Polygon] Render a line between last added point and current target

---

gnd/src/main/java/com/google/android/gnd/persistence/mbtiles/MbtilesFootprintParser.java
gnd/src/main/java/com/google/android/gnd/repository/OfflineAreaRepository.java
gnd/src/main/java/com/google/android/gnd/util/ImmutableListCollector.java

This commit cleans up the mbtiles footprint parser by:
- deleting unused methods.
- wrapping return values in RX constructs
- making use of collection helpers to reduce stream boilerplate.
It also adds two helper functions to ImmutableList collector to simplify
working with collections in the context of RX streams.

refactor: clean up mbtiles parser; use RX

---

gnd/src/main/java/com/google/android/gnd/system/CameraManager.java
gnd/src/main/java/com/google/android/gnd/system/StorageManager.java
gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java
gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java

TODO: Figure out a way to update the response in PhotoFieldViewModel from EditObservationViewModel.
Fixes #
@... PTAL?

Replace deprecated API for launching intents

---

gnd/src/main/java/com/google/android/gnd/model/Project.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/ProjectEntity.java
gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/ProjectConverter.java
gnd/src/test/java/com/google/android/gnd/persistence/local/LocalDataStoreTest.java
gnd/src/test/java/com/google/android/gnd/persistence/remote/firestore/schema/FeatureConverterTest.java
gnd/src/test/java/com/google/android/gnd/persistence/remote/firestore/schema/ObservationConverterTest.java

Replaces `putLayer(id, layer)` with `putLayer(layer)`.
@gino-m  PTAL?

Cleanup deprecated method

---

cloudbuild.yaml

Improve overall run time:
* Pull & extract cache only if dependencies have not changed
* Build & save cache only when dependencies have changed
Fixes #270
Current run time: ~13.5 mins
New run time:
Run # | Cache Present in bucket | Cache pulled & extracted | Cache built & saved | Time taken
------|-------------------------|---------------------------|----------------------|------------
1 a1c24b7 | No / Obsolete | No | Yes | 00:09:37
2 4b98ce9  | Yes | Yes | No | 00:06:52
Notes:
* Since the md5 depends on file size, it might result in a collision if only a number is changed in the gradle file. But the improvements are still huge and we can tackle that minor problem later if needed.
* We should also consider adding `retention policy` to the cache bucket to avoid storing obsolete caches. …

Improve CI build time

---

gnd/src/main/java/com/google/android/gnd/Config.kt
gnd/src/main/java/com/google/android/gnd/model/layer/Layer.java
gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/LayerEntity.java
gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/LayerConverter.java
gnd/src/main/java/com/google/android/gnd/repository/ProjectRepository.kt
gnd/src/test/java/com/google/android/gnd/repository/ProjectRepositoryTest.java
gnd/src/test/java/com/google/android/gnd/ui/home/AddFeatureDialogFragmentTest.kt

Remove contributorsCanAdd

---

gnd/src/main/java/com/google/android/gnd/MainViewModel.kt

This fixes an issue on startup whereby navigations were executed on the
IO thread (which android doesn't allow). We compose the auth manager
stream with the userRepository. The userRepository returns an observable
that observes on the IO thread; post-composition, the resulting stream
takes the observation thread of the compose argument; so the final
stream was being observed on the IO thread.
The fix is straightforward: set the resulting stream to observe on the
UI thread after the composition is performed.
@gino-m @shobhitagarwal1612

fix: execute navigations on the main thread

---

cloudbuild.yaml

Changes made:
1. Building instrumentation apk in "assemble_debug" step
2. Running instrumentation tests in firebase test lab
@gino-m  PTAL?

Run instrumentation tests only for push to master

---

ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionFragment.kt

Set the offScreenPageLimit of the Data Collection ViewPager2 to 1 to clean up fragments older than the last one and newer than the next one.
@gino-m PTAL?

Cleanup out of range Data Collection fragments

---

ground/src/main/java/com/google/android/ground/persistence/remote/RemoteDataStore.java
ground/src/main/java/com/google/android/ground/persistence/remote/firestore/FirestoreDataStore.java
ground/src/main/java/com/google/android/ground/persistence/remote/firestore/schema/SubmissionCollectionReference.kt
ground/src/main/java/com/google/android/ground/repository/SubmissionRepository.kt
ground/src/main/java/com/google/android/ground/rx/ValueOrError.kt
sharedTest/src/main/java/com/google/android/ground/test/persistence/remote/FakeRemoteDataStore.java

Things done:
1. Remove dependency on `ValueOrError` and use kotlin `Result`
2. Cleanup unused static helper methods
@JSunde  PTAL?

Replace ValueOrError with Result in firestore

---

cloud-builder/chat-notifier.yaml

Towards #1177 
Configures a google chat notifier when a build is passes / fails / timeouts on the master branch.
https://cloud.google.com/build/docs/configuring-notifications/notifiers
How does it work?
Cloud run free tier:
Tested by removing the "master" filter and triggering a cloud build. A notification was sent to the google chat space after the build was complete. 
@gino-m  PTAL?
P.S. The same config can be extended to be used for web repo

Save config for google chat notifications

---

ground/src/main/java/com/google/android/ground/model/geometry/Coordinate.kt
ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/LoiCardSource.kt
ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/MapContainerFragment.kt
ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/MapContainerViewModel.kt
ground/src/main/java/com/google/android/ground/ui/map/CameraPosition.kt
ground/src/main/java/com/google/android/ground/ui/map/LoiCard.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/GoogleMapsFragment.kt
ground/src/test/java/com/google/android/ground/ui/home/mapcontainer/LoiCardSourceTest.kt

Towards #1153 
* Filter the cards based on current LatLng bounds
* List should auto-update on panning/zooming in addition to switching survey
https://user-images.githubusercontent.com/8918023/191056149-11469fe4-fa5a-4bc1-9502-316c2a2dc351.mp4
@JSunde @gino-m PTAL?

Filter LOI cards based on visibility

---

ground/src/main/java/com/google/android/ground/model/locationofinterest/LocationOfInterest.kt
ground/src/main/java/com/google/android/ground/model/mutation/LocationOfInterestMutation.kt
ground/src/main/java/com/google/android/ground/persistence/local/room/RoomLocalDataStore.kt
ground/src/main/java/com/google/android/ground/repository/LocationOfInterestRepository.kt
ground/src/test/java/com/google/android/ground/persistence/local/LocalDataStoreTest.kt

Towards #1288 
Replaces references of `builder()` with kotlin object instantiation and `copy()`

Remove builder() from LocationOfInterestMutation

---

ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/MapContainerFragment.kt
ground/src/main/res/layout/map_container_frag.xml
ground/src/main/res/layout/map_home_layout.xml

Towards #1153 
Anchor gps button to top of card layout to avoid hiding it when recycler view gets populated

[Loi Cards] Anchor GPS button to cards

---

ground/src/main/java/com/google/android/ground/MainViewModel.kt
ground/src/main/java/com/google/android/ground/repository/SurveyRepository.kt
ground/src/main/java/com/google/android/ground/rx/Loadable.kt
ground/src/main/java/com/google/android/ground/ui/home/HomeScreenFragment.kt
ground/src/main/java/com/google/android/ground/ui/submissiondetails/SubmissionDetailsFragment.java
ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorDialogFragment.java

Fixes #1303
This PR changes the behavior of displaying the survey selector is no survey is active.
Things done:
* Removed `NOT_FOUND` state from Loadable.
* Manually dispose survey sync subscription after logout to prevent firebase from attempting to sync without any user.

Fix crash when attempting to logout

---

ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/MapContainerViewModel.kt
ground/src/main/java/com/google/android/ground/ui/map/MapController.kt
ground/src/test/java/com/google/android/ground/ui/map/MapControllerTest.kt

Fixes #1321 
When the app is killed forcefully, the active survey id momentarily changes to empty string. The current logic translates that to default position (0, 0). After that, the actual survey id kicks in but the position is already changed by that time.
This PR fixes that behavior by not returning anything if last saved position doesn't exist in shared prefs.
@scolsen @JSunde  PTAL?

Prevent reseting last saved position

---

ground/src/main/java/com/google/android/ground/ui/map/MapController.kt
ground/src/test/java/com/google/android/ground/ui/map/MapControllerTest.kt

Handle NPE when creating flowables. They don't gracefully handle null values and throw an error.
@JSunde  PTAL?

Fix instrumentation tests

---

ground/src/main/res/layout/data_collection_header.xml
ground/src/main/res/layout/question_data_collection_frag.xml

Added a new subcomponent view for the Data Collection Task header so it can be reused between different task fragments
Towards #1146 
@shobhitagarwal1612 PTAL

Pull out the Data Collection Task header into subcomponent

---

build.gradle
ground/build.gradle

Upgrade SDK and Firebase APIs, use Firebase BoM

---

ground/src/main/java/com/google/android/ground/ui/map/gms/GoogleMapsFragment.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/LocationOfInterestClusterManager.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/LocationOfInterestClusterRenderer.kt

Fixes an issue whereby cluster items were not rendered using custom icons. Turns out I had implemented the wrong method *and* did not set the renderer properly. We now implement the correct method and ensure the marker icon factory is initialized, if it isn't, default marker icons will be rendered as a fallback.
Fixes #1387
@gino-m

fix: render custom icons for cluster items

---

ground/src/androidTest/java/com/google/android/ground/TestRemoteStorageModule.kt
ground/src/main/java/com/google/android/ground/persistence/remote/RemotePersistenceModule.kt
ground/src/test/java/com/google/android/ground/TestRemoteStorageModule.kt

Fixes #1399 
Renamed RemoteStorageModule to RemotePersistenceModule.
@... PTAL?

Renamed RemoteStorageModule to RemotePersistenceModule

---

ground/build.gradle

Required to use in-memory SQLite on Apple M1 chipsets.
Towards #1471.

Update roboelectric for M1 chipset support

---

ground/build.gradle
ground/src/main/java/com/google/android/ground/repository/SurveyRepository.kt
ground/src/main/java/com/google/android/ground/ui/home/HomeScreenViewModel.kt
ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorViewModel.kt
ground/src/test/java/com/google/android/ground/repository/SurveyRepositoryTest.kt

Also pushes launch of `activateSurvey()` up to view models so that exceptions can be propagated and handled there.
Towards #1471.
@shobhitagarwal1612 Could you PTAL?

Simplify SurveyRepository tests using in memory local db instead of mocks

---

ground/src/main/java/com/google/android/ground/persistence/local/LocalValueStore.kt
ground/src/main/java/com/google/android/ground/repository/LocationOfInterestRepository.kt
ground/src/main/java/com/google/android/ground/repository/MapStateRepository.kt
ground/src/main/java/com/google/android/ground/repository/SurveyRepository.kt
ground/src/main/java/com/google/android/ground/repository/TermsOfServiceRepository.kt
ground/src/test/java/com/google/android/ground/repository/LocationOfInterestRepositoryTest.kt

Replaces re-declaration of LocalValueStore var's getter/setter in repository with `by`

[Code health] Cleanup LocalValueStore

---

ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/TaskConverter.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewPagerAdapter.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/NumberTaskFragment.kt
ground/src/main/res/layout/number_task_frag.xml

Fixes #1563
Adds support for persisting "number" type tasks to local db and displaying a task view. Web app already supports this type from the earlier version.
@JSunde  PTAL?

[Data Collection] Add support for number type task

---

ground/src/main/java/com/google/android/ground/repository/LocationOfInterestRepository.kt
ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt
ground/src/test/java/com/google/android/ground/repository/LocationOfInterestRepositoryTest.kt

This prevents circular deps and encourages stricter separation of concerns. Towards #1373

Decouple Survey and LOI repos

---

ground/src/main/java/com/google/android/ground/ui/datacollection/components/ButtonAction.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/components/TaskButton.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/components/TaskView.kt
ground/src/main/res/drawable/survey_synced_background.xml
ground/src/main/res/drawable/task_chip_image_button.xml
ground/src/main/res/drawable/task_dark_green_btn_selector.xml
ground/src/main/res/drawable/task_light_green_btn_selector.xml
ground/src/main/res/drawable/task_transparent_btn_selector.xml
ground/src/main/res/layout/task_chip_button_dark_green.xml
ground/src/main/res/layout/task_chip_button_light_green.xml
ground/src/main/res/layout/task_chip_button_transparent.xml
ground/src/main/res/layout/task_chip_button_with_icon_light_green.xml
ground/src/main/res/layout/task_chip_button_with_text_and_icon_transparent.xml
ground/src/main/res/layout/task_frag_with_header.xml
ground/src/main/res/layout/task_frag_without_header.xml
ground/src/main/res/values/colors.xml
ground/src/main/res/values/styles.xml

Fixes #1621
This is a no-op change. Adds the xml layouts, styles and helper classes for TaskView and TaskButton.
These will be used in the upcoming PRs for refactoring task fragments.
Full prototype: https://github.com/google/ground-android/pull/1622
[Design doc](https://docs.google.com/document/d/15CGT-9LvgarzBvrC8kPPAEHlrGuZCqVL0i9lpmya2dU/r/0-OLrHylzybpz6_mkioEm7og/edit#)

[Revamped Data Collection UI] Add layouts for TaskButton and TaskView

---

.idea/codeStyles/Project.xml
ground/build.gradle
ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/date/DateTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/number/NumberTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/photo/PhotoTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/point/DropAPinTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/PolygonDrawingTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/text/QuestionTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/time/TimeTaskFragment.kt
ground/src/main/res/navigation/nav_graph.xml
ground/src/test/java/com/google/android/ground/HiltExt.kt
ground/src/test/java/com/google/android/ground/ui/datacollection/DataCollectionFragmentTest.kt

Fixes #1608
Previously we used an ActivityScoped view model to share the DataCollectionViewModel between the DataCollectionFragment and the Task fragments, but this caused issues when the user completed one job and opened another because the DataCollectionViewModel would not be cleared. Now the DataCollectionViewModel is scoped to a new nav graph which includes only the Data Collection fragments so we properly create a new DataCollectionViewModel instance for each new job.

Use navGraph scoped ViewModel to share DataCollectionViewModel

---

ground/src/main/java/com/google/android/ground/persistence/local/LocalValueStore.kt
ground/src/main/java/com/google/android/ground/persistence/local/SharedPreferencesModule.kt
ground/src/main/java/com/google/android/ground/util/StrictModeExtensions.kt

Fixes #1624.
Note that it's not currently easily disable StrictMode warnings caused by Firebase Crashlytics initialization. Alternatives are currently being investigated by Firebase team: https://github.com/firebase/firebase-android-sdk/issues/3795

Disable StrictMode for quick reads/writes

---

ground/build.gradle
ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/MapCardAdapter.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/FeatureClusterRenderer.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/GoogleMapsFragment.kt

Previously, we did not render the actively selected map feature LOI using the larger icon. This commit fixes that by doing a few things:
1. We upgrade to a newer version of the clustering utility. By default, the utility will only re-render clusters and individual markers when the underlying cluster set has changed. This is dependent on the clustering algortihm, and the algo we currently use has no knowledge of map feature selection. Luckily, this newer version of the API adds a shouldRender method that we can override to force the renderer to re-render on selection changes.
2. Moves calls to cardSelection callback invocations in the map adapter to view holder binding. This is the correct place to call it. Calling this in the updateData method will incorrectly reset active LOI state and …

Active loi UI fix

---

ground/src/main/java/com/google/android/ground/ui/datacollection/components/TaskButton.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/components/TaskButtonFactory.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/components/TaskHeaderPopupView.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/components/TaskView.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/components/TaskViewFactory.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/date/DateTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/number/NumberTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/photo/PhotoTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/point/DropAPinTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/PolygonDrawingTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/text/TextTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/time/TimeTaskFragment.kt
ground/src/main/res/drawable/baseline_arrow_drop_up_24.xml
ground/src/main/res/drawable/light_green_bg.xml
ground/src/main/res/layout/popup_layout.xml
ground/src/main/res/values/styles.xml

Towards https://github.com/google/ground-android/issues/1621
Show a popup containing the task label whenever the header card is clicked. Autohide the popup if user clicks anywhere outside of the popup.
[Design Doc](https://docs.google.com/document/d/15CGT-9LvgarzBvrC8kPPAEHlrGuZCqVL0i9lpmya2dU/r/0-OLrHylzybpz6_mkioEm7og/edit#)
[Figma Mocks](https://www.figma.com/file/r2uGtyOiWoDa29za7DNuUc/Ground-Acacia-UX?node-id=1566%3A47266&t=dG3k5Uq9xfJLrC3s-0)
@scolsen @JSunde PTAL?

[Data Collection] Display a popup containing task label for tasks without a header

---

ground/src/main/java/com/google/android/ground/model/submission/TextTaskData.kt
ground/src/main/java/com/google/android/ground/persistence/sync/LocalMutationSyncWorker.kt
ground/src/main/java/com/google/android/ground/repository/UserMediaRepository.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/photo/PhotoTaskViewModel.kt
ground/src/test/java/com/google/android/ground/repository/UserMediaRepositoryTest.kt

Also add valid filename check to add more valuable error messages in case an invalid path is passed to the UserMediaRepository
Fixes #1684
@JSunde  @scolsen  PTAL?

Fix photo upload flow

---

ground/src/main/java/com/google/android/ground/ui/map/gms/FeatureClusterRenderer.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/GoogleMapsFragment.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/renderer/FeatureRenderer.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/renderer/PolygonRenderer.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/renderer/PolylineRenderer.kt

The purpose of this PR is to refactor out rendering related business logic for map features to a separate package. This would also improve code readability.
`GoogleMapsFragment` contains rendering logic for following features:
* Point
* Polygon
* Polyline
* Clusters
Currently, clustering is only supported for `Points`. Also, we don't have a standalone renderer for points. This is handled by separate classes `FeatureClusterManager` and `FeatureClusterRenderer`. So, no further refactoring needed for them.
For Polygon and Polyline, all business logic is embedded within `GoogleMapsFragment`. This can be improved by adding an interface and moving the logic to their own separate implementations.
In the future, we may have to think about adding clustering logic for polygon and polylines as well. …

[Code Health] Abstract out map rendering logic for polygon and polyline features

---

ground/build.gradle
ground/src/main/java/com/google/android/ground/ui/map/gms/mog/LatLngBoundsExt.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/mog/MogClient.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/mog/MogCollection.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/mog/MogImageMetadata.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/mog/MogMetadata.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/mog/MogMetadataReader.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/mog/MogTile.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/mog/MogTileDownloader.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/mog/MogTileMetadata.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/mog/MogTileProvider.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/mog/MogTileReader.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/mog/MogTilesRequest.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/mog/README.md
ground/src/main/java/com/google/android/ground/ui/map/gms/mog/SeekableInputStream.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/mog/TiffTag.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/mog/TiffTagDataType.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/mog/TileCoordinates.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/mog/UrlInputStream.kt
ground/src/test/java/com/google/android/ground/ui/map/gms/mog/SeekableBufferedInputStreamTest.kt
sharedTest/build.gradle

Towards #1596.
This includes only support class implementation. Implementations are not yet used to display or download tiles. Unit test coverage still needed.

Add support for batch and on demand retrieval of tiles from COGs

---

ground/src/main/java/com/google/android/ground/model/submission/DropAPinTaskData.kt
ground/src/main/java/com/google/android/ground/repository/LocationOfInterestRepository.kt
ground/src/main/java/com/google/android/ground/ui/common/AbstractMapContainerFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/point/DropAPinMapFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/point/DropAPinTaskViewModel.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/PolygonDrawingMapFragment.kt
ground/src/main/java/com/google/android/ground/ui/map/CameraPosition.kt
ground/src/main/java/com/google/android/ground/ui/map/MapController.kt
ground/src/main/java/com/google/android/ground/ui/map/MapFragment.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/FeatureClusterRenderer.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/GmsExt.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/GoogleMapsFragment.kt
ground/src/test/java/com/google/android/ground/ui/map/MapControllerTest.kt

Fixes #1602 
* Ensures markers and clusters aren't shown at the same zoom level
* Clicking a cluster zooms to the LOI bounds contained within the cluster
* When a survey is loaded for the first time, map camera pans to all LOIs
@gino-m  PTAL?

Improve map clustering UX

---

ground/src/main/java/com/google/android/ground/model/geometry/Geometry.kt
ground/src/main/java/com/google/android/ground/model/geometry/InvalidGeometryException.kt
ground/src/test/java/com/google/android/ground/model/geometry/GeometryValidatorTest.kt

Use InvalidGeometryException instead of IllegalStateException when geometry is invalid

---

ground/src/main/res/drawable/launch_screen.xml
ground/src/main/res/values/colors.xml

Background was white, making border around logo invisible. Updated to same background color used in web app
@vittorino FYI
@JSunde PTAL?

Tweak splash screen background color

---

ground/src/main/res/drawable/launch_screen.xml
ground/src/main/res/values/colors.xml

Follow-up to #1851.
@JSunde PTAL

Use attr color instead of @color

---

ground/src/main/java/com/google/android/ground/repository/OfflineAreaRepository.kt
ground/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorViewModel.kt
ground/src/main/res/layout/offline_area_selector_frag.xml
ground/src/main/res/values/strings.xml

Fixes #1872 
@JSunde PTAL?
@amegantz Any advice on the messsage shown at the bottom of the screen? I was thinking:
> Imagery unavailable. Select another area to download to your device
Wdyt?

Show "no data" message when area with no imagery is selected

---

ground/src/main/java/com/google/android/ground/GroundApplication.kt

This is the solution recommended by Firebase support. It also solves Maps SDK lag when strict policy is enabled. Related to https://github.com/firebase/firebase-android-sdk/issues/3795
Closes #1882
@shobhitagarwal1612 @JSunde FYI

Log StrictMode thread warnings except reads

---

ground/src/main/java/com/google/android/ground/ui/common/AbstractMapContainerFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/point/DropAPinMapFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/point/DropAPinTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/PolygonDrawingMapFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/PolygonDrawingTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt
ground/src/main/java/com/google/android/ground/ui/map/MapFragment.kt
ground/src/main/java/com/google/android/ground/ui/map/MapProviderModule.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/GoogleMapsFragment.kt
ground/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorFragment.kt

Labeling the interface "Fragment" makes it obvious wherever its used that it will always be referring to a Fragment and should be treated as such. Unfortunately Android `androidx.fragment.Fragment` is a concrete class, so we can't extend it in an interface.
Towards #1907
@JSunde PTAL?

Minor renames of map abstractions

---

ground/src/main/java/com/google/android/ground/system/GoogleApiManager.kt
ground/src/main/java/com/google/android/ground/ui/common/ViewModelModule.kt
ground/src/main/java/com/google/android/ground/ui/startup/StartupFragment.kt
ground/src/main/java/com/google/android/ground/ui/startup/StartupViewModel.kt

Fixes #901
Fixes #1881
The app gets stuck with a blank screen as the initialization flow is called in `onAttach()` but this method is only called once during creation and not when resuming the fragment from background.
Verified by running the below steps manually:
1. Turn off the device screen
2. Install the app using AS
3. Wake the device

Move app initialization to onResume() to prevent blank screen

---

ground/src/main/java/com/google/android/ground/persistence/local/room/dao/OfflineAreaDao.kt
ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomOfflineAreaStore.kt
ground/src/main/java/com/google/android/ground/persistence/local/stores/LocalOfflineAreaStore.kt
ground/src/main/java/com/google/android/ground/repository/OfflineAreaRepository.kt
ground/src/main/java/com/google/android/ground/ui/offlineareas/OfflineAreasViewModel.kt
ground/src/test/java/com/google/android/ground/persistence/local/LocalDataStoreTests.kt

Towards #1581 
Migrates usages of flowable to flow in offline area screens
Verified for regressions by running the app locally, downloading offline areas and then removing them.

[Rx -> Coroutine] Migrate Offline Area Data layer

---

ground/src/main/java/com/google/android/ground/MainActivity.kt
ground/src/main/java/com/google/android/ground/ui/common/Navigator.kt
ground/src/test/java/com/google/android/ground/MainViewModelTest.kt
ground/src/test/java/com/google/android/ground/ui/home/HomeScreenFragmentTest.kt
ground/src/test/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragmentTest.kt
ground/src/test/java/com/google/android/ground/ui/tos/TermsOfServiceFragmentTest.kt

Reverts google/ground-android#2020
This is causing an regression.

Revert "Use coroutine in Navigator"

---

ground/build.gradle
ground/src/main/java/com/google/android/ground/model/SurveyListItem.kt
ground/src/main/java/com/google/android/ground/persistence/remote/RemoteDataStore.kt
ground/src/main/java/com/google/android/ground/persistence/remote/firebase/FirestoreDataStore.kt
ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/SurveysCollectionReference.kt
ground/src/main/java/com/google/android/ground/repository/SurveyRepository.kt
ground/src/main/java/com/google/android/ground/system/NetworkManager.kt
ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveyListAdapter.kt
ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorViewModel.kt
ground/src/main/res/layout/survey_card_item.xml
ground/src/test/java/com/google/android/ground/repository/SurveyRepositoryTest.kt
ground/src/test/java/com/google/android/ground/ui/surveyselector/SurveySelectorFragmentTest.kt
sharedTest/build.gradle
sharedTest/src/main/kotlin/com/sharedtest/persistence/remote/FakeRemoteDataStore.kt

Also upgrade Firebase deps and introduces some minor refactors. Fixes #1973

Make survey list reactive to local and remote changes

---

ground/src/main/java/com/google/android/ground/Config.kt
ground/src/main/java/com/google/android/ground/persistence/local/room/entity/TileSourceEntity.kt
ground/src/test/java/com/google/android/ground/persistence/local/LocalDataStoreTests.kt

Room treats non-null values assigned to boxed types (e.g. Int?, Integer) as explicit values and will not auto-generate IDs when these values are provided. This was causing UNIQUNESS constraint failures when inserting/updating tilesource entites, as we were using `0` as a default.
Converting to a non-boxed primitive type `Int` results in the correct behavior (Room treats `0` as an indicator that a value should be generated).
Fixes #2044
Note: We can also fix this by setting the default to `null` and retaining the type, so if we need to keep this nullable for some reason that's possible too.

Fix TileSourceEntity id generation.

---

ground/src/main/java/com/google/android/ground/persistence/local/room/dao/LocationOfInterestMutationDao.kt
ground/src/main/java/com/google/android/ground/persistence/local/room/dao/SubmissionMutationDao.kt
ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomLocationOfInterestStore.kt
ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomSubmissionStore.kt
ground/src/main/java/com/google/android/ground/persistence/local/stores/LocalLocationOfInterestStore.kt
ground/src/main/java/com/google/android/ground/persistence/local/stores/LocalSubmissionStore.kt
ground/src/main/java/com/google/android/ground/repository/LocationOfInterestRepository.kt
ground/src/main/java/com/google/android/ground/repository/MutationRepository.kt
ground/src/main/java/com/google/android/ground/repository/SubmissionRepository.kt
ground/src/main/java/com/google/android/ground/ui/syncstatus/SyncStatusViewModel.kt
ground/src/test/java/com/google/android/ground/persistence/local/LocalDataStoreTests.kt
ground/src/test/java/com/google/android/ground/repository/LocationOfInterestRepositoryTest.kt

Updates mutations, submission and LOI, to use FLow and suspend functions. Also updates tests accordingly. I've verified the sync UI works as expected after this change.
In one or two places, I've used RX interop to avoid needing to scope-bloat the conversions at this time, but we should be able to eliminate those calls relatively soon.

Convert a bunch of mutations related streams to Flow and suspend funs.

---

ground/src/main/java/com/google/android/ground/ui/common/CameraPermissionDeniedDialogFragment.kt
ground/src/main/java/com/google/android/ground/ui/common/CameraPermissionDeniedDialogViewModel.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/photo/PhotoTaskFragment.kt
ground/src/main/res/layout/camera_permission_denied_dialog.xml
ground/src/main/res/navigation/nav_graph.xml
ground/src/main/res/values/strings.xml

Adds a new dialog that informs users that we need camera permissions to submit photos. The user can select OK and attempt a submission again by granting permissions, or exit the data collection task.
Fixes #2087.
video: https://github.com/google/ground-android/assets/11237600/d3ca4083-9d8c-4c1c-99a3-ff5f3721ea7a
@gino-m @shobhitagarwal1612

Photo Task: Fix crash on photo permissions denial.

---

ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorFragment.kt
ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorViewModel.kt
ground/src/main/res/values/strings.xml
ground/src/test/java/com/google/android/ground/ui/surveyselector/SurveySelectorFragmentTest.kt

Fixes #1497
Fixes #2095 
Add exception handling if any error occurs when activating a survey in survey selector fragment. Currently it logs the exception message for debugging and shows a generic message "Something went wrong" to the user. 
@gino-m  PTAL?

Handle exceptions when attempting to activate survey

---

ground/src/main/java/com/google/android/ground/model/job/Job.kt

Previously, if a Job lacked a default style value, we rendered features with the color value 0. We use ARGB color format, in which this value corresponds to a completely transparent color. In result, polygons and points in a survey would not be rendered at all if a survey's job lacked a proper default style.
We now instead render features with a default, opaque black color when the job lacks default styling. This is the same behavior as the web app.
Fixes #2092

Render polygons opaquely when Jobs lack a default style.

---

ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionFragment.kt

Fixes #1975 
This updates the reference anchor point for the data collection progress bar. Before this change it was anchored to a non-existent view and so never showed up. Now it is anchored to the correct view.
Fill out a survey and verify the progress bar is still there.
@gino-m PTAL?

Updating anchor point of the progress bar to the correct xml ID

---

ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskViewModel.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/DrawAreaTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/DrawAreaTaskIncompleteResult.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/DrawAreaTaskResult.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/DrawAreaTaskViewModel.kt
ground/src/main/res/values/strings.xml
ground/src/main/res/values/styles.xml
ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/polygon/DrawAreaTaskFragmentTest.kt

Fixes #2102
Default behavior of "Undo" button is to display it only when the response is empty. In draw area task, we were only persisting the response when the drawing was complete. So, we also had to override the default "undo" behavior which wasn't working as expected. 
Proposed solution in this PR:
1. Save incomplete "linestring" to response map and remove overridden "undo" behavior.
2. Add validation to prevent navigating previous/next when the current response is incomplete
@gino-m  PTAL?

Hide "Undo" button in area task when drawing

---

ground/src/main/java/com/google/android/ground/ui/common/BaseMapViewModel.kt
ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt

Fixes #2173
Fixes #1892
Fixes #2163
We were only persisting the current camera position to shared prefs only for home screen. This PR extends this for all map based screens (data collection tasks, offline area screen, home screen)
Verified by moving the map within a task and navigating back to the home screen and confirming that the viewport is not reset.
@gino-m  PTAL?

Don't reset viewport when resuming from data collection flow

---

build.gradle

Fixes #2183
Verified at HEAD that running `gradlew clean` removes the android-ground/build dir
@gino-m  PTAL?

Add gradle task clean

---

ground/src/main/java/com/google/android/ground/ui/common/SignOutConfirmationDialogViewModel.kt
ground/src/main/java/com/google/android/ground/ui/common/SignOutConfirmationFragment.kt
ground/src/main/java/com/google/android/ground/ui/home/HomeScreenFragment.kt
ground/src/main/java/com/google/android/ground/ui/home/HomeScreenViewModel.kt
ground/src/main/res/layout/sign_out_confirmation_dialog.xml
ground/src/main/res/navigation/nav_graph.xml
ground/src/main/res/values/strings.xml

Adds a sign out warning dialog informing users their unsaved data will be lost.
Fixes #1683
Adds a sign out confirmation screen to Ground, warning users that unsaved data will be lost on sign out. Currently this is only implemented for sign outs from the home screen fragment.
Sign out of ground from the hamburger menu and verify that the screen comes up.
Clicking cancel should exit the dialog.
Clicking sign out should sign the user out.
https://github.com/google/ground-android/assets/77077870/fc4ea211-5796-4802-92bb-79e12d20d683
@shobhitagarwal1612   PTAL?

Adding sign out warning dialog to the home screen

---

ground/src/main/java/com/google/android/ground/model/job/Job.kt
ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt

Fixes #2176
Fixes #2192
Jobs without any tasks with `isAddLoiTask` bit are also getting included for `adHocLoiJobs`, causing problems when attempting to save the data.
Don't include jobs for adhoc data collection if the job doesn't contain any tasks with `isAddLoiTask` set to true. Also add another validation to confirm that the job must contain exactly one add loi task
Steps for collecting data for `AdhocLoiJobs`:
1. App displays a job card without an LOI if it's data collection strategy is `AD_HOC`, `MIXED`, or `UNKNOWN`.
2. User clicks the job card
3. After data collection, the app first tries to create a new LOI
4. It attempts to get the first task with `isAddLoiTask` bit set to true. Else throws an exception.
5. After LOI is saved, it enqueues a new submission using the LOI created …

Hide adhoc job cards if AddLoiTask is missing

---

ground/src/main/java/com/google/android/ground/model/job/Job.kt
ground/src/main/java/com/google/android/ground/persistence/local/room/converter/SubmissionDataConverter.kt
ground/src/main/java/com/google/android/ground/persistence/local/room/converter/SubmissionDeltasConverter.kt
ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionConverter.kt

This commit adds a specific exception type for the case in which a caller attempts to retrieve a task from a Job that does not contain a task with the designated ID.
Updates callsites to properly handle and log this exception (in all cases we just ignore the data).
Fixes #2179

Job: Handle unknown tasks

---

ground/src/main/java/com/google/android/ground/persistence/sync/LocalMutationSyncWorker.kt
ground/src/main/java/com/google/android/ground/repository/MutationRepository.kt
ground/src/test/java/com/google/android/ground/persistence/sync/LocalMutationSyncWorkerTest.kt

Fixes #2129.
Not sure how to test this, open to suggestions.
This also ensures "create LOI" occurs before "create submission". See #2235 for additional fixes.

Process mutations in the order in which they were created

---

config/detekt/detekt.yml
ground/build.gradle
ground/src/main/java/com/google/android/ground/persistence/local/LocalValueStore.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/DrawAreaTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/DrawAreaTaskViewModel.kt
ground/src/main/res/drawable/touch_app_24.xml
ground/src/main/res/values/strings.xml
ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/polygon/DrawAreaTaskFragmentTest.kt

Fixes #2223
Uses jetpack compose to display an alert dialog when draw area task is opened for the first time by the user.
[draw_area_instructions.webm](https://github.com/google/ground-android/assets/8918023/3e287dac-c890-44b0-884e-e077b2c1f26f)
@gino-m  PTAL?

[Data Collection] Show instructions dialog for draw area task when opened for the first time

---

ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/DrawAreaTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/AdaptiveSpacingItemDecorator.kt
ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/MapTypeDialogFragment.kt
ground/src/main/res/layout/map_type_dialog_item.xml

Fixes #1781 
Fill the width and equally space the items in portrait mode. 
In landscape mode, use a hardcoded spacing to left-align the items.
[map_type_selector_adaptive_spacing.webm](https://github.com/google/ground-android/assets/8918023/7a640367-fed7-4282-a558-3fc784142ddc)
@gino-m  PTAL?

Prevent horizontal scrolling for map type selector

---

ground/src/main/java/com/google/android/ground/ui/map/gms/mog/MogClient.kt

Fixes #2265 
Fixes #2234
Catch all exceptions when attempting to load URLs for tiles. Solution also fixes invalid BigTIFF file format!
Logged error message for broken URLs:
Logged error message for bad tiff format:
PTAL @gino-m

Catch all exception when loading URL for offline tiles.

---

cloudbuild.yaml

Fixes #2269
Gradle daemons are background processes which are spawned to speed up subsequent builds. It is generally recommended to disable these for CI builds.
https://docs.gradle.org/8.5/userguide/gradle_daemon.html#disable_for_a_build
@sufyanAbbasi PTAL?

Disable gradle daemon for remote builds

---

ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt

Fixes #2283.
Launches snackbar hint introduced in #2132 in `viewLifecycleOwner.lifecycleScope` instead of `lifecycleScope` to ensure coroutine is bound to lifecycle of view. Also, fails gracefully in the rare case there could be a race condition with view destruction.

Fix crash on startup

---

ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionFragment.kt
ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt
ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt
ground/src/test/java/com/google/android/ground/ui/home/HomeScreenFragmentTest.kt

Towards #1975 
Waits a little bit after the task view has changed in order to recalculate the progress bar position, which is based on the top of the action buttons container. This is is in order to allow the action buttons to settle into their position after the keyboard has moved out of the way, since the callbacks are called too quickly.
Also replaces deprecated Java `systemWindowInsetTop` property (sorry, I used Bard/Gemini for that).
- Clicked on a text task, wait for the keyboard to show up, then moved to the next and previous tasks while the action buttons are pushed up.
@gino-m  PTAL!

Add a small delay after the page scroll is idle to calculate the progress bar position.

---

ground/src/main/res/navigation/nav_graph.xml
ground/src/test/java/com/google/android/ground/ui/datacollection/DataCollectionFragmentTest.kt

Towards #708
Adds unit tests for following behaviors:
* Draft is saved when clicking next or previous button
* Tasks are pre-loaded when data collection fragment is opened with draft submission
@gino-m  PTAL?

Add unit tests for saving and loading drafts in data collection fragment

---

ground/src/main/java/com/google/android/ground/ui/common/EphemeralPopups.kt
ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt
ground/src/main/res/layout/basemap_layout.xml
ground/src/main/res/values/strings.xml

Updates our snackbar popup to support two enhancements:
1. The location lock button moves dynamically so that it is not obscured by the snackbar
2. The snackbar has a dismiss action which, on tap, dismisses the snackbar.
Towards #2285

Home: Adjust location lock position for snackbar.

---

ground/src/main/java/com/google/android/ground/Config.kt
ground/src/main/java/com/google/android/ground/model/locationofinterest/LocationOfInterest.kt
ground/src/main/java/com/google/android/ground/model/mutation/LocationOfInterestMutation.kt
ground/src/main/java/com/google/android/ground/persistence/local/room/converter/ConverterExt.kt
ground/src/main/java/com/google/android/ground/persistence/local/room/entity/LocationOfInterestEntity.kt
ground/src/main/java/com/google/android/ground/persistence/local/room/entity/LocationOfInterestMutationEntity.kt
ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/LoiConverter.kt
ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/LoiDocument.kt
ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/LoiMutationConverter.kt
ground/src/main/java/com/google/android/ground/repository/LocationOfInterestRepository.kt
ground/src/test/java/com/google/android/ground/persistence/local/LocalDataStoreTests.kt
ground/src/test/java/com/google/android/ground/persistence/remote/firebase/schema/LoiMutationConverterTest.kt
sharedTest/src/main/kotlin/com/sharedtest/FakeData.kt

Fixes #2300.
Send `planned: false` for LOIs that are created ad-hoc from the app. Maps to `isPlanned` on the client.
- Breakpoints at document load time verified that the Firestore was storing "planned:false" for newly created entries and reserialized back on the client.
- Firestore stores the field (see image).
@gino-m PTAL!

Save `planned:false` for ad-hoc LOIs.

---

ground/src/main/java/com/google/android/ground/ui/common/AbstractFragment.kt
ground/src/main/java/com/google/android/ground/ui/common/AbstractMapContainerFragment.kt
ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt
ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt
ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/cards/MapCardAdapter.kt

Fixes #2298
The root cause is that we are initializing the adapter in a coroutine scope and later when the view is generated,  binding the recycler view to the adapter. Sometimes, the adapter takes longer to load and the binding throws an exception.
In order to solve this, move the adapter creation out of the coroutine and do the necessary refactors.
@gino-m  PTAL?

Fix crash on app load due to race condition between initialization of bottom cards adapter

---

ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/point/DropPinTaskMapFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/DrawAreaTaskMapFragment.kt

Found while working on https://github.com/google/ground-android/issues/2299
Cleanup obsolete code. The `mapViewModel` is used for updating the map features.
@gino-m  PTAL?

Remove unused HomeScreenMapContainerViewModel from point/area task fragments

---

ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/DrawAreaTaskFragment.kt
ground/src/main/res/values/strings.xml
ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/polygon/DrawAreaTaskFragmentTest.kt

Fixes #2311
Updates text for draw area info. Uses `onResume()` event to trigger the info dialog, since the `setMenuVisibility()` is deprecated in newer versions of Android and was not reliable for determining the task's visibility state overall.
@gino-m @shobhitagarwal1612 ?

Update draw area info dialog text and use `onResume()` event to show the dialog.

---

ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt

Fixes #2331
Prevent re-triggering the LOI name dialog when clicking Previous (which recomposes the Composable) by saving the dialog open state on the view model. Also performs some refactoring to adhere to Jetpack State Hoisting architecture.
PTAL @gino-m!

Save LOI name dialog state on the view model to prevent re-triggering the LOI name dialog.

---

ground/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorViewModel.kt
ground/src/main/res/navigation/nav_graph.xml

Fixes #2301
Moves back to the map after completing a download.
@gino-m

Move back to map after offline area download.

---

ground/src/main/java/com/google/android/ground/persistence/local/room/converter/ConverterExt.kt
ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomSubmissionStore.kt

Adds a `catch` call to handle exceptions thrown during db -> model object conversion for submissions, preventing these from reaching downstream collectors. As a result, these values will be ignored in any downstream flow or collector of the flow.
Towards #2314

SubmissionStore: Handle exceptions in the allSurveyMutationsFlow

---

ground/src/main/java/com/google/android/ground/Config.kt
ground/src/main/java/com/google/android/ground/persistence/sync/LocalMutationSyncWorker.kt
ground/src/main/java/com/google/android/ground/persistence/sync/SurveySyncWorker.kt
ground/src/main/java/com/google/android/ground/persistence/sync/WorkRequestBuilder.kt
ground/src/test/java/com/google/android/ground/persistence/sync/LocalMutationSyncWorkerTest.kt

Addresses #154
Increases worker retry count to mitigate issues involving jobs that exceed the worker count.
PTAL @gino-m @shobhitagarwal1612 !

Increase worker retry count (also refactor constants into Config.kt).

---

ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt
ground/src/test/java/com/google/android/ground/ui/datacollection/DataCollectionFragmentTest.kt

Fixes #2359
In the current behavior, the validation fails due to empty value and we show an error toast message instead of navigating to previous task fragment. This PR changes that by not validating the task value if it is empty for previous button only.

Allow navigating to previous task for required fields when task is empty

---

ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/multiplechoice/MultipleChoiceItem.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskViewModel.kt
ground/src/main/res/layout/multiple_choice_checkbox_item.xml
ground/src/main/res/layout/multiple_choice_radiobutton_item.xml
ground/src/test/java/com/google/android/ground/CustomViewActions.kt
ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskFragmentTest.kt

Fixes #2362
Ensures that when the user enters some text into the option text area, the option is checked. Will also remove the checkmark if the user backspaces.
Default state:
Entered text:
Deleted text:
Allows checking empty:
Allows unchecking with text:
PTAL @gino-m @justinkimtang !

Select other option when user types something in.

---

CONTRIBUTING.md

It seems like the issue of SHA1 mismatch during Google login could be encountered by everyone who runs the project for the first time. It would be a good idea to add this to a separate troubleshooting tab.
@gino-m PTAL

ADD Troubleshooting SHA1 matching issues

---

ground/src/main/java/com/google/android/ground/persistence/remote/RemoteDataStore.kt
ground/src/main/java/com/google/android/ground/persistence/remote/firebase/FirestoreDataStore.kt
ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/LoiCollectionReference.kt
ground/src/main/java/com/google/android/ground/repository/LocationOfInterestRepository.kt
ground/src/test/java/com/google/android/ground/repository/LocationOfInterestRepositoryTest.kt
ground/src/test/java/com/google/android/ground/ui/datacollection/DataCollectionFragmentTest.kt
sharedTest/src/main/kotlin/com/sharedtest/persistence/remote/FakeRemoteDataStore.kt

This PR hard codes this behavior for surveys by default. As follow-ups, we'll want to 1) add restriction server side and 2) allow survey organizers to control whether data collectors can see each other's data.
Tested manually on Pixel 7, Android 14, API 34.
Towards #2374
@lecrabe @rfontanarosa @jcqli  FYI

[ACLs] Prevent data collectors from seeing each other's LOIs

---

ground/src/main/java/com/google/android/ground/system/auth/GoogleAuthenticationManager.kt

`FirebaseAuth` doesn't block the main thread, so checking its state directly at startup may be producing a race condition on init of the current user. Waiting for auth events before checking should solve this issue.
Fixes #2390

[Auth] Wait for user to be initialized before checking if null

---

ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/location/CaptureLocationTaskMapFragment.kt
ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt
ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt

Fixes #2376
Make `SurveyProperties` contain the data needed to compute a read only state instead. I mistakenly assumed 
PTAL @gino-m @shobhitagarwal1612

Refactor `readOnly` -> `noLois` in `SurveyProperties`

---

ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt

Fixes #2408
Instead of crashing the app, reset the current task id to empty. 

Fix crash in data collection fragment

---

ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewPagerAdapter.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt
ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/BaseTaskFragmentTest.kt
ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskFragmentTest.kt

Fixes #2410
Currently, we set a position integer to each task fragment during creation and later use it to generate/fetch view model for the task fragment. This has been working fine but is still error prone. This is because it assumes that the original order of tasks can never change which may or may not be true. 
To make it more secure, replacing `position` with `taskId` since it is guaranteed that each task id is unique.
Verified for regressions by checking all scenarios manually
* First task
* Last task
* App pause/resume
* Draft state
@sufyanAbbasi  @gino-m  PTAL?

Use `taskId` instead of `position` for initializing task view models

---

ground/src/main/java/com/google/android/ground/Config.kt
ground/src/main/java/com/google/android/ground/FirebaseCrashLogger.kt
ground/src/main/java/com/google/android/ground/FirebaseCrashLogging.kt
ground/src/main/java/com/google/android/ground/GroundApplication.kt
ground/src/main/java/com/google/android/ground/repository/SurveyRepository.kt
ground/src/main/java/com/google/android/ground/util/Debug.kt

Fixes #2421
Currently, we were only logging survey id when the error is logged. But if the app crashes, then the app closes directly and the custom key isn't loaded. 
To fix that, update the selected survey id and screen name to firebase crashlytics proactively.
@gino-m  PTAL?

Add custom keys to firebase crashlytics

---

ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt
ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskFragmentTest.kt

Fixes #2417
This PR fixes the position of "skip" button for the first task. Currently this button appears at the beginning of the row. This is because "previous" button is hidden for the first task. 
To resolve it, make the "previous" button as disabled instead of hiding it.
@gino-m  PTAL?

Fix alignment of button for the first task

---

ground/src/main/java/com/google/android/ground/Config.kt
ground/src/main/java/com/google/android/ground/LocalDatabaseModule.kt

Fixes #932
We can't reset DB version to 1 since it is already launched to play store. With this change, the app will always require migration instead of clearing the db when upgrading the db version
@gino-m  PTAL?

Disable fallbackToDestructiveMigration()

---

ground/src/main/java/com/google/android/ground/repository/UserRepository.kt
ground/src/main/java/com/google/android/ground/system/auth/AnonymousAuthenticationManager.kt
ground/src/main/java/com/google/android/ground/system/auth/BaseAuthenticationManager.kt
ground/src/main/java/com/google/android/ground/system/auth/GoogleAuthenticationManager.kt
ground/src/main/java/com/google/android/ground/ui/signin/SignInViewModel.kt
ground/src/test/java/com/google/android/ground/domain/usecase/MakeSurveyAvailableOfflineUseCaseTest.kt
ground/src/test/java/com/google/android/ground/ui/surveyselector/SurveySelectorFragmentTest.kt
sharedTest/src/main/kotlin/com/sharedtest/system/auth/FakeAuthenticationManager.kt

Fixes #2335
When opening the app by following the repro steps as per #2335, the startup fragment is not invoked. Due to this, the user isn't logged in and the app appears to be un-initialized.
This PR fixes that by ensuring that sdk is always initialized irrespective of how the app is launched.
Verified by following the below steps:
2. Ensure app has location permissions, click on a survey.
3. While in the survey map view, before clicking on "Collect", go into app settings and remove location permissions.
4. Then re-open the app using the "Open" button on the settings.
5. See that app is properly loaded including user details and survey list.
@gino-m @sufyanAbbasi @scolsen PTAL?

[Bug] Ensure firebase auth is always initialized before accessing it

---

ground/src/main/java/com/google/android/ground/repository/OfflineAreaRepository.kt
ground/src/main/java/com/google/android/ground/ui/offlineareas/OfflineAreasViewModel.kt
ground/src/main/java/com/google/android/ground/ui/util/FileUtil.kt

Also remove obsolete usage of suspend
Removes unused functions in FileUtil class. Also removes obsolete usages of `suspend`

Cleanup dead code in FileUtil

---

ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/MultipleChoiceConverter.kt
ground/src/test/java/com/google/android/ground/persistence/remote/firebase/schema/MultipleChoiceConverterTest.kt

Fixes #2460 
* Default to false if the field is missing
* Adds unit test coverage
@gino-m @rfontanarosa  PTAL?

Handle nullability for hasOtherOption in Multiple choice type tasks

---

ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/TaskPosition.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/UiState.kt

This is similar to https://github.com/google/ground-android/pull/2476. This allows hiding internals of the view model to fragment and exposing it via UiState. This makes the class more robust and manageable.
@gino-m  PTAL?

Use UiState in DataCollectionFragment

---

ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorFragment.kt
ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorViewModel.kt
ground/src/main/java/com/google/android/ground/ui/surveyselector/UiState.kt
ground/src/main/java/com/google/android/ground/util/ViewExt.kt
ground/src/main/res/layout/survey_selector_frag.xml

Fixes #2081
This PR aims at simplifying the way we are updating the UI in survey selector fragment. Currently, we have 3 separate flows for toggling progress dialog, survey list and errors. In this PR, we have merged all three flows into a single flow `UiState`  
@gino-m  PTAL?

Merge multiple ui state flows into a single flow in SurveySelectorFragment

---

ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionMutationConverter.kt
ground/src/test/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionMutationConverterTest.kt

Fixes #2473
Moves the CaptureLocationTaskData case before GeometryTaskData to correctly convert the object to firestore map. Also adds missing test coverage for capture location task, time task and data task.

Allow storing altitude and accuracy in Firestore for CaptureLocationTaskData

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
ground/build.gradle

Fixes #2486 
Update gradle and kotlin versions to be more compatible, but not set, Java 21.
See compatibility tables: 
https://docs.gradle.org/current/userguide/compatibility.html
https://developer.android.com/jetpack/androidx/releases/compose-kotlin
@gino-m PTAL!

Update gradle/kotlin versions to be more compatible with Java 21.

---

ground/src/main/java/com/google/android/ground/repository/SubmissionRepository.kt
ground/src/test/java/com/google/android/ground/ui/datacollection/DataCollectionFragmentTest.kt

Removes unnecessary creation of `submission` object when attempting to save submission.
@sufyanAbbasi  @gino-m  PTAL?

Cleanup SubmissionRepository

---

ground/src/main/java/com/google/android/ground/domain/usecases/submission/SubmitDataUseCase.kt
ground/src/main/java/com/google/android/ground/model/locationofinterest/LocationOfInterest.kt
ground/src/main/java/com/google/android/ground/repository/LocationOfInterestRepository.kt

Moves logic for creation of LOI to LoiRepository. Also, removes the creation of intermediate state `LocationOfInterest` and directly generates the mutation.
This is similar to https://github.com/google/ground-android/pull/2495 where the goal is to simplify the save LOI flow by reducing the number of steps involved.

Moves creation of LOI to LoiRepository

---

ground/src/main/java/com/google/android/ground/model/locationofinterest/LocationOfInterest.kt
ground/src/main/java/com/google/android/ground/model/mutation/LocationOfInterestMutation.kt
ground/src/main/java/com/google/android/ground/persistence/local/room/converter/ConverterExt.kt
ground/src/main/java/com/google/android/ground/persistence/local/room/entity/LocationOfInterestEntity.kt
ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/LoiConverter.kt
ground/src/main/java/com/google/android/ground/repository/LocationOfInterestRepository.kt
ground/src/test/java/com/google/android/ground/persistence/remote/firebase/schema/LoiConverterTest.kt

Fixes #2573 
Remove `ownerEmail` from LOI model and local repository, since it's not used or supplied by the new proto serialization.
PTAL @shobhitagarwal1612!

Remove ownerEmail from LOIs.

---

build.gradle
cloudbuild.yaml
config/jacoco/jacoco.gradle

Reenable codecov reports and PR comments

---

ground/src/main/java/com/google/android/ground/ui/home/AboutFragment.kt
ground/src/test/java/com/google/android/ground/BaseHiltTest.kt
ground/src/test/java/com/google/android/ground/ui/home/AboutFragmentTest.kt

Fixes #2586 
Part 1 of the AboutFragment Test coverage
@shobhitagarwal1612 @sufyanAbbasi  PTAL?

Added AboutFragment test cases

---

ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/location/CaptureLocationTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/point/DropPinTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/DrawAreaTaskFragment.kt

Fixes #2493
-  I think this occurs because `generateViewId()` is not thread safe when `GoogleMapsFragment` views are also being produced at the same time.
@gino-m, @shobhitagarwal1612  PTAL!

Prevent view ID conflict/crash by multiplying each generated view ID by a prime number

---

e2eTest/src/main/java/com/google/android/ground/e2etest/SurveyRunnerTest.kt
e2eTest/src/main/java/com/google/android/ground/e2etest/TestConfig.kt

Towards https://github.com/google/ground-platform/issues/1927
Allows for LOI task to be at an arbitrary index rather than hardcoded to the first entry.
- Ran `npm run test:e2e:create` in ground-platform.
- Ran `firebase emulators:exec "./gradlew :e2eTest:connectedLocalDebugAndroidTest --stacktrace --info" --project local --ui  --config ../ground-platform/firebase.local.json --import ../ground-platform/data/test-create --export-on-exit ../ground-platform/data/test-submit`
@gino-m PTAL!

[End-to-End Tests] Allow configuration for LOI task to be at any index in task list

---

ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/DrawAreaTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/DrawAreaTaskViewModel.kt
ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/polygon/DrawAreaTaskViewModelTest.kt

Towards #2373 
Ensures that draw area tasks can be loaded from saved state. Will enter "complete" mode by default and the user can  undo if they want to go back, similar to the drop pin save state logic.
@shobhitagarwal1612 PTAL!

Load drawn area from saved state

---

codecov.yml

@sufyanAbbasi PTAL to upblock https://github.com/google/ground-android/pull/2598

Relax codecov check constraints

---

ground/src/main/java/com/google/android/ground/Config.kt
ground/src/main/java/com/google/android/ground/domain/usecases/submission/SubmitDataUseCase.kt
ground/src/main/java/com/google/android/ground/model/locationofinterest/LocationOfInterest.kt
ground/src/main/java/com/google/android/ground/model/mutation/LocationOfInterestMutation.kt
ground/src/main/java/com/google/android/ground/model/mutation/Mutation.kt
ground/src/main/java/com/google/android/ground/model/mutation/SubmissionMutation.kt
ground/src/main/java/com/google/android/ground/persistence/local/room/converter/ConverterExt.kt
ground/src/main/java/com/google/android/ground/persistence/local/room/entity/LocationOfInterestMutationEntity.kt
ground/src/main/java/com/google/android/ground/persistence/local/room/entity/SubmissionMutationEntity.kt
ground/src/main/java/com/google/android/ground/repository/LocationOfInterestRepository.kt
ground/src/main/java/com/google/android/ground/repository/MutationRepository.kt
ground/src/main/java/com/google/android/ground/repository/SubmissionRepository.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt
ground/src/main/java/com/google/android/ground/ui/syncstatus/SyncListItem.kt
ground/src/test/java/com/google/android/ground/persistence/local/LocalDataStoreTests.kt
ground/src/test/java/com/google/android/ground/persistence/remote/firebase/protobuf/LoiMutationConverterTest.kt
ground/src/test/java/com/google/android/ground/persistence/remote/firebase/protobuf/ModelToProtoExtKtTest.kt
ground/src/test/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionMutationConverterTest.kt
ground/src/test/java/com/google/android/ground/persistence/sync/LocalMutationSyncWorkerTest.kt
ground/src/test/java/com/google/android/ground/persistence/sync/MediaUploadWorkerTest.kt
ground/src/test/java/com/google/android/ground/ui/datacollection/DataCollectionFragmentTest.kt
sharedTest/src/main/kotlin/com/sharedtest/FakeData.kt

Fixes #2389.
When a user collects data, they may need to add a new LOI depending on the job configuration. We treat the addition of the LOI and the eventual submission of data against it as two distinct data mutations. This resulted in duplicate mutation details in sync status for what, to the user, is perceived as a single instance of data collection/submission, which can prove confusing.
To resolve this, we now associate mutations together using a "collection ID" which indicates whether or not two distinct mutations originated from the same data collection flow. When we read mutations out of the local store, we then combine them using this identifier, taking only the more recent mutation as indicative of the overall status for the submission.

Sync: Fix double mutation detail rendering in sync status.

---

codecov.yml
ground/build.gradle
ground/src/main/java/com/google/android/ground/model/submission/PhotoTaskData.kt
ground/src/main/java/com/google/android/ground/persistence/local/room/converter/ValueJsonConverter.kt
ground/src/main/java/com/google/android/ground/persistence/remote/firebase/protobuf/ModelToProtoExt.kt
ground/src/main/java/com/google/android/ground/persistence/sync/LocalMutationSyncWorker.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/photo/PhotoTaskViewModel.kt
ground/src/test/java/com/google/android/ground/persistence/remote/firebase/protobuf/ModelToProtoExtKtTest.kt

Fix local (de)serialization of photo tasks

---

ground/src/main/java/com/google/android/ground/ui/common/AbstractMapFragmentWithControls.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/location/CaptureLocationTaskMapFragment.kt
ground/src/main/res/layout/map_task_frag.xml
ground/src/main/res/values/strings.xml
ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/BaseTaskFragmentTest.kt

Fixes #2442
Inline the location fab and other elements in task fragment instead of embedded layout to allow constraints to be set correctly.
| Small screen | Large Screen |
| ----- | ----- |
| ![update-info-card](https://github.com/user-attachments/assets/831de988-1899-451b-9042-96d7468061e3) | ![update-info-card-large](https://github.com/user-attachments/assets/ff073f8f-6456-453a-9705-f651a3dfa87c) |
@gino-m  PTAL?

Prevent overlapping of info card and location FAB

---

ground/src/main/java/com/google/android/ground/model/imagery/TileSource.kt
ground/src/main/java/com/google/android/ground/repository/OfflineAreaRepository.kt
ground/src/main/java/com/google/android/ground/ui/common/AbstractMapContainerFragment.kt
ground/src/main/java/com/google/android/ground/ui/common/BaseMapViewModel.kt
ground/src/main/java/com/google/android/ground/ui/map/gms/GoogleMapsFragment.kt
ground/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorFragment.kt
ground/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorViewModel.kt

Fixes https://github.com/google/ground-android/issues/1790
Things done:
* Convert `TileSource` enum to sealed data class
* Simplify `OfflineAreaRepository`
* Replace `List<TileSource>` with `TileSource` when adding overlay for simplicity. If we need to support multiple tile sources, then we can change it back later.
This is a pure refactor and doesn't change app behavior.
Verified for regressions by testing that remote mog overlay is loaded in offline area screen and locally downloaded tiles are loaded on home screen.
@gino-m  PTAL?

[Offline area] Refactor code related to loading local/remote tile overlays

---

ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskViewModel.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/date/DateTaskViewModel.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/location/CaptureLocationTaskViewModel.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskViewModel.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/number/NumberTaskViewModel.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/photo/PhotoTaskViewModel.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/point/DropPinTaskViewModel.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/DrawAreaTaskViewModel.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/text/TextTaskViewModel.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/time/TimeTaskViewModel.kt
ground/src/main/res/layout/date_task_frag.xml
ground/src/main/res/layout/time_task_frag.xml

Fixes #2520
@anandwana001 @gino-m   PTAL?

Remove dependency on context from view models

---

ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorViewModel.kt

Fixes #2729
Prevent secondary loading of survey while the current survey is still being loaded. Unfortunately, there still exists UX problems of the user not getting any feedback about the survey still in the loading state even after the loading bar has gone away.
@gino-m PTAL!

Ignore survey clicks while the survey is being activated.

---

ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/components/TaskButton.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/location/CaptureLocationTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/point/DropPinTaskFragment.kt
ground/src/test/java/com/google/android/ground/ui/datacollection/DataCollectionFragmentTest.kt
ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/BaseTaskFragmentTest.kt
ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/date/DateTaskFragmentTest.kt
ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskFragmentTest.kt

Fixes #2394 
Dynamically updates the "Next/Done" button when 
Shows Done button disabled:
Option 1 triggers the next task, Next button is enabled
Option 2 checked, Next button still enabled
Option 1 unchecked, Next button becomes Done button, still enabled
@anandwana001, @shobhitagarwal1612  PTAL!

Make sure "Done" button is rendered when the last task is hidden due to unsatisfied condition.

---

ground/src/main/java/com/google/android/ground/FirebaseCrashLogger.kt
ground/src/main/java/com/google/android/ground/persistence/sync/LocalMutationSyncWorker.kt
ground/src/main/java/com/google/android/ground/persistence/sync/MediaUploadWorker.kt
ground/src/main/java/com/google/android/ground/persistence/sync/SurveySyncWorker.kt

This will help us debug issues with data sync (#2751).

Report sync failures to Crashlytics

---

ground/src/main/AndroidManifest.xml
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/date/DateTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/time/TimeTaskFragment.kt
ground/src/main/res/layout/date_task_frag.xml
ground/src/main/res/layout/time_task_frag.xml
ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/date/DateTaskFragmentTest.kt
ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/time/TimeTaskFragmentTest.kt

Adds hint for date/time task fields

---

ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionFragment.kt

Fixes #2734 
1. The set position happens under handler earlier which is now changed to coroutines 
2. We are checking not the values and then setting, not before the action button render on screen

Added doOnLayout for ProgressBar Position

---

ground/src/main/java/com/google/android/ground/persistence/remote/firebase/FirebaseFirestoreProvider.kt

Fixes #2689 
Firebase Settings were added on top of the same settings and due to which the issue is coming, now we are only setting the settings if new, else use the same instance.

Add a check to prevent re-initializing firebase firestore

---

ground/src/main/java/com/google/android/ground/PermissionDeniedDialog.kt
ground/src/test/java/com/google/android/ground/MainActivityTest.kt
ground/src/test/java/com/google/android/ground/PermissionDeniedDialogTest.kt

PermissionDeniedDialogTest and SignInError Test Coverage

---

ground/src/main/java/com/google/android/ground/repository/LocationOfInterestRepository.kt
ground/src/main/java/com/google/android/ground/repository/SubmissionRepository.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt
ground/src/main/java/com/google/android/ground/ui/syncstatus/SyncStatusViewModel.kt

Fixes #2773 
Earlier app crash when any offline LOI is not available.
Added Null check of such LOI access logic
@shobhitagarwal1612 @sufyanAbbasi  PTAL?

Added null check for Offline LOI

---

ground/src/main/java/com/google/android/ground/MainActivity.kt

Added NavigateUp empty Check

---

ground/src/main/java/com/google/android/ground/persistence/remote/RemotePersistenceModule.kt
ground/src/main/java/com/google/android/ground/persistence/remote/firebase/FirebaseFirestoreProvider.kt
ground/src/main/java/com/google/android/ground/persistence/remote/firebase/FirestoreUuidGenerator.kt
ground/src/main/java/com/google/android/ground/persistence/uuid/OfflineUuidGenerator.kt
ground/src/main/java/com/google/android/ground/repository/UserMediaRepository.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/photo/PhotoTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/photo/PhotoTaskViewModel.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/point/DropPinTaskViewModel.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/DrawAreaTaskViewModel.kt
ground/src/test/java/com/google/android/ground/persistence/sync/MediaUploadWorkerTest.kt
ground/src/test/java/com/google/android/ground/ui/datacollection/DataCollectionFragmentTest.kt
sharedTest/src/main/kotlin/com/sharedtest/persistence/uuid/FakeUuidGenerator.kt

Uses same singleton provider to get Firebase instance when generating UUIDs as used elsewhere. This requires those calls to be made asynchronously to avoid blocking the UI.
Fixes #2377

Fix "FirebaseFirestore has already been started" sync failures

---

ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomLocationOfInterestStore.kt
ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomSubmissionStore.kt
ground/src/main/java/com/google/android/ground/persistence/local/stores/LocalLocationOfInterestStore.kt
ground/src/main/java/com/google/android/ground/persistence/local/stores/LocalSubmissionStore.kt
ground/src/main/java/com/google/android/ground/persistence/sync/LocalMutationSyncWorker.kt
ground/src/main/java/com/google/android/ground/persistence/sync/MediaUploadWorker.kt
ground/src/main/java/com/google/android/ground/repository/MutationRepository.kt
ground/src/main/java/com/google/android/ground/ui/home/HomeScreenViewModel.kt

Forces mutation workers to scan all incomplete mutations when home screen is first opened. The should happen when the home screen is opened after app update.
Towards #2726
Fixes #2751

Unstick stuck uploads

---

ground/src/main/java/com/google/android/ground/ui/common/AbstractMapContainerFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/DrawAreaTaskMapFragment.kt

Move camera position to geometry when restoring draw area tasks

---

config/detekt/detekt.yml
ground/src/main/java/com/google/android/ground/persistence/remote/firebase/FirebaseStorageManager.kt
ground/src/main/java/com/google/android/ground/persistence/remote/firebase/FirestoreDataStore.kt
ground/src/main/java/com/google/android/ground/persistence/remote/firebase/base/FluentCollectionReference.kt
ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/JobCollectionReference.kt
ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/LoiCollectionReference.kt
ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/SurveyDocumentReference.kt
ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/TermsOfServiceDocumentReference.kt

Towards #2854
As per documentation, calling `await()` when the coroutine is cancelled throws `JobCancellationException`. Since it is a normal part of the coroutine lifecycle, these can be safely ignored and the error can be handled accordingly. 
The classes are identified based on logs/stacktraces from the crashlytics dashboard. There could be more of them, so we should keep the issue open until no more of these errors are observed.
@gino-m  PTAL?

Adds exception handling for coroutine cancellation when using await()

---

ground/src/main/java/com/google/android/ground/model/mutation/SubmissionMutation.kt
ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomLocationOfInterestStore.kt
ground/src/main/java/com/google/android/ground/persistence/local/stores/LocalLocationOfInterestStore.kt
ground/src/main/java/com/google/android/ground/persistence/sync/MediaUploadWorker.kt
ground/src/main/java/com/google/android/ground/repository/MutationRepository.kt
ground/src/main/java/com/google/android/ground/ui/home/HomeScreenViewModel.kt

Minor ktdoc and code cleanup ahead of #2840

---

ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskViewModel.kt
ground/src/main/res/layout/multiple_choice_checkbox_item.xml
ground/src/main/res/layout/multiple_choice_radiobutton_item.xml
ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskFragmentTest.kt

Fixes #2833
Disables the previous/next buttons if the task is required and user has selected other option but hasn't filled the text.
Verified by running the app locally and via unit tests
@gino-m  PTAL?

[Multiple choice questions] Make "other" text required

---

ground/build.gradle
ground/schemas/com.google.android.ground.persistence.local.room.LocalDatabase/120.json
ground/src/main/java/com/google/android/ground/LocalDatabaseModule.kt
ground/src/main/java/com/google/android/ground/persistence/local/room/LocalDatabase.kt

Allow exporting table schema to code repository. 
This will enable compile time failures if room cannot auto-migrate schema and a manual migration is missing.
https://developer.android.com/training/data-storage/room/migrating-db-versions
Needed for https://github.com/google/ground-android/pull/2871
@gino-m  PTAL?

Enable exporting table schema to code repository

---

ground/build.gradle
ground/src/main/java/com/google/android/ground/model/submission/MultipleChoiceTaskData.kt
ground/src/main/java/com/google/android/ground/persistence/remote/firebase/protobuf/ModelToProtoExt.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskViewModel.kt
ground/src/test/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionMutationConverterTest.kt

Fixes #2846
Added proto in this PR
https://github.com/google/ground-platform/pull/2107

Mark other_selected if Other selected

---

ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/location/CaptureLocationTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/location/CaptureLocationTaskMapFragment.kt

[Capture location task] Prompted to Correct enable location task

---

ground/src/main/java/com/google/android/ground/system/GoogleApiManager.kt
ground/src/main/java/com/google/android/ground/ui/startup/StartupFragment.kt
ground/src/main/java/com/google/android/ground/ui/startup/StartupViewModel.kt
ground/src/main/res/values-fr/strings.xml

Some GMS strangeness:
* When Play services are present, but disabled,  after "ENABLE" is clicked in the resolution dialog, `onActivityResult()` is called with a failure result even though the flow is not complete.
* When Play services are not supported on a device, an error dialog is shown, but `onActivityResult()` is not called when dismissed.
To work around this, if the error is identified as "recoverable, this PR waits indefinitely for Play services to be installed.
Towards #2783 - we may want to follow-up with a PR to add a distinct message "Waiting for Play services..." while waiting.
Filed #2919 as follow-up for edge case.

Handle Play services failures more gracefully

---

.github/auto_assign.yml

Disable auto-assigner and reduce reviewer to 1
@gino-m  PTAL?

Update auto-assign config to only add 1 reviewer

---

ground/src/main/java/com/google/android/ground/MainActivity.kt

Fixes #2944
`super.onBackPressed()` is now deprecated, and documentation suggested using `OnBackPressedCallback`
Back Press should work correctly.

Migrate BackPress to OnBackPressedCallback

---

ground/src/main/java/com/google/android/ground/repository/MutationRepository.kt
ground/src/main/java/com/google/android/ground/ui/syncstatus/SyncListItem.kt
ground/src/main/java/com/google/android/ground/ui/syncstatus/SyncStatusDetail.kt
ground/src/main/java/com/google/android/ground/ui/syncstatus/SyncStatusFragment.kt
ground/src/main/java/com/google/android/ground/ui/syncstatus/SyncStatusViewModel.kt

This commit uses the newly introduced getUploadQueueFlow() in the MutationRepository to fetch mutations for the sync status UI. In additiion, I have renamed some classes and added some documentation for clarity. In addition, we now handle SubmissionMutations separately from LOI Mutations, allowing us to better inform users. We also no longer check for the authenticated user in the sync view model, since this is done in the mutation repository before the uplaod queue is returned.
Fixes #2894
@gino-m

SyncStatus: Use new mutations repository upload queue flow; renaming.

---

.github/workflows/todo-to-issue.yml
ground/src/main/java/com/google/android/ground/GroundApplication.kt

Instead of merging the commit to master branch, it commits to the PR's source branch when the PR is approved.
@gino-m  PTAL?

Update todo-to-list github action to commit to PR instead of master branch

---

ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt

Fixes #2956
This is a no-op change and improves the code readability slightly by exposing methods with concise task controller.
Note: While working on this, I found more improvements for abstracting out the task sequence logic into a separate handler. Will file a separate bug and PR as a follow up to this.
Filed: https://github.com/google/ground-android/issues/2958
@anandwana001  @gino-m  PTAL?

[Code health] Don't expose task stepper with unbounded page count in DataCollectionViewModel

---

ground/src/main/java/com/google/android/ground/ui/util/BitmapUtil.kt

Fixes #2963 
Parent Ticket #2338
This PR removes the use of `getBitmap` function of `android.provider.MediaStore` as it is deprecated and changed with `ImageDecoder` and `BitmapFactory` as per the API level requirements. 

Remove getBitmap deprecated function

---

ground/src/main/java/com/google/android/ground/ui/IconFactory.kt

Fixes #2960
Parent Ticket #2338
As setColorFilter is deprecated by java, this PR is raised to use the new `setColorFilter`. 
Also, as our app has a minimum level of 24,  this new `setColorFilter` API has a minimum of API 29, so added a API level check.

Update setColorFilter with the non-deprecated function

---

ground/src/main/java/com/google/android/ground/system/LocationManager.kt

Fixes #2969
Parent Ticket #2338 
`LocationRequest` is deprecated and update with the latest builder design pattern.

Deprecated LocationRequest fixed with new Builder Design Pattern

---

ground/src/main/java/com/google/android/ground/ui/map/gms/mog/ImageEditor.kt

Fixes #2965 
Parent Ticket #2338 
`Bitmap.CompressFormat.WEBP` is deprecated and this PR added API level check and update with `WEBP_LOSSY`.

Added WEBP_LOSSY and update Deprecated Bitmap.CompressFormat

---

ground/src/main/java/com/google/android/ground/domain/usecases/submission/SubmitDataUseCase.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/components/LoiNameDialog.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/point/DropPinTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/point/DropPinTaskViewModel.kt
ground/src/test/java/com/google/android/ground/ui/datacollection/DataCollectionFragmentTest.kt
ground/src/test/java/com/google/android/ground/ui/datacollection/TaskFragmentRunner.kt

Fixes #2502
This is a no-op change and adds test coverage for data submission flow when LOI isn't provided and needs to be created along with the  whole flow (incl. LoiDialogName handling).
Also adds a couple of TODOs for detected code smells.
Increases overall coverage by 1.28%. See codecov reports https://github.com/google/ground-android/pull/2980#issuecomment-2571700630.
@anandwana001 @gino-m  PTAL?

[Code health] Add test coverage for adhoc data submission flow

---

ground/src/main/java/com/google/android/ground/ui/datacollection/TaskSequenceHandler.kt
ground/src/test/java/com/google/android/ground/ui/datacollection/TaskSequenceHandlerTest.kt

Fixes #2987
This is a no-op change as this class isn't being used anywhere at the moment.
Remove isLastPosition from TaskSequenceHandler which also accepts value as it is confusing and should be moved to downstream.  The class is being used in: https://github.com/google/ground-android/pull/2986
@anandwana001 @scolsen  PTAL?

Improve design of TaskSequenceHandler by removing a confusing method

---

ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/location/CaptureLocationTaskFragment.kt
ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/point/DropPinTaskFragment.kt

This PR is a pure refactor which is split from https://github.com/google/ground-android/pull/2986 so that main logic change can be separated from refactors.
Things done:
* Adds support for hiding the next button in the base helper method
* Reuse the same function in drop pin and capture location tasks.
@anandwana001 PTAL?

Reuse addNextButton() for Capture location and drop pin tasks

---

ground/src/main/java/com/google/android/ground/ui/datacollection/components/TextTaskInput.kt

Fixes #2988 
The width of the text input is now again taking the max width of the screen.

Fix the TextInput Width

---

ground/src/main/java/com/google/android/ground/ui/datacollection/TaskSequenceHandler.kt
ground/src/test/java/com/google/android/ground/ui/datacollection/TaskSequenceHandlerTest.kt

Towards #2993
Adds caching mechanism for generated task sequence.
See https://github.com/google/ground-android/issues/2993#issue-2776885263 for detailed description.
@scolsen @anandwana001  PTAL?

Add logic to cache generated task sequence

---

ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt

This PR is a pure refactor which is split from https://github.com/google/ground-android/pull/2986 so that main logic change can be separated from refactors.
Things done:
* Instead of using `currentTaskId.value` as default task id in all method, pass the id from the callers 
* Prevent re-creating task sequence for each value when storing values to local db.
* Cleanup unused code.

Refactor DataCollectionViewModel

---

ground/src/main/java/com/google/android/ground/ui/datacollection/TaskDataHandler.kt
ground/src/test/java/com/google/android/ground/ui/datacollection/TaskDataHandlerTest.kt

Towards #2993 
Introduces a wrapper class for handling task data values. Provides a way to subscribe for changes to the task value. 
This is a no-op change. This will be integrated along with TaskSequenceHandler in DataCollectionViewModel in future CLs.
See https://github.com/google/ground-android/issues/2993#issue-2776885263 for detailed description.
@scolsen @anandwana001 PTAL?

Introduce TaskDataHandler

---

app/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt
app/src/main/java/com/google/android/ground/ui/datacollection/TaskDataHandler.kt
app/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt
app/src/test/java/com/google/android/ground/ui/datacollection/TaskDataHandlerTest.kt

Towards #2993
In #2995, we introduced `TaskDataHandler` for managing data state. This PR aims at using it in `DataCollectionViewModel`.
This shouldn't change the behavior and is no-op.
Split from https://github.com/google/ground-android/pull/2986
@anandwana001 @scolsen  PTAL?

Use TaskDataHandler in DataCollectionViewModel

---

app/src/main/java/com/google/android/ground/ui/datacollection/TaskSequenceHandler.kt
app/src/test/java/com/google/android/ground/ui/datacollection/TaskSequenceHandlerTest.kt

Towards https://github.com/google/ground-android/issues/2993
This PR aims at using `TaskDataHandler` in `TaskSequenceHandler` for generating task sequences instead of exposing a callback. In https://github.com/google/ground-android/pull/3005, we've already started using `TaskDataHandler` for managing task data state.
This shouldn't change the behavior and is no-op.
Split from https://github.com/google/ground-android/pull/2986
@anandwana001 @scolsen PTAL?

Integrate TaskDataHandler in TaskSequenceHandler

---

app/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt

Fixes an issue in data collection flow where the draft was getting saved after task submission causing the data collection fragment to be reopened just after collecting data.
Changes verified by running the app locally with and without this fix.

[Bug] Prevent saving to draft after task is submitted

---

app/src/main/java/com/google/android/ground/domain/usecases/survey/ListAvailableSurveysUseCase.kt
app/src/main/java/com/google/android/ground/repository/SurveyRepository.kt
app/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorViewModel.kt
app/src/test/java/com/google/android/ground/domain/usecase/ListAvailableSurveysUseCaseTest.kt
app/src/test/java/com/google/android/ground/repository/SurveyRepositoryTest.kt
app/src/test/java/com/google/android/ground/ui/surveyselector/SurveySelectorFragmentTest.kt

Towards #3014 
This PR aims at pulling out all logic related to compiling a list of surveys to be displayed to the user from SurveyRepositry to a new use case `ListAvailableSurveysUseCase`.
Also adds test coverage for the new use case.

Create a new use case for listing available surveys 

---

app/src/main/java/com/google/android/ground/MainViewModel.kt
app/src/main/java/com/google/android/ground/domain/usecases/survey/ActivateSurveyUseCase.kt
app/src/main/java/com/google/android/ground/domain/usecases/survey/MakeSurveyAvailableOfflineUseCase.kt
app/src/main/java/com/google/android/ground/domain/usecases/survey/ReactivateLastSurveyUseCase.kt
app/src/main/java/com/google/android/ground/domain/usecases/survey/SyncSurveyUseCase.kt
app/src/main/java/com/google/android/ground/repository/SurveyRepository.kt
app/src/test/java/com/google/android/ground/domain/usecase/MakeSurveyAvailableOfflineUseCaseTest.kt
app/src/test/java/com/google/android/ground/domain/usecase/ReactivateLastSurveyUseCaseTest.kt
app/src/test/java/com/google/android/ground/domain/usecase/SyncSurveyUseCaseTest.kt
app/src/test/java/com/google/android/ground/repository/SurveyRepositoryTest.kt
app/src/test/java/com/google/android/ground/repository/UserRepositoryTest.kt
app/src/test/java/com/google/android/ground/ui/home/HomeScreenFragmentTest.kt
app/src/test/java/com/google/android/ground/ui/surveyselector/SurveySelectorFragmentTest.kt
app/src/test/java/com/google/android/ground/ui/syncstatus/SyncStatusFragmentTest.kt

Towards https://github.com/google/ground-android/issues/3014
* Moves business logic for fetching and saving survey to `SyncSurveyUseCase`
* Moves business logic for subscribing to remote updates to `MakeSurveyAvailableOfflineUseCase`

Refactor out single use logic from SurveyRepository to existing use cases

---

app/src/main/java/com/google/android/ground/MainViewModel.kt
app/src/main/java/com/google/android/ground/domain/usecases/survey/ActivateSurveyUseCase.kt
app/src/main/java/com/google/android/ground/domain/usecases/survey/ReactivateLastSurveyUseCase.kt
app/src/main/java/com/google/android/ground/repository/SurveyRepository.kt
app/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorViewModel.kt
app/src/test/java/com/google/android/ground/repository/UserRepositoryTest.kt
app/src/test/java/com/google/android/ground/ui/home/HomeScreenFragmentTest.kt
app/src/test/java/com/google/android/ground/ui/surveyselector/SurveySelectorFragmentTest.kt

Fixes #3020
This PR aims to make the behavior of activate survey deterministic by making the call wait until the survey has been activated i.e. the survey gets fetched from local db and is emitted by the flow.
Without this, today the UI assumes that the survey has been activated and the screens are ready to consume it. This may lead to unwanted behavior if the next screen expects the value to be available immediately.
The function waits for 3s before throwing an error. Instead of crashing the app, we display an error toast that "something went wrong" and the user can try again.
@gino-m @sufyanAbbasi @anandwana001  PTAL?

Make activateSurvey call blocking

---

app/src/main/java/com/google/android/ground/MainViewModel.kt
app/src/main/java/com/google/android/ground/domain/usecases/survey/ReactivateLastSurveyUseCase.kt
app/src/main/java/com/google/android/ground/domain/usecases/survey/RemoveOfflineSurveyUseCase.kt
app/src/main/java/com/google/android/ground/repository/SurveyRepository.kt
app/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorViewModel.kt
app/src/test/java/com/google/android/ground/domain/usecases/survey/RemoveOfflineSurveyUseCaseTest.kt
app/src/test/java/com/google/android/ground/ui/surveyselector/SurveySelectorFragmentTest.kt

Fixes #3014
Split SurveyRepository and create a new use case for removing offline survey

[Code health] Migrate remaining business logic from SurveyRepository to a domain use case

---

app/src/main/java/com/google/android/ground/ui/compose/ConfirmationDialog.kt
app/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionFragment.kt
app/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorFragment.kt
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-pt/strings.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/google/android/ground/ui/datacollection/DataCollectionFragmentTest.kt
app/src/test/java/com/google/android/ground/ui/datacollection/TaskFragmentRunner.kt

Fixes #2635 
Adds a new warning dialog before discarding the in-progress data collection screen.
https://github.com/user-attachments/assets/a33557e6-c1cf-448e-a39d-d29e4768ba29

Show a warning dialog when attempting to close data collection screen

---

app/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt
app/src/main/java/com/google/android/ground/ui/datacollection/TaskDataHandler.kt
app/src/main/java/com/google/android/ground/ui/datacollection/TaskSequenceHandler.kt
app/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt
app/src/test/java/com/google/android/ground/ui/datacollection/TaskDataHandlerTest.kt
app/src/test/java/com/google/android/ground/ui/datacollection/TaskSequenceHandlerTest.kt

Fixes #3009
Fixes #3025 
As discussed in https://github.com/google/ground-android/pull/3008#issuecomment-2618061017, we can replace `sequence` with `list` in `TaskSequenceHandler` to improve lookup performance.
Verified for regressions by running the app locally.
@anandwana001 @sufyanAbbasi  PTAL?

Use list instead of sequence in TaskSequenceHandler

---

app/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt
app/src/main/java/com/google/android/ground/ui/home/mapcontainer/jobs/JobMapComposables.kt
app/src/main/java/com/google/android/ground/util/ComposeExt.kt

Performs a minor refactor on https://github.com/google/ground-android/pull/2892 to further remove non-composable logic out of the composable class.
This is a pure refactor and doesn't change the behavior. Verified by running the app locally. 
@sufyanAbbasi  PTAL?

Minor cleanup for new data entry points

---

app/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt
app/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt
app/src/main/java/com/google/android/ground/ui/home/mapcontainer/jobs/DataCollectionEntryPointData.kt
app/src/main/java/com/google/android/ground/ui/home/mapcontainer/jobs/JobMapComposables.kt
app/src/test/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModelTest.kt

Follow up to https://github.com/google/ground-android/pull/3036
Further simplifies the `JobMapComposables` by replacing async function call to fetch submission count by adding it to card data. We no longer need to evaluate it on-the-fly as there is only 1 card rendered at a time.
@anandwana001 @sufyanAbbasi  PTAL?

Add submission count to card data

---

app/src/main/java/com/google/android/ground/domain/usecases/datasharingterms/GetDataSharingTermsUseCase.kt
app/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt
app/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-pt/strings.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/google/android/ground/domain/usecases/datasharingterms/GetDataSharingTermsUseCaseTest.kt

Fixes #3031
Simplifies the logic for showing data sharing terms by replacing flows with getter and moving core logic to domain layer with unit tests.
@anandwana001 @gino-m @sufyanAbbasi  PTAL?

Move logic for showing data sharing terms to domain layers

---

app/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionFragment.kt
app/src/main/java/com/google/android/ground/ui/datacollection/DataSubmissionConfirmationDialog.kt
app/src/main/java/com/google/android/ground/ui/datacollection/DataSubmissionConfirmationScreen.kt
app/src/test/java/com/google/android/ground/ui/datacollection/DataCollectionFragmentTest.kt

Fixes #3050
Things done in this PR:
1. Hide the close button when displaying the confirmation screen
2. Handle edge case for back press on confirmation screen to directly navigate up
3. Simplify compose UI creation of the dialog
Tested locally
@gino-m  PTAL?

Hide close button after data is collected

---

app/src/main/java/org/groundplatform/android/ui/datacollection/DataCollectionViewModel.kt

Fixes #3081
Store the value to TaskDataHandler whenever we are resuming the draft.
I was able to reproduce the issue wherein the value for previous tasks was getting lost when locking and unlocking the screen multiple times. With this change, the data loss issue is no longer reproducible.

Fix data loss when locking screen during data collection 

---

app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskFragment.kt
app/src/main/java/org/groundplatform/android/ui/home/HomeScreenFragment.kt
app/src/main/java/org/groundplatform/android/ui/home/HomeScreenViewModel.kt

This PR adds a new flag to track whether or not we are restoring the application from an instantaneous photo capture. If so, we do not bother showing the draft resotred toast.
Since the HomeScreenFragment controls the toast display, we unfortunately need to track this state as shared state in the HomeScreenVM, giving access to this state in the PhotoTaskFragment. We might want to consider moving the toast display into the Task fragments themselves to better encapsulate this state in the future.
Fixes #3080
@gino-m

PhotoTask: Don't show draft toast on photo capture

---

app/src/main/java/org/groundplatform/android/LocalDatabaseModule.kt
app/src/main/java/org/groundplatform/android/persistence/sync/LocalMutationSyncWorker.kt
app/src/main/java/org/groundplatform/android/persistence/sync/MediaUploadWorker.kt
app/src/main/java/org/groundplatform/android/persistence/sync/SurveySyncWorker.kt
app/src/test/java/org/groundplatform/android/persistence/sync/LocalMutationSyncWorkerTest.kt
app/src/test/java/org/groundplatform/android/persistence/sync/MediaUploadWorkerTest.kt
app/src/test/java/org/groundplatform/android/persistence/sync/SurveySyncServiceTest.kt
app/src/test/java/org/groundplatform/android/persistence/sync/SurveySyncWorkerTest.kt

Fixes https://github.com/google/ground-android/issues/3097
Refactor database and worker classes to use IoDispatcher for coroutine context
PR description:
Refactored database and worker classes to use IoDispatcher for coroutine context instead of relying on default dispatchers or hardcoded executors. This ensures that I/O operations, such as database queries and background work, are executed on a thread pool optimized for I/O, improving performance and consistency across the application.
Checklist:
Refactored LocalDatabaseModule to continue using IoDispatcher for setQueryExecutor
Refactored LocalMutationSyncWorker.ktMediaUploadWorker/SurveySyncWorker/ to inject and use IoDispatcher instead of Dispatchers.IO

Refactor database and worker classes to use IoDispatcher for coroutine context

---

app/src/main/java/org/groundplatform/android/model/job/Job.kt
app/src/main/java/org/groundplatform/android/usecases/submission/SubmitDataUseCase.kt
app/src/test/java/org/groundplatform/android/FakeData.kt
app/src/test/java/org/groundplatform/android/usecases/submission/SubmitDataUseCaseTest.kt

Fixes #2981 
This caused an issue when AddLocationTask's value was also of type geometry, causing it to be considered as valid AddLoi task.

Refactor: Replace check for invalid addLoiTask using task type instead of task value

---

app/src/main/java/org/groundplatform/android/persistence/remote/firebase/FirestoreDataStore.kt
app/src/main/java/org/groundplatform/android/persistence/sync/LocalMutationSyncWorker.kt
app/src/main/java/org/groundplatform/android/repository/MutationRepository.kt
app/src/test/java/org/groundplatform/android/persistence/sync/LocalMutationSyncWorkerTest.kt

Fixes #2883
Access data layer via repository.
Also adds a safety check to prevent uploading of mutations from another user account.

[Code health] Access remote data store via mutation repository

---

app/src/main/java/org/groundplatform/android/Config.kt
app/src/main/java/org/groundplatform/android/ui/datacollection/components/TextTaskInput.kt
app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/AbstractTaskViewModel.kt
app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/multiplechoice/MultipleChoiceItemView.kt
app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskViewModel.kt
app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/text/TextTaskViewModel.kt
app/src/main/res/values/strings.xml
app/src/test/java/org/groundplatform/android/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskFragmentTest.kt
app/src/test/java/org/groundplatform/android/ui/datacollection/tasks/text/TextTaskFragmentTest.kt

This commit establishes an initial character limit for freeform text responses (including "other" entries for multiple choice questions). We set an initial limit of 255 characters, configurable in Config.kt. This commit also introduces an error message to indicate to users that they have hit the limit.
Fixes #2219

Impose a character limit on text data responses.

---

app/src/main/java/org/groundplatform/android/persistence/local/LocalValueStore.kt
app/src/test/java/org/groundplatform/android/MainViewModelTest.kt

Doesn't change any behavior. Replaces current usages of .edit() with a more idiomatic method.

Replace chained shared preferences edits with kotlin KTX extension function

---

app/src/test/java/org/groundplatform/android/persistence/sync/SurveySyncServiceTest.kt

The test was previously disabled due to a GCB specific flake.
Fixes #1787 
GCB has been deprecated. Re-enabling the previously disabled unit test

Re-enable flaky SurveySyncServiceTest

---

app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/multiplechoice/MultipleChoiceItemView.kt

Fixes #2403
This ensures that the text field for "Other" automatically gains focus, allowing the user to start typing immediately after selecting the option.
[other field focus.webm](https://github.com/user-attachments/assets/d7f747be-1b76-4f50-b674-78b098150b5a)
@gino-m  PTAL?

Request focus when "Other" option is selected

---

.github/dependabot.yml

Configured using https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
This was recommended by google.com organization guide.
Currently, the bot is configured to update the `gradle` and `github action` dependencies on a daily basis. Once, the dependencies are stable, then we can move on to a weekly interval.
@gino-m  PTAL?

Create a config to auto-update gradle and github actions using dependabot
