google/ground-android

gnd/src/main/java/com/google/android/gnd/rx/Result.java
So I can stop pulling these changes into every issue-24 branch :)
=> Merge Result Wrapper into issue-24/master

gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java
I forgot to update some calls to the Result API in the HomeScreenViewModel after intaking changes -.-
This fixes that mistake.
=> Bug: Fix calls to Result methods in HomeScreenVM

gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java
=> Fix Leaky Subscriptions in Map Container

gnd/src/main/java/com/google/android/gnd/rx/Result.java, gnd/src/main/java/com/google/android/gnd/ui/editrecord/EditRecordFragment.java, gnd/src/main/java/com/google/android/gnd/ui/editrecord/EditRecordViewModel.java
This change fixes leaky subscriptions in the Edit Record Fragment and View Model.
**Note:** At the moment this includes a quick fix for the homescreen--this change will disappear from this PR once #72 is merged--I just pulled it in here to make sure the edit record interactions were working as expected (since the bug addressed in #72 prevents builds).
Another brick on the road to #24.
=> Fix Leaky Subscriptions in Edit Record 

gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorDialogFragment.java, gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorViewModel.java
Another step toward finishing #24.
**Note**: This currently contains the quickfix for the homescreen. This change can be ignored and will go away once #72 is merged into issue-24/master.
=> Fix leaky subscriptions in the Project Selector

gnd/build.gradle, gnd/src/main/java/com/google/android/gnd/rx/Result.java, gnd/src/main/java/com/google/android/gnd/ui/editrecord/EditRecordFragment.java, gnd/src/main/java/com/google/android/gnd/ui/editrecord/EditRecordViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/RecordListViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java, gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorDialogFragment.java, gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorViewModel.java
Whew, so we:
* Created a Result for wrapping errors in nested streams
* Had some fruitful discussions about our handling of streams
* Fixed the leaky subscriptions.
Hooray!
Closes #24 
@navinsivakumar FYI
=> Fix Leaky Subscriptions

gnd/src/main/java/com/google/android/gnd/ui/editrecord/EditRecordViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java
https://github.com/google/ground-android/issues/84#issuecomment-498366352
=> Simplify edit record an add feature Rx error handling

gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java, gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorViewModel.java
Addressing conclusions in https://github.com/google/ground-android/issues/84#issuecomment-498366352
=> Clean up handling of project selection streams

gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java, gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/RecordListViewModel.java
Addressing conclusions in https://github.com/google/ground-android/issues/84#issuecomment-498366352
=> Simplify loading of record summaries and related error handling

build.gradle
Updates Gradle to version 3.4.1
=> Gradle: Update gradle version

gnd/src/main/java/com/google/android/gnd/GndApplicationModule.java, gnd/src/main/java/com/google/android/gnd/MainActivity.java, gnd/src/main/java/com/google/android/gnd/persistence/local/LocalDataStore.java, gnd/src/main/java/com/google/android/gnd/persistence/local/LocalValueStore.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/RemoteDataStore.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FirestoreDataStore.java, gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java, gnd/src/main/java/com/google/android/gnd/repository/InMemoryCache.java, gnd/src/main/java/com/google/android/gnd/repository/Persistable.java, gnd/src/main/java/com/google/android/gnd/system/AuthenticationManager.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerViewModel.java
=> Remember and restore last active project

gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java
Sorry I forgot to push these before merging. PTAL?
=> Missing commits from review of #138

gnd/src/main/java/com/google/android/gnd/persistence/local/LocalDataStore.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/FeatureMutationDao.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/FeatureMutationEntity.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/LocalDatabase.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/RecordMutationDao.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/RecordMutationEntity.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java, gnd/src/main/java/com/google/android/gnd/persistence/shared/FeatureMutation.java, gnd/src/main/java/com/google/android/gnd/persistence/shared/Mutation.java, gnd/src/main/java/com/google/android/gnd/persistence/shared/RecordMutation.java, gnd/src/main/java/com/google/android/gnd/persistence/sync/DataSyncWorkManager.java, gnd/src/main/java/com/google/android/gnd/persistence/sync/LocalMutationSyncWorker.java
Closes #147. Future work in #154.
For now retry indefinitely.
Could one you kindly give a quick look? Please reply here if you're looking so the other knows. Thanks in advance!
=> Retry sync on failure

gnd/src/main/res/values/strings.xml
"+ Observation instead of "+ Add observation", since "+" already implies "Add". It also looks a bit prettier imo.
=> [Feature sheet] Rename button label

gnd/src/main/java/com/google/android/gnd/persistence/sync/LocalMutationSyncWorker.java
For some reason part of sync was trying to run on UI thread.
Fixes #177. Filed #178 to track longer term fix.
=> [Offline sync] Fix broken data sync

gnd/src/main/java/com/google/android/gnd/model/layer/FeatureType.java, gnd/src/main/java/com/google/android/gnd/model/layer/Style.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/LocalDatabase.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FeatureTypeDoc.java, gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/FeatureSheetFragment.java, gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapAdapter.java
=> Use icon color in new feature type default style 

gnd/src/main/java/com/google/android/gnd/ui/editrecord/EditRecordFragment.java, gnd/src/main/java/com/google/android/gnd/ui/editrecord/EditRecordViewModel.java, gnd/src/main/res/layout/edit_record_frag.xml
=> Use DataBinding in EditRecordFragment

CONTRIBUTING.md, README.md
Add steps to run code health checks locally
=> Update README and CONTRIBUTING guidelines

config/pmd/pmd-ruleset.xml, gnd/src/main/java/com/google/android/gnd/model/observation/MultipleChoiceResponse.java, gnd/src/main/java/com/google/android/gnd/model/observation/TextResponse.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FeatureDoc.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/GndFirestore.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/RecordDoc.java, gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java, gnd/src/main/java/com/google/android/gnd/system/AuthenticationManager.java, gnd/src/main/java/com/google/android/gnd/ui/basemapselector/BasemapSelectorFragment.java, gnd/src/main/java/com/google/android/gnd/ui/common/AbstractDialogFragment.java, gnd/src/main/java/com/google/android/gnd/ui/common/BindingAdapters.java, gnd/src/main/java/com/google/android/gnd/ui/common/BottomSheetBehavior.java, gnd/src/main/java/com/google/android/gnd/ui/editrecord/EditRecordFragment.java, gnd/src/main/java/com/google/android/gnd/ui/editrecord/SingleSelectDialogFactory.java, gnd/src/main/java/com/google/android/gnd/ui/home/AddFeatureDialogFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java, gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapAdapter.java, gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorDialogFragment.java, gnd/src/main/java/com/google/android/gnd/ui/recorddetails/RecordDetailsFragment.java, gnd/src/main/java/com/google/android/gnd/ui/recorddetails/RecordDetailsViewModel.java, gnd/src/main/java/com/google/android/gnd/util/Enums.java, gnd/src/main/java/com/google/android/gnd/workers/FileDownloadWorker.java
- The enabled checks didn't require a lot of changes. So, enabled them in bulk than one by one as planned.
- Changes were made one commit at a time
@gino-m @scolsen I enabled these checks because they seemed harmless to me and improved code readability. Looking forward to discuss if you disagree with me and believe if some of them shouldn't be enabled.
=> [Code health] Enable few PMD checks

config/checkstyle/checkstyle.gradle, config/checkstyle/checkstyle.xml, config/checkstyle/java.header, config/checkstyle/xml.header, gnd/src/main/java/com/google/android/gnd/model/basemap/tile/Tile.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/TileDao.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/TileEntity.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/TileEntityState.java, gnd/src/main/java/com/google/android/gnd/ui/basemapselector/BasemapSelectorFragment.java, gnd/src/main/java/com/google/android/gnd/ui/basemapselector/BasemapSelectorModule.java, gnd/src/main/java/com/google/android/gnd/ui/basemapselector/BasemapSelectorViewModel.java, gnd/src/main/res/layout/basemap_selector_frag.xml, gnd/src/main/res/layout/edit_record_frag.xml, gnd/src/main/res/layout/feature_sheet_chrome.xml, gnd/src/main/res/layout/home_screen_frag.xml, gnd/src/main/res/layout/main_act.xml, gnd/src/main/res/layout/multiple_choice_input_field.xml, gnd/src/main/res/layout/project_selector_dialog.xml, gnd/src/main/res/layout/project_selector_list_item.xml, gnd/src/main/res/layout/record_details_frag.xml, gnd/src/main/res/layout/sign_in_frag.xml, gnd/src/main/res/layout/text_input_field.xml, gnd/src/main/res/layout/two_line_toolbar.xml
=> [Code health] Add check for license headers

config/checkstyle/checkstyle.xml, gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java, gnd/src/main/java/com/google/android/gnd/ui/common/BottomSheetBehavior.java, gnd/src/main/java/com/google/android/gnd/ui/common/EphemeralPopups.java, gnd/src/main/java/com/google/android/gnd/ui/common/ProgressDialogs.java
Validates the format of the Javadoc (if present)
=> [Code health] Check format of Javadoc summary

gnd/src/main/java/com/google/android/gnd/ui/common/BottomSheetBehavior.java
Revert changes made in https://github.com/google/ground-android/pull/221/commits/658eeed47895537c00e1ea61c1309b06d40a24eb
=> [Bug] Fix a regression caused during code health refactor

README.md
=> [Documentation] Add troubleshooting section

gnd/src/main/java/com/google/android/gnd/GndApplicationModule.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FirestoreDataStore.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FirestoreUuidGenerator.java
=> [Code health] Move implementation of OfflineUuidGenerator

README.md
For consistency with the other sites.
=> Updated the project description in the Android readme

gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java
=> [Refactor] Replace lambdas with method reference

config/pmd/pmd-ruleset.xml, gnd/src/test/java/com/google/android/gnd/repository/InMemoryCacheTest.java
I have chosen the most easiest class for adding tests. 
The motivation behind this is to have at least one test class written so that I can start working on running unit tests on cloud build as a first step (next Instrumentation Tests)
=> [Testing] Add tests for InMemoryCacheTest

README.md
=> [Code Health] Update badge link to point to Cloud Build Dashboard

cloudbuild.yaml
Run unit tests on cloud build
* Fixes output file to save both STDOUT and STDERR logs
=> [Cloud build] Run unit tests on cloud build

gnd/src/main/java/com/google/android/gnd/Config.java, gnd/src/main/java/com/google/android/gnd/GndApplicationModule.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/LocalDatabase.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java
This refactor is based on an existing TODO
- Adds new file to store project configurations
- Create database in module
- Inject DAOs directly
=> [Refactor] Inject DAOs directly

gnd/src/main/java/com/google/android/gnd/GndApplicationModule.java, gnd/src/main/java/com/google/android/gnd/MainActivity.java, gnd/src/main/java/com/google/android/gnd/persistence/local/LocalDataStore.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/LocalDatabase.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/UserDao.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/UserEntity.java, gnd/src/main/java/com/google/android/gnd/repository/ProjectRepository.java, gnd/src/main/java/com/google/android/gnd/repository/UserRepository.java
Add user entity and save user info on login
=> [Feature] Save user to local db

gnd/src/main/java/com/google/android/gnd/persistence/local/room/ObservationMutationDao.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java
=> [Offline sync] Fix broken observation mutation sync

gnd/src/main/java/com/google/android/gnd/MainActivity.java, gnd/src/main/java/com/google/android/gnd/system/AuthenticationManager.java, gnd/src/main/java/com/google/android/gnd/ui/common/Navigator.java
=> [Auth] Fix exception on failed sign in

gnd/src/main/java/com/google/android/gnd/Config.java, gnd/src/main/java/com/google/android/gnd/model/form/Field.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/FieldEntityType.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FormDoc.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java
Towards #310 
- Adds new field type to local and remote persistence
=> [Support Photos] Add field type photo

gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/AbstractFluentFirestore.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/GndFirestore.java, gnd/src/main/java/com/google/android/gnd/rx/RxCompletable.java, gnd/src/main/java/com/google/android/gnd/system/GoogleApiManager.java, gnd/src/main/java/com/google/android/gnd/system/NetworkManager.java, gnd/src/main/java/com/google/android/gnd/system/PermissionsManager.java, gnd/src/main/java/com/google/android/gnd/system/SettingsManager.java
Fixes #306. See issue tracker for details.
=> [Project list] Fix loading of project list when offline

cloudbuild.yaml, gnd/build.gradle
Closes #223 
Inspired from #288
=> [Code health] Run code health checks on build

gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java, gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorDialogFragment.java
Reverts google/ground-android#316
App crashes with following stacktrace on clicking **`+ Observation`** button
```
Process: com.google.android.gnd, PID: 11911
java.lang.IllegalStateException: Fragment ProjectSelectorDialogFragment{8b889db (d8b55ca0-0f4e-4fca-9e4a-344184805174)} not associated with a fragment manager.
at androidx.fragment.app.Fragment.requireFragmentManager(Fragment.java:910)
at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:245)
at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:202)
at com.google.android.gnd.ui.home.HomeScreenFragment.dismissProjectSelector(HomeScreenFragment.java:243)
at com.google.android.gnd.ui.home.HomeScreenFragment.onStop(HomeScreenFragment.java:232)
at …
```
=> Revert "[Project selector] Fix reappearing frozen project selector"

gnd/src/main/java/com/google/android/gnd/MainActivity.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FeatureDoc.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/ObservationDoc.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/ObservationListItemViewHolder.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java, gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsFragment.java, gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorDialogFragment.java, third_party/checkstyle/google_checks.xml
Adds a checkstyle rule for reporting missing default statements for switch case.
The error logs should be helpful in fixing bugs or cleaning up unused cases
=> [Code health] Enforce default statement in switch-case

gnd/src/main/AndroidManifest.xml
=> Update API key comment

config/lint/lint.xml, gnd/src/main/res/layout/edit_observation_frag.xml, gnd/src/main/res/layout/feature_sheet_frag.xml
=> [Code health] Fix minor lint warnings

build.gradle, gnd/build.gradle
Closes #188 
From Logcat with ❤️ 
```
2020-02-15 00:22:52.604 20804-20804/com.google.android.gnd I/CrashlyticsCore: Initializing Crashlytics Core 2.7.0.33
2020-02-15 00:22:57.877 20804-20941/com.google.android.gnd I/CrashlyticsCore: Crashlytics report upload complete: 5E46EBF901E1-0001-5084-797544D9403F
```
=> Log crash reports to Firebase Crashlytics

gnd/build.gradle, gradle.properties
Run check code right before installing the app for testing rather than build.
=> [Developer workflow] Fixes "No classes configured for SpotBugs analysis" bug

config/lint/lint.xml, gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/MultiSelectDialogFactory.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/SingleSelectDialogFactory.java, gnd/src/main/java/com/google/android/gnd/ui/home/AddFeatureDialogFragment.java, gnd/src/main/res/values-pt/strings.xml, gnd/src/main/res/values/strings.xml
=> Remove duplicate strings

gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/StyleTypeConverter.java
=> Allow null styles in remote db

build.gradle, gnd/src/main/res/layout/feature_sheet_header.xml, gradle/wrapper/gradle-wrapper.properties
Updated gradle version to latest using Android Studio's updater.
=> Bump up gradle version

gnd/build.gradle
- Updates all but material library to latest version (read commit description)
- Cleanup build.gradle for consistency
=> [Maintenance] Update non-conflicting gradle dependencies

gnd/src/main/java/com/google/android/gnd/Config.java, gnd/src/main/java/com/google/android/gnd/GndApplication.java, gnd/src/main/java/com/google/android/gnd/GndApplicationModule.java, gnd/src/main/java/com/google/android/gnd/inject/GndWorkerFactory.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/FirestoreStorageManager.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/RemoteStorageManager.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FirestoreStorageManager.java, gnd/src/main/java/com/google/android/gnd/persistence/sync/LocalMutationSyncWorker.java, gnd/src/main/java/com/google/android/gnd/persistence/sync/PhotoSyncWorkManager.java, gnd/src/main/java/com/google/android/gnd/persistence/sync/PhotoSyncWorker.java, gnd/src/main/java/com/google/android/gnd/repository/FeatureRepository.java, gnd/src/main/java/com/google/android/gnd/system/StorageManager.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java
Towards #310 
Things done:
- Added Worker and WorkerManager for photo sync
- Cleanup FirebaseStorageManager
- Minor Timber/lambdas nits that came across
Tested manually on emulator:
1. Network available -> New observation (FROGS project) -> Save
2. Network unavailable -> New observation (FROGS project) -> Save -> Killed the app -> Enable network -> Reopen the app
=> [Photos] Sync photos to FirebaseStorage using Workers

CONTRIBUTING.md
I realise now I should've done this on my own user branch, rather than using `ground-android`. Apologies. Will do so in future.
=> Add a couple of extra bits of info

build.gradle
Change suggested by IDE.
Tested app by manually creating a new observation for regressions.
=> Bump gradle to 3.6.2

gnd/src/main/java/com/google/android/gnd/repository/ProjectRepository.java
=> [Home screen] Reactivate project when restoring app

gnd/build.gradle
Fixes #460 
https://firebase.google.com/docs/perf-mon/disable-sdk?platform=android#disable-gradle-plugin
Disables the plugin by setting `instrumentationEnabled` to `false` only for debug build type.
This prevents `gnd:transformClassesWithFirebasePerformancePluginForDebug` task from getting executed.
To verify the changes, I ran 3 tests and performed the following steps for each.
- Disabled gradle cache from `gradle.properties` so that it does not affect test results
- Clean project
- Build project
Tests summary:
1. No changes(master branch): 57s
2. Commented out `apply plugin: 'com.google.firebase.firebase-perf'`: 23s
3. Set `instrumentationEnabled` as false: 22s
(with caching enabled, it only takes 5-7s with the new changes)
Full output:
----------------
1. Clean project
2. Build project …
=> Disable firebase performance plugin to speed up build time

gnd/src/main/java/com/google/android/gnd/ui/home/BottomSheetChromeBehavior.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenMetrics.java, gnd/src/main/java/com/google/android/gnd/ui/home/OnBottomSheetSlideBehavior.java, gnd/src/main/java/com/google/android/gnd/ui/home/SheetSlideMetrics.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerLayoutBehavior.java, gnd/src/main/res/layout/home_screen_frag.xml
=> [Feature sheet] Refactor/rename key bottom sheet elements

build.gradle, gnd/build.gradle, third_party/android-gmaps-addons/build.gradle
Periodic updates of 3rd party libraries
Tested by running the tests and app locally
=> Update gradle dependencies

gnd/src/main/java/com/google/android/gnd/repository/OfflineAreaRepository.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/map/MapAdapter.java, gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapAdapter.java, third_party/android-gmaps-addons/src/com/cocoahero/android/gmaps/addons/mapbox/MapBoxOfflineTileProvider.java
=> Fixed Tile Providers

build.gradle, gnd/build.gradle, gnd/src/main/java/com/google/android/gnd/GndApplication.java
=> Update crashlytics plugin

gnd/src/main/java/com/google/android/gnd/ui/editobservation/AbstractFieldViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java, gnd/src/main/res/layout/edit_observation_frag.xml, gnd/src/main/res/layout/multiple_choice_input_field.xml, gnd/src/main/res/layout/photo_input_field.xml, gnd/src/main/res/layout/text_input_field.xml
Fixes #493
- Add * next to required field labels
- Show errors when saving form
Screenshots:
------------
1. Clicking "+ Observation"
2. After clicking save:
@gino-m PTAL
=> [Bug fix] Display errors when saving form

gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java
=> [Add feature] Show observation form immediately after adding new feature

gnd/build.gradle, gnd/src/main/java/com/google/android/gnd/ui/common/AbstractFragment.java, gnd/src/main/java/com/google/android/gnd/ui/common/TwoLineToolbar.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/MultipleChoiceFieldLayout.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/featuredetails/FeatureDetailsFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/featuredetails/ObservationListFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java, gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsFragment.java, gnd/src/main/java/com/google/android/gnd/ui/offlinearea/OfflineAreasFragment.java, gnd/src/main/java/com/google/android/gnd/ui/offlinearea/selector/OfflineAreaSelectorFragment.java, gnd/src/main/java/com/google/android/gnd/ui/offlinearea/viewer/OfflineAreaViewerFragment.java, gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorDialogFragment.java
Closes #418 
Manually tested all screens for regression:
* Offline areas
* Settings
* Add feature
* Add / edit / view observation
@dturner PTAL.
=> [Code health] Replace Butterknife with ViewBinding

gnd/src/main/java/com/google/android/gnd/repository/ObservationRepository.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java
Closes #523 
Move boilerplate code for generating mutations to ObservationRepository
=> Refactor ObservationRepository

config/pmd/pmd.gradle
Bumps pmd plugin to [latest](https://pmd.github.io/) version.
=> Update pmd plugin

.github/pull_request_template.md
Refactored existing template by adding comments ``. This way, we can keep the template without deleting anything when creating a new PR.
=> Update template for Pull Requests

config/pmd/pmd-ruleset.xml, gnd/src/main/java/com/google/android/gnd/rx/RxDebug.java, gnd/src/main/java/com/google/android/gnd/system/LocationManager.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/SingleSelectDialogFactory.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java, gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorDialogFragment.java
- Enables a `pmd` rule to detect all unused formal parameters
- Fix all detected warnings
=> [Code health] Remove ununsed parameters

gnd/src/main/java/com/google/android/gnd/AbstractActivity.java, gnd/src/main/java/com/google/android/gnd/system/NetworkManager.java, gnd/src/main/java/com/google/android/gnd/ui/MarkerIconFactory.java, gnd/src/main/java/com/google/android/gnd/ui/common/EphemeralPopups.java, gnd/src/main/java/com/google/android/gnd/ui/common/ProgressDialogs.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/FieldViewFactory.java, gnd/src/main/java/com/google/android/gnd/ui/home/featuredetails/ObservationListItemViewHolder.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java, gnd/src/main/java/com/google/android/gnd/ui/util/DrawableUtil.java, gnd/src/main/java/com/google/android/gnd/ui/util/FileUtil.java, gnd/src/main/java/com/google/android/gnd/ui/util/ViewUtil.java
Changes suggested by Android Studio. 
Done by invoking `Analyze > Infer Support Annotations`
=> Add supported annotations

gnd/src/main/java/com/google/android/gnd/persistence/local/LocalDataStore.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/LocalDataStoreException.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/base/FluentDocumentReference.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/base/FluentFirestore.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/RecordDocumentReference.java, gnd/src/main/java/com/google/android/gnd/persistence/sync/LocalMutationSyncWorker.java, gnd/src/main/java/com/google/android/gnd/repository/ObservationRepository.java, gnd/src/main/java/com/google/android/gnd/system/AuthenticationManager.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsFragment.java, gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsViewModel.java, gnd/src/test/java/com/google/android/gnd/persistence/local/LocalDataStoreTest.java
=> [Manage observations] Add ability to remove observations

gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/dao/LayerDao.java, gnd/src/test/java/com/google/android/gnd/persistence/local/LocalDataStoreTest.java
Fixes #512 
Verified by adding a unit test
=> [Offline support] Remove old layers when inserting new ones

.idea/codeStyles/Project.xml, gnd/src/main/java/com/google/android/gnd/persistence/local/LocalDataStore.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/dao/FeatureDao.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/dao/ObservationDao.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/FeatureEntity.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/FeatureDocumentReference.java, gnd/src/main/java/com/google/android/gnd/persistence/sync/LocalMutationSyncWorker.java, gnd/src/main/java/com/google/android/gnd/repository/FeatureRepository.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java, gnd/src/main/res/layout/feature_details_chrome.xml, gnd/src/main/res/values/styles.xml, gnd/src/test/java/com/google/android/gnd/persistence/local/LocalDataStoreTest.java
Fixes #108 
This PR aims at making the `Delete Feature` item in menu functionable.
Steps to verify:
- Open app
- Click `+` to add a new feature
- Select `Delete Feature` from the options menu
@gino-m  PTAL?
=> [Feature] Add ability to delete features

gnd/src/main/java/com/google/android/gnd/persistence/remote/RemoteDataEvent.java, gnd/src/main/java/com/google/android/gnd/repository/FeatureRepository.java
=> [Sync] Remove local feature when deleted remotely

.idea/codeStyles/Project.xml, gnd/src/main/java/com/google/android/gnd/Config.java, gnd/src/main/java/com/google/android/gnd/model/form/Element.java, gnd/src/main/java/com/google/android/gnd/model/form/Field.java, gnd/src/main/java/com/google/android/gnd/model/form/Form.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/FieldEntity.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/FieldConverter.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/FormConverter.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/featuredetails/ObservationListItemViewHolder.java, gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsFragment.java, gnd/src/test/java/com/google/android/gnd/persistence/local/LocalDataStoreTest.java
=> [View/add/edit observations] Sort fields by `index` defined in form

gnd/src/main/java/com/google/android/gnd/ui/home/BottomSheetMetrics.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerLayoutBehavior.java
Fixes #548 
@gino-m @scolsen PTAL
=> Keep the map centered when expanding/collapsing bottom sheet

build.gradle
=> Bump gradle to 4.0.1

gnd/src/main/java/com/google/android/gnd/persistence/local/room/converter/ResponseJsonConverter.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/QuerySnapshotConverter.java, gnd/src/main/java/com/google/android/gnd/repository/FeatureRepository.java
Fixes #470 
Added detailed explanation about the solution in the commit description.
Steps to verify bug:
1. Login into app with test user
1. Choose 'sample project' from the list of projects
1. All features should be loaded on first attempt
@gino-m  PTAL?
=> [Bug] Load all features after activating project

gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java, gnd/src/main/res/layout/edit_observation_frag.xml
Fixes #556, Fixes #553 
Steps to verify:
1. Select any project and add a new feature
2. On "edit observation" screen, tap on text field to show the soft keyboard (input)
3. Click "save"
4. Blue screen shouldn't appear
Trying the above steps on master branch results in a blue screen.
@gino-m  PTAL?
=> Hide soft keyboard when saving form

.idea/codeStyles/Project.xml, gnd/src/main/java/com/google/android/gnd/GndApplicationModule.java, gnd/src/main/java/com/google/android/gnd/model/feature/Feature.java, gnd/src/main/java/com/google/android/gnd/ui/common/FeatureHelper.java, gnd/src/main/java/com/google/android/gnd/ui/home/featuredetails/FeatureDetailsFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/featuredetails/FeatureDetailsViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsFragment.java, gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsViewModel.java, gnd/src/main/res/layout/feature_details_frag.xml, gnd/src/main/res/layout/feature_details_header.xml, gnd/src/main/res/layout/observation_details_frag.xml, gnd/src/main/res/values/strings.xml
=> Display name of the user who created the feature under title

build.gradle, gradle/wrapper/gradle-wrapper.properties
Tested manually for regressions
@dturner PTAL
=> Bump gradle version

gnd/build.gradle
Changes verified by running unit & instrumented tests manually
@dturner PTAL
=> Update testing dependencies

gnd/src/main/res/layout/map_move_feature_layout.xml
This confuses our instrumentation tests
Fixes #598 
@dturner PTAL?
=> [Regression] Do not use same id for different ImageViews

gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapAdapter.java
These bugs were introduced in the last PR.
Tested manually using examples project.
@gino-m  PTAL?
=> [Bug] Fix regressions for adding/removing a MapPin

gnd/src/main/java/com/google/android/gnd/persistence/local/LocalValueStore.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java, gnd/src/main/java/com/google/android/gnd/ui/map/MapProviderModule.java, gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapAdapter.java, gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapProvider.java
The map type resets after app restart. So, this is to resolve that problem.
@gino-m  PTAL?
=> [Map] Map type should persist after re-opening the app

gnd/src/main/java/com/google/android/gnd/repository/ProjectRepository.java
Related #451 
Increase timeout when fetching project summaries from remote db.
=> Increase remote query timeout

gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerViewModel.java
Fixes #550 
* Move subscription for clicks from onViewCreated() to onMapReady()
* Replace MutableLiveData with a PublishSubject to debounce clicks faster than 250ms
@gino-m  PTAL?
=> [Map] Fix NPE when rotating screen after selecting map type

gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/FeatureEntity.java
=> Ignore features with unknown layerId

build.gradle
=> Upgrade Gradle Build Tools version

build.gradle
Periodic update to latest Gradle build. Updated errorprone in the process originally upgrade while debugging compile issues.
=> Upgrade gradle build to 4.1.1, errorprone to 1.3.0

cloudbuild.yaml, gnd/build.gradle, third_party/android-gmaps-addons/build.gradle
=> [Bug] Use "staging" buildType for CI

gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
Steps to reproduce the error in `master`:
1. Select any project
2. Click on any point feature
3. Rotate the screen twice
4. Open the overflow menu and click on "Move Feature"
@gino-m  PTAL?
=> [Bug] Fix NPE when moving feature

gnd/src/main/java/com/google/android/gnd/ui/common/Navigator.java
This doesn't fix any issues, just prevents the throwing of exception.
@dturner  PTAL?
=> Don't throw runtime exception if id not found

gnd/src/main/res/xml/preferences.xml
=> Remove empty icon space in preference screen

cloud-builder/Dockerfile-base, cloudbuild.yaml
Fixes #646
@gino-m  PTAL?
Before:
After:
=> Update build tools version and install gcloud

.idea/codeStyles/Project.xml, gnd/build.gradle, gnd/src/main/java/com/google/android/gnd/MainActivity.java, gnd/src/main/java/com/google/android/gnd/MainViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/common/Navigator.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/home/featuredetails/ObservationListFragment.java, gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsFragment.java, gnd/src/main/java/com/google/android/gnd/ui/offlinebasemap/OfflineBaseMapListAdapter.java, gnd/src/main/java/com/google/android/gnd/ui/offlinebasemap/OfflineBaseMapsViewModel.java, gnd/src/main/res/navigation/nav_graph.xml
This removed the workaround previously requires due to broken back/up stack with global actions (#3) 
Fixes #253.
=> [Code health] Update nav components and simplify usage

gnd/src/main/java/com/google/android/gnd/MainActivity.java, gnd/src/main/java/com/google/android/gnd/MainViewModel.java
Contributes to #9, @dturner as discussed. PTAL?
=> [Code health] Move authentication handling into MainViewModel

gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java, gnd/src/main/res/layout/home_screen_frag.xml
=> Re-enable build version label

gnd/src/main/java/com/google/android/gnd/MainActivity.java, gnd/src/main/java/com/google/android/gnd/MainViewModel.java, gnd/src/main/res/values/strings.xml
=> Show progress dialog when signing in app

gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/MultiSelectDialogFactory.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/MultipleChoiceFieldViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/SelectDialogFactory.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/SingleSelectDialogFactory.java
Things done:
* Added a base class for Single/Multi dialog factory
* Refactored existing dialog factory classes to use this new base class.
* Merged inner DialogState class to improve readability
@gino-m  PTAL?
=> Refactor handler for MultipleChoiceFields

gnd/build.gradle, gnd/src/main/java/com/google/android/gnd/model/Mutation.java, gnd/src/main/java/com/google/android/gnd/model/Project.java, gnd/src/main/java/com/google/android/gnd/model/form/Element.java, gnd/src/main/java/com/google/android/gnd/model/form/Field.java, gnd/src/main/java/com/google/android/gnd/model/form/Form.java, gnd/src/main/java/com/google/android/gnd/model/form/MultipleChoice.java, gnd/src/main/java/com/google/android/gnd/model/layer/Layer.java, gnd/src/main/java/com/google/android/gnd/model/observation/Observation.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/MutationEntity.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/ObservationMutationEntity.java
* Removes redundant `@Nonnull`
* Removes `@Nullable` from Builders that are being complained by the updated plugin
=> Update auto-value plugin

third_party/checkstyle/google_checks.xml
Found while cleaning up TODOs in #715.
=> [Code health] Use relative path to license headers in checkstyle

gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java, gnd/src/main/res/navigation/nav_graph.xml
=> [Add observation] Use empty arg instead of special value for "new"

gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
=> [Project selector] Create project selector once in onCreate

gnd/src/main/java/com/google/android/gnd/GndApplicationModule.java, gnd/src/main/java/com/google/android/gnd/repository/OfflineBaseMapRepository.java, gnd/src/main/java/com/google/android/gnd/system/GeocodingManager.java, gnd/src/main/java/com/google/android/gnd/ui/offlinebasemap/selector/OfflineBaseMapSelectorFragment.java, gnd/src/main/res/values/strings.xml
Work towards #699.
@scolsen Would you mind having a look-see? 🥇
=> [Code health] GeocodingManager readability tweaks 

gnd/src/main/java/com/google/android/gnd/system/PermissionsManager.java
Work towards #699.
@scolsen PTAL?
=> [Code health] Document PermissionsManager

gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsFragment.java, gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsViewModel.java, gnd/src/main/res/layout/observation_details_frag.xml
Work towards #699
@gino-m  PTAL?
=> [Code health] Document ObservationDetails

gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/FeatureConverter.java
Remove already fixed TODO and redundunt `@NonNull` from args.
=> [Code health] Clean-up todos

gnd/src/main/java/com/google/android/gnd/model/TestModelBuilders.java, gnd/src/main/java/com/google/android/gnd/model/form/Field.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/models/FieldEntityType.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/FieldConverter.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/ObservationConverter.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/FieldViewFactory.java, gnd/src/main/java/com/google/android/gnd/util/Enums.java, gnd/src/test/java/com/google/android/gnd/persistence/local/LocalDataStoreTest.java, gnd/src/test/java/com/google/android/gnd/persistence/remote/firestore/schema/ObservationConverterTest.java, gnd/src/test/java/com/google/android/gnd/repository/FeatureRepositoryTest.java
Fixes #759.
@scolsen Could you PTAL?
=> Expect "text_field" for text fields instead of "text" in remote db

gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/converter/ResponseDeltasConverter.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/converter/ResponseJsonConverter.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/converter/ResponseMapConverter.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/ObservationEntity.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/ObservationMutationEntity.java, gnd/src/test/java/com/google/android/gnd/persistence/local/LocalDataStoreTest.java
=> [Code health] Use form definition when deserializing observation mutations in local db

gnd/src/main/java/com/google/android/gnd/model/form/Field.java, gnd/src/main/java/com/google/android/gnd/model/observation/NumberResponse.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/converter/ResponseJsonConverter.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/models/FieldEntityType.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/FieldConverter.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/ObservationConverter.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/ObservationMutationConverter.java, gnd/src/main/java/com/google/android/gnd/ui/common/ViewModelModule.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/FieldViewFactory.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/NumberFieldViewModel.java, gnd/src/main/res/layout/number_input_field.xml
This PR adds support for numeric fields (currently limited to Doubles)
Fixes issue #23
=> Add support for numeric fields.

gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/map/MapAdapter.java, gnd/src/main/java/com/google/android/gnd/ui/map/MapGeoJson.java, gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapAdapter.java
No style/camera moves happen yet, we'll need to implement those on top of these changes.
=> feat: Make geojson features selectable

gnd/src/main/java/com/google/android/gnd/persistence/local/room/models/FieldEntityType.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/FieldConverter.java
@scolsen FYI. @HemanParbhakar PTAL?
=> [Code health] Simplify/clean up field converters

gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerLayoutBehavior.java
Fixes #802, maybe fixes #786 (can't repro anymore).
@scolsen Could you PTAL?
=> [Map] Fix map Y offset after bottom sheet collapse

gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/PhotoFieldViewModel.java, gnd/src/main/res/layout/photo_field.xml, gnd/src/main/res/layout/photo_input_field.xml
Fixes #768. @shobhitagarwal1612 PTAL? 👀
=> [Add/Edit Observation] Hide "Add photo" button when photo exists

gnd/src/main/java/com/google/android/gnd/GndApplication.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FirestoreStorageManager.java, gnd/src/main/java/com/google/android/gnd/persistence/sync/PhotoSyncWorkManager.java, gnd/src/main/java/com/google/android/gnd/repository/UserMediaRepository.java, gnd/src/main/java/com/google/android/gnd/system/StorageManager.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/PhotoFieldViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/util/FileUtil.java
@shobhitagarwal1612 Could you PTAL? Sorry for PR flood!
=> [Photo upload] Minor cleanup and debugging

gnd/src/main/res/layout/photo_input_field.xml
=> [Bug] Display validation error for photo fields

gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java
Fixes #856
Contributes to #668, #690. 
=> Stop replaying home screen actions on config changes

cloudbuild.yaml, gnd/build.gradle
Make `testBuildType` configurable. 
Default value is "debug" for local testing/development. For GCB, using flag to set it to "staging"
@gino-m  PTAL?
=> [Code health] Fix instrumentation tests not building locally

gnd/src/main/java/com/google/android/gnd/ui/home/BottomSheetState.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
=> [Feature] Hide "move feature" option for non-point features

gnd/src/main/res/values-pt/strings.xml, gnd/src/main/res/values/strings.xml
Provided by Imaflora. @mmisim PTAL?
=> [i18n] Add remaining Portuguese translations

gnd/src/main/AndroidManifest.xml, gnd/src/main/java/com/google/android/gnd/repository/UserMediaRepository.java, gnd/src/main/java/com/google/android/gnd/system/CameraManager.java, gnd/src/main/java/com/google/android/gnd/system/StorageManager.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/util/FileUtil.java, gnd/src/main/res/xml/file_paths.xml, gnd/src/test/java/com/google/android/gnd/system/CameraManagerTest.java, gnd/src/test/java/com/google/android/gnd/system/StorageManagerTest.java
Fixes https://github.com/google/ground-platform/issues/761
Things done:
* Save photos captured / selected from gallery to external storage directory
* Move photo handling related code to UserMediaRepository
* Remove bitmap/photo handling code from `FileUtil` and let it be generic utility class.
* Cleanup EditObservationViewModel by moving unrelated code to media related classes.
@gino-m  PTAL?
=> [Photos] Save full resolution when capturing image via camera

cloudbuild.yaml
Disabling until #922 is resolved to unblock current stream of PRs.
@shobhitagarwal1612 Wdyt?
=> [CI] Temporarily disable running UI tests in CI

cloudbuild.yaml
=> [CI] Reenable Cloud authenticate

gnd/src/main/java/com/google/android/gnd/persistence/local/LocalValueStore.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/FeatureMutationEntity.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerViewModel.java, gnd/src/main/res/values-pt/strings.xml
Fixes #910.
Fixes #911.
Fixes #913.
@shobhitagarwal1612 Could you PTAL?
=> [Stability] Fixes several exceptions reported by Crashlytics and in logs

gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/FeatureMutationEntity.java, gnd/src/main/res/values-pt/strings.xml
Fixes #913.
@HemanParbhakar One more small one?
=> [Offline areas] Fixes crash on showing offline areas screen due to bad string format

gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/FeatureMutationEntity.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerViewModel.java, gnd/src/main/res/values-pt/strings.xml
Fixes #911.
@shobhitagarwal1612 Could you PTAL?
=> [Map] Fixes crash when moving points

gnd/src/main/java/com/google/android/gnd/model/feature/Feature.java, gnd/src/main/java/com/google/android/gnd/model/feature/PolygonFeature.java
Contributes to #358 
Implemented Polygon Feature Model class
@gino-m @atalekar  PTAL?
=> [Polygon Drawing] Implement PolygonFeature model class

gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapAdapter.java
The listener was getting reset on each change to GeoJSON on the map.
@scolsen PTAL?
=> [Map] Only register map click listener once

gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java, gnd/src/main/res/layout/map_home_layout.xml, gnd/src/main/res/xml/preferences.xml
* Fixes a bug when adding a new feature
* Menu icon tint
* Hide missing feature from settings
@gino-m  PTAL?
=> [Bug] Fix crash when creating a new feature

gnd/src/main/java/com/google/android/gnd/model/TestModelBuilders.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/FeatureEntity.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/FeatureConverter.java, gnd/src/test/java/com/google/android/gnd/persistence/remote/firestore/schema/FeatureConverterTest.java
Contributes #358 
Load polygon features from remote db.
@shobhitagarwal1612  @gino-m PTAL?
=> [Polygon Drawing] Load polygon features from remote db.

config/pmd/pmd-ruleset.xml, gnd/src/androidTest/java/com/google/android/gnd/DataBindingIdlingResource.java, gnd/src/test/java/com/google/android/gnd/persistence/local/LocalDataStoreTest.java, gnd/src/test/java/com/google/android/gnd/persistence/remote/firestore/schema/FeatureConverterTest.java, gnd/src/test/java/com/google/android/gnd/persistence/remote/firestore/schema/ObservationConverterTest.java
Enables PMD plugin for test classes.
@gino-m PTAL?
=> [Code quality] Enable PMD plugin for tests

gnd/build.gradle, gnd/src/main/java/com/google/android/gnd/ui/common/FeatureHelper.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/map/MapPolygon.java, gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapAdapter.java, gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapProvider.java, gnd/src/main/java/com/google/android/gnd/ui/util/BitmapUtil.java, gnd/src/main/res/drawable/ic_endpoint.xml, gnd/src/main/res/values/dimens.xml
Contributes #358 
Polygon loaded from local db and shown on Map.
@gino-m @shobhitagarwal1612  PTAL?
=> [Polygon Drawing] Render polygons on map

gnd/src/androidTest/java/com/google/android/gnd/persistence/remote/FakeRemoteDataStore.java, gnd/src/main/java/com/google/android/gnd/model/layer/Layer.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/LayerEntity.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/LayerConverter.java, gnd/src/main/java/com/google/android/gnd/repository/ProjectRepository.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapAdapter.java, gnd/src/main/res/layout/map_home_layout.xml
Fixes #965:
Also does some minor cleanup.
@scolsen or @shobhitagarwal1612 PTAL?
=> [Map] Fix broken add feature button

gnd/build.gradle, gnd/src/main/java/com/google/android/gnd/model/feature/Feature.java, gnd/src/main/java/com/google/android/gnd/model/feature/PointFeature.java, gnd/src/main/java/com/google/android/gnd/model/feature/PolygonFeature.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/RemoteDataEvent.java, gnd/src/main/java/com/google/android/gnd/repository/FeatureRepository.java, gnd/src/main/java/com/google/android/gnd/repository/ObservationRepository.java, gnd/src/main/java/com/google/android/gnd/repository/ProjectRepository.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java, gnd/src/test/java/com/google/android/gnd/repository/FeatureRepositoryTest.java
Fixes #80 
The intention behind this PR is to cleanup pending TODOs and improve test coverage.
Followed TDD approach for this PR.
* Cleaned up unit tests + new test library (power-mockito)
* Increased test coverage of FeatureRepository to 100%
* Added helper method : Create a new mutation from the feature via it's internal method
* Provide "mutations" instead of "feature" when performing create/update/delete operations.
* Simplify code by replacing `Maybe` with `Single` when attempting to get a feature from repo
* Remove dependency : project id should be the active project when fetching a feature 
@gino-m PTAL?
=> [Feature Repository] Add tests and cleanup ToDos

build.gradle, config/spotbugs/spotbugs-filter.xml, config/spotbugs/spotbugs.gradle, gnd/build.gradle, gnd/src/main/java/com/google/android/gnd/persistence/local/LocalValueStore.java, gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/ObservationConverter.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/OptionNestedObject.java, gnd/src/main/java/com/google/android/gnd/rx/RxCompletable.java, gnd/src/main/java/com/google/android/gnd/system/rx/RxFusedLocationProviderClient.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/featureselector/FeatureSelectorFragment.java, gnd/src/main/java/com/google/android/gnd/ui/settings/Keys.java, gnd/src/main/java/com/google/android/gnd/ui/syncstatus/SyncStatusListAdapter.java, gnd/src/main/java/com/google/android/gnd/ui/syncstatus/SyncStatusViewHolder.java
Re-enables `spotbugs` plugin disabled in https://github.com/google/ground-android/pull/501
@gino-m  PTAL?
=> [Code analysis plugin] Re-enable spotbugs plugin

gnd/src/main/java/com/google/android/gnd/model/layer/Layer.java, gnd/src/main/java/com/google/android/gnd/ui/common/FeatureHelper.java, gnd/src/sharedTest/java/com/google/android/gnd/FakeData.java, gnd/src/test/java/com/google/android/gnd/ui/common/FeatureHelperTest.java
I've added all possible cases by looking at the code. PLMK if i've missed any.
=> [Code health] Add unit tests for FeatureHelper

gnd/build.gradle
It is difficult to find the commit using the current version name.
So, append the current commit's SHA1 for better debugging.
e.g. `7539-SNAPSHOT(2 +5 -1) a345bc3f96dc369c32eb1b540890ac3fb4eba7b2`
@gino-m PTAL?
=> Append commit sha1 to version name

gnd/src/main/java/com/google/android/gnd/system/LocationManager.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerViewModel.java, gnd/src/main/res/layout/map_container_frag.xml, gnd/src/main/res/values/strings.xml
Fixes #979
* Adds an overlay on map with location accuracy
* GPS satellite updates can't be fetched using current `FusedLocationProviderClient`. Needs more effort.
@gino-m  PTAL?
=> [UX] Show location accuracy on map

gnd/build.gradle
Update compileSdkVersion and targetSdkVersion to the latest stable release (30).
=> Update compileSdkVersion and targetSdkVersion to 30.

gnd/src/main/java/com/google/android/gnd/ui/map/MapProviderModule.java
MapProvider is injected into both `FeatureRepositionView` and `MapContainerFragment`. Without a singleton, each would have a different copy of MapProvider.
@gino-m PTAL?
=> [Regression] Make MapProvider singleton

cloudbuild.yaml, config/lint/lint.xml, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java, gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsFragment.java, gnd/src/main/res/values-pt/strings.xml
=> [Code health] Lint checks & CI fix

build.gradle, gnd/build.gradle, third_party/android-gmaps-addons/build.gradle
=> Moves common gradle configs to root level

gnd/src/main/res/layout/polygon_drawing_controls.xml
Contributes to #358
This PR fixes styling issue of Polygon Drawing Controls assigning each widget with proper marign.
@gino-m @atalekar PTAL?
=> [Polygon Drawing] Fixed spacing issue for polygon drawing controls

gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/PolygonDrawingInfoDialogFragment.java, gnd/src/main/res/layout/dialog_polygon_info.xml
Contributes to #358 
This PR fixes styling issue of Polygon Dialog fragment UI Design as per the Figma.
@gino-m @atalekar  PTAL?
=> [Polygon Drawing] Fixed styling issue for polygon  info dialog.

build.gradle
The performance should be better now with #1008.
=> Upgrade compile and target SDK version.

gnd/src/main/java/com/google/android/gnd/model/Project.java, gnd/src/main/java/com/google/android/gnd/model/Role.java, gnd/src/main/java/com/google/android/gnd/model/feature/FeatureType.java, gnd/src/main/java/com/google/android/gnd/model/layer/Layer.java, gnd/src/main/java/com/google/android/gnd/repository/ProjectRepository.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java, gnd/src/sharedTest/java/com/google/android/gnd/FakeData.java, gnd/src/test/java/com/google/android/gnd/repository/ProjectRepositoryTest.java
Fixes #1035
Fixes #1044
Added some tests for `ProjectRepository`, more will be added in a series of test bashes this quarter.
@atalekar Could you PTAL?
=> Respect layer settings when determining "add feature" permissions

gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/LayerConverter.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java
=> Fix layer permissions issues

gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/PolygonDrawingView.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/PolygonDrawingViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/map/MapFragment.java, gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsFragment.java, gnd/src/main/res/layout/polygon_drawing_controls.xml
Fixes #1050
Fixes #1054 
Contributes to #1052 
@rachaprince PTAL?
=> [Add polygon] Polygon drawing UI tweaks and fixes

gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/PolygonDrawingViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsFragment.java
Fixes two small bugs discovered during manual testing:
- Centers the custom icon in the crosshairs when adding points
- Prevents an Array index out of bounds error when removing vertices
=> UI bug fixes

gnd/src/main/java/com/google/android/gnd/system/LocationManager.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/PolygonDrawingViewModel.java, gnd/src/main/res/layout/polygon_drawing_controls.xml, gnd/src/test/java/com/google/android/gnd/ui/home/mapcontainer/PolygonDrawingViewModelTest.java
Fixes #1052
Adds full coverage for polygon drawing flow. The remaining code coverage is related to location lock. IMO, we should separate it out into an UI component and use it everywhere.
@gino-m  PTAL?
=> Add tests for PolygonDrawing flow

build.gradle, config/jacoco/jacoco.gradle, config/lint/lint.xml, gnd/build.gradle, gnd/src/main/java/com/google/android/gnd/ui/offlinebasemap/OfflineAreaListAdapter.java, gradle.properties, gradle/wrapper/gradle-wrapper.properties
Updates gradle to 7.0.3
* Improves code coverage stats by excluding remaining auto-generated classes
* Removes unused `powermock` library
* Updates dependent navigation and hilt libraries
@gino-m  PTAL?
=> Update to gradle 7.0.3

gnd/src/main/java/com/google/android/gnd/ui/editobservation/AbstractFieldViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java
@shobhitagarwal1612 I did some renaming and minor refactoring to make things easier to reason about. PTAL?
Contributes to #1067, #1068.
=> [Add/edit observation] Minor cleanup

gnd/src/main/java/com/google/android/gnd/model/form/MultipleChoice.java, gnd/src/main/java/com/google/android/gnd/model/form/Option.java, gnd/src/main/java/com/google/android/gnd/model/observation/DateResponse.java, gnd/src/main/java/com/google/android/gnd/model/observation/MultipleChoiceResponse.java, gnd/src/main/java/com/google/android/gnd/model/observation/NumberResponse.java, gnd/src/main/java/com/google/android/gnd/model/observation/Response.java, gnd/src/main/java/com/google/android/gnd/model/observation/TextResponse.java, gnd/src/main/java/com/google/android/gnd/model/observation/TimeResponse.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java, gnd/src/main/res/navigation/nav_graph.xml
Depends on #1069. [Relevant diffs](https://github.com/google/ground-android/pull/1070/files/a782a64bd1e41cf3b355033cad5419a8c4782a74..980e7ee26889a967e4f6c721cfd9241b3087b249).
Fixes #1067.
Contributes to #1068.
@atalekar FYI.
=> [Add/edit observation] Save/restore form states to bundle when activity is paused

gnd/src/main/java/com/google/android/gnd/system/ApplicationErrorManager.java, gnd/src/test/java/com/google/android/gnd/system/ApplicationErrorManagerTest.java
Fixes #1072.
@rachaprince could you PTAL?
=> Allow app to open when network is not available

gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/PhotoFieldViewModel.java, gnd/src/main/res/layout/photo_field.xml, gnd/src/main/res/layout/photo_input_field.xml
Fixes #1068 (for real this time)
=> [Add/edit observation] Clear photo in parent view model

gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java, gnd/src/main/res/values-es/strings.xml, gnd/src/main/res/values-pt/strings.xml, gnd/src/main/res/values/strings.xml
=> [Add/edit observation] Reword "discard changes" prompt

gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/editobservation/PhotoFieldViewModel.java
Save actual size photo instead of thumbnail when capturing photo.
@gino-m  PTAL?
=> Fix photo capture flow

gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/PolygonDrawingViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/TransientMapFeatures.java, gnd/src/main/java/com/google/android/gnd/ui/map/MapPin.java, gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsFragment.java, gnd/src/test/java/com/google/android/gnd/ui/home/mapcontainer/PolygonDrawingViewModelTest.java
Towards #1056
Adds a temporary marker for each selected point while drawing polygon.
@atalekar  PTAL?
=> Draw marker for each drawn polygon vertex

gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FirestoreDataStore.java, gnd/src/main/java/com/google/android/gnd/persistence/sync/LocalMutationSyncWorker.java, gnd/src/main/java/com/google/android/gnd/persistence/sync/PhotoSyncWorker.java
=> Report non-fatal mutation sync errors to Crashlytics

gnd/src/sharedTest/java/com/google/android/gnd/persistence/remote/FakeRemoteDataStore.java, gnd/src/test/java/com/google/android/gnd/ui/MarkerIconFactoryTest.java, gnd/src/test/java/com/google/android/gnd/ui/projectselector/ProjectSelectorDialogFragmentTest.java
Fixes #577
Adds tests for ProjectSelectorDialog
@gino-m @shobhitagarwal1612 PTAL
=> Add ProjectSelectorDialogFragmentTest

config/jacoco/jacoco.gradle, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/FeatureDataTypeSelectorDialogFragment.java, gnd/src/test/java/com/google/android/gnd/ui/mapcontainer/FeatureDataTypeSelectorDialogFragmentTest.java, gnd/src/test/java/com/google/android/gnd/ui/projectselector/ProjectSelectorDialogFragmentTest.java
=> Add tests for FeatureDataTypeSelectorFragment

config/jacoco/jacoco.gradle, gnd/src/test/java/com/google/android/gnd/ui/mapcontainer/PolygonDrawingInfoDialogFragmentTest.java
=> Add tests for PolygonDrawingInfoDialogFragmentTest

build.gradle, gnd/build.gradle
Add gradle dependency for Kotlin
This is a no-op change.
=> Add kotlin support

config/checkstyle/checkstyle.gradle, gnd/src/main/java/com/google/android/gnd/model/mutation/ObservationMutation.kt, gnd/src/main/java/com/google/android/gnd/util/CollectionExtensions.kt, third_party/checkstyle/google_checks.xml
Tested locally by verifying that checkstyle fails if header is missing for kotling files
Fixes the detected errors
@gino-m  PTAL?
=> Fix license header check for kotlin files

gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FirestoreDataStore.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FirestoreStorageManager.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/FeatureDocumentReference.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/ProjectDocumentReference.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/SubmissionCollectionReference.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/SubmissionConverter.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/SubmissionDocument.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/SubmissionDocumentReference.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/SubmissionMutationConverter.java, gnd/src/test/java/com/google/android/gnd/persistence/local/LocalDataStoreTest.java, gnd/src/test/java/com/google/android/gnd/persistence/remote/firestore/schema/SubmissionConverterTest.java
=> Rename Observation -> Submission references in Firestore schema

gnd/src/main/java/com/google/android/gnd/MainViewModel.kt, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FirestoreDataStore.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/FeaturesCollectionReference.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/FieldConverter.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/GroundFirestore.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/SurveyConverter.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/SurveyDocument.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/SurveyDocumentReference.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/SurveysCollectionReference.java, gnd/src/main/java/com/google/android/gnd/repository/OfflineAreaRepository.java, gnd/src/main/java/com/google/android/gnd/repository/SubmissionRepository.java, gnd/src/main/java/com/google/android/gnd/repository/SurveyRepository.kt, gnd/src/main/java/com/google/android/gnd/repository/TermsOfServiceRepository.kt, gnd/src/main/java/com/google/android/gnd/ui/common/ViewModelModule.java, gnd/src/main/java/com/google/android/gnd/ui/home/featuredetails/FeatureDetailsViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/home/featureselector/FeatureSelectorFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/PolygonDrawingViewModel.kt, gnd/src/main/java/com/google/android/gnd/util/Localization.kt, gnd/src/test/java/com/google/android/gnd/repository/SurveyRepositoryTest.java, gnd/src/test/java/com/google/android/gnd/repository/UserRepositoryTest.java
=> Rename references of "project" to "survey" in firebase schema

gnd/src/main/java/com/google/android/gnd/model/TestModelBuilders.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/JobConverter.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/JobNestedObject.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/TaskConverter.java, gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/TaskNestedObject.java, gnd/src/main/java/com/google/android/gnd/ui/editsubmission/EditSubmissionFragment.java, gnd/src/main/java/com/google/android/gnd/ui/editsubmission/EditSubmissionViewModel.java, gnd/src/test/java/com/google/android/gnd/persistence/remote/firestore/schema/FeatureConverterTest.java, gnd/src/test/java/com/google/android/gnd/persistence/remote/firestore/schema/SubmissionConverterTest.java
Towards https://github.com/google/ground-android/issues/1122
@JSunde  PTAL?
=> Rename references of "form" to "task" in firebase schema

gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/CameraUpdate.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerViewModel.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/PolygonDrawingView.java, gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/PolygonDrawingViewModel.kt
Fixes an issue where locate me does not work when drawing a polygon. 
To verify bug fix:
1. Enter polygon drawing mode
2. Tap the location lock button
screen recording of the fix:
https://user-images.githubusercontent.com/7172296/177991023-0217dc4a-59b9-44ea-a378-6dc02f3b31e2.mov
=>  Fix locate me on polygon drawing view

ground/src/main/AndroidManifest.xml, ground/src/main/java/com/google/android/ground/GroundApplication.kt, ground/src/main/java/com/google/android/ground/GroundApplicationModule.java
=> Rename GndApplication.kt and GndApplicationModule.java

build.gradle, ground/build.gradle
[GeoTools](https://www.geotools.org/) is an open source library for
processing and working with geospatial data. We'll use it to handle
geometries and geojson going forward. This is a first step toward
simplifying and improving our model of map features and locations of
interest.
=> Add GeoTools Dependency

ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionTaskFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewPagerAdapter.kt, ground/src/main/res/layout/data_collection_frag.xml, ground/src/main/res/layout/data_collection_step_frag.xml, ground/src/main/res/values/strings.xml, ground/src/test/java/com/google/android/ground/ui/datacollection/DataCollectionFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/DataCollectionTestData.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/DataCollectionViewModelTest.kt
Towards #1146
Adds a Horizontal ViewPager2 and a next button for stepping between DataCollectionTaskFragments which will contain the various steps required for the user to collect data.
=> Add ViewPager2 to DataCollectionFragment for paging between DataCollectionTaskFragments

cloud-builder/Dockerfile-base, cloud-builder/cloudbuild.yaml, cloudbuild.yaml
Fixes #1172 
Also improves the total build time by ~40s
@gino-m  PTAL?
=> Update build tools version of configured docker image

ground/src/main/java/com/google/android/ground/persistence/local/room/models/StepEntityType.java, ground/src/main/java/com/google/android/ground/persistence/remote/firestore/schema/FieldConverter.java, ground/src/main/java/com/google/android/ground/persistence/remote/firestore/schema/MultipleChoiceConverter.java, ground/src/main/java/com/google/android/ground/persistence/remote/firestore/schema/StepConverter.java, ground/src/main/java/com/google/android/ground/persistence/remote/firestore/schema/StepNestedObject.java, ground/src/main/java/com/google/android/ground/persistence/remote/firestore/schema/TaskConverter.java, ground/src/main/java/com/google/android/ground/persistence/remote/firestore/schema/TaskNestedObject.java
Towards https://github.com/google/ground-android/issues/1164
@gino-m  PTAL?
=> Rename "element" to "step"

ground/src/main/java/com/google/android/ground/persistence/remote/firestore/GeometryConverter.kt, ground/src/test/java/com/google/android/ground/persistence/remote/firestore/GeometryConverterTest.kt
Towards #929. Cleans up existing tests in the process.
@scolsen PTAL?
=> [Model] Implement Firestore map ->`Geometry` conversion

build.gradle, config/lint/lint.gradle, gradle/wrapper/gradle-wrapper.properties
This change was made using AS's tool. Also updates compile sdk version to 31
Updates gradle (and other dependencies) using Android Studio's AGP tool.
This also requires updating compile sdk version to 31.
Verified the changes by running the app locally.
@gino-m  PTAL?
=> Update compileSdkVersion and gradle plugin

ground/src/main/java/com/google/android/ground/persistence/local/room/RoomLocalDataStore.java, ground/src/main/java/com/google/android/ground/ui/editsubmission/EditSubmissionViewModel.java
Towards alpha cleanup
@gino-m  PTAL?
=> Rename obsolete usage of Obs

cloudbuild.yaml
Diable instrumentation tests for master build to prevent build from failing. 
This is temporary until the underlying issue is resolved.
@gino-m  PTAL?
=> Disable instrumentation tests

ground/src/main/java/com/google/android/ground/rx/Loadable.kt, ground/src/main/java/com/google/android/ground/rx/ValueOrError.kt
=> Replace ValueOrError with Result in Loadable

.idea/codeStyles/Project.xml, ground/src/main/java/com/google/android/ground/model/submission/Submission.java, ground/src/main/java/com/google/android/ground/persistence/local/room/entity/SubmissionEntity.java, ground/src/main/java/com/google/android/ground/persistence/remote/firestore/schema/SubmissionConverter.kt, ground/src/main/java/com/google/android/ground/repository/SubmissionRepository.kt, ground/src/main/java/com/google/android/ground/ui/editsubmission/EditSubmissionViewModel.java, ground/src/main/java/com/google/android/ground/ui/home/locationofinterestdetails/SubmissionListFragment.java, ground/src/test/java/com/google/android/ground/persistence/local/LocalDataStoreTest.java, ground/src/test/java/com/google/android/ground/persistence/remote/firestore/schema/SubmissionConverterTest.java, ground/src/test/java/com/google/android/ground/ui/datacollection/DataCollectionTestData.kt
Towards #1228
Replace with "id" of the Survey
@gino-m PTAL?
=> Remove instance of Survey from Submission model

ground/src/main/java/com/google/android/ground/persistence/remote/firestore/GeometryConverter.kt, ground/src/test/java/com/google/android/ground/persistence/remote/firestore/GeometryConverterTest.kt
=> Test GeometryConverter for `Polygon`, add Javadoc

.editorconfig
Fixes inconsistent indentation b/w ktfmt and IDE
@JSunde  PTAL?
=> Set indent size as 2 for kotlin

ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewPagerAdapter.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/QuestionDataCollectionFragment.kt, ground/src/main/res/drawable/ic_question_answer.xml, ground/src/main/res/layout/data_collection_frag.xml, ground/src/main/res/layout/edit_submission_frag.xml, ground/src/main/res/layout/fragment_terms_service.xml, ground/src/main/res/layout/offline_base_map_selector_frag.xml, ground/src/main/res/layout/offline_base_map_viewer_frag.xml, ground/src/main/res/layout/offline_base_maps_frag.xml, ground/src/main/res/layout/question_data_collection_frag.xml, ground/src/main/res/layout/settings_activity.xml, ground/src/main/res/layout/submission_details_frag.xml, ground/src/main/res/layout/sync_status_frag.xml, ground/src/main/res/navigation/nav_graph.xml, ground/src/main/res/values/colors.xml, ground/src/main/res/values/strings.xml, ground/src/main/res/values/styles.xml, ground/src/test/java/com/google/android/ground/ui/datacollection/DataCollectionFragmentTest.kt
- Added new QuestionDataCollectionFragment that is shown for TEXT type tasks
- Data persistence will be covered in a follow up change
- Tweaks to Data Collection Fragment UX
- Updated app accent color to align with mocks
Towards #1146
=> Add QuestionDataCollectionFragment

ground/src/main/java/com/google/android/ground/ui/map/LocationController.kt, ground/src/main/java/com/google/android/ground/ui/map/MapController.kt, ground/src/test/java/com/google/android/ground/ui/map/LocationControllerTest.kt, ground/src/test/java/com/google/android/ground/ui/map/MapControllerTest.kt
Adds tests for controllers added in https://github.com/google/ground-android/pull/1296
@scolsen @JSunde  PTAL?
=> Add unit tests for map and location controller

ground/src/main/java/com/google/android/ground/model/geometry/Coordinate.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/LoiCardSource.kt, ground/src/main/java/com/google/android/ground/ui/map/ConverterExt.kt, ground/src/main/java/com/google/android/ground/ui/map/MapController.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/GoogleMapsFragment.kt, ground/src/test/java/com/google/android/ground/ui/map/MapControllerTest.kt
=> [Bug] Convert LatLng to Point correctly

ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/LoiCardAdapter.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/MapContainerFragment.kt
Towards #1153 
https://user-images.githubusercontent.com/8918023/193992483-cc1dab49-f030-4505-b9cf-95495568f53a.mp4
=> [Bottom Card] Auto-select middle LOI card on scroll

ground/src/main/java/com/google/android/ground/ui/common/AbstractFragment.kt, ground/src/main/java/com/google/android/ground/ui/home/HomeScreenFragment.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/MapContainerFragment.kt, ground/src/main/res/layout/home_screen_frag.xml
Steps to reproduce:
* Open the app
* Wait for the map to load
* Rotate the screen
=> Fix crash on rotate by removing manual save/restore of map fragment

ground/src/main/java/com/google/android/ground/ui/map/CameraPosition.kt, ground/src/test/java/com/google/android/ground/ui/map/CameraPositionTest.kt
=> Preserve bounds when loading position from local preferences

ground/src/main/res/drawable/launch_screen.xml, ground/src/main/res/layout/startup_frag.xml
This fixes the logo not appearing at the startup
@JSunde PTAL?
=> Fix typo in launch screen

ground/src/main/java/com/google/android/ground/model/submission/TaskData.kt, ground/src/main/java/com/google/android/ground/ui/home/locationofinterestdetails/SubmissionListItemViewHolder.java
=> Remove redundant getSummaryText()

ground/build.gradle, ground/src/main/java/com/google/android/ground/model/task/Task.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt, ground/src/main/java/com/google/android/ground/util/LiveDataExtensions.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/DataCollectionFragmentTest.kt, sharedTest/src/main/java/com/sharedtest/FakeData.kt
=> Persist TaskData when user presses continue on final Task in Job

ground/src/main/java/com/google/android/ground/ui/datacollection/QuestionDataCollectionFragment.kt
=> Remove obsolete TODOS in QuestionDataCollectionFragment

ground/src/main/java/com/google/android/ground/model/job/Job.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/LoiCardAdapter.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/MapContainerFragment.kt, ground/src/main/res/layout/loi_card_item.xml, ground/src/main/res/values/strings.xml
=> Update UX for LOI cards

ground/src/main/res/layout/data_collection_header.xml, ground/src/main/res/layout/multiple_choice_data_collection_frag.xml
=> Use new Data Collection Header component in Multiple Choice Task

ground/build.gradle
Adds Gson since it is used in our impl but it has so far only been imported transitively. 
=> Add missing Gson dep

config/lint/lint.xml, ground/src/main/java/com/google/android/ground/ui/common/AbstractMapViewModel.kt, ground/src/main/res/drawable/ic_gps_lock_not_fixed.xml, ground/src/main/res/layout/basemap_layout.xml
Fixes #1378
Switch location lock icon based on lock state.
@gino-m  PTAL?
=> Add icon for location lock "not_fixed" state

ground/src/main/java/com/google/android/ground/persistence/sync/MutationSyncWorkManager.kt, ground/src/main/java/com/google/android/ground/persistence/sync/PhotoSyncWorkManager.kt, ground/src/main/java/com/google/android/ground/persistence/sync/SyncService.kt, ground/src/main/java/com/google/android/ground/persistence/sync/TileSetDownloadWorkManager.kt, ground/src/main/java/com/google/android/ground/repository/LocationOfInterestRepository.kt, ground/src/main/java/com/google/android/ground/repository/SubmissionRepository.kt, ground/src/test/java/com/google/android/ground/repository/LocationOfInterestRepositoryTest.kt
=> [Code health] Renamed data sync worker classes

ground/src/main/java/com/google/android/ground/ui/home/HomeScreenFragment.kt, ground/src/main/java/com/google/android/ground/ui/home/HomeScreenViewModel.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt
=> [Code Health] Cleanup remaining usages of LoiRepositionViewModel

ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/LoiCardAdapter.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/LoiCardViewModel.kt, ground/src/main/res/layout/loi_card_item.xml, ground/src/test/java/com/google/android/ground/ui/home/mapcontainer/LoiCardViewModelTest.kt
=> Move xml logic for LoiCard to view model

ground/src/main/java/com/google/android/ground/ui/common/AbstractMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/common/AbstractMapViewModel.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/offlinebasemap/selector/OfflineAreaSelectorFragment.kt, ground/src/main/java/com/google/android/ground/ui/offlinebasemap/selector/OfflineAreaSelectorViewModel.kt, ground/src/main/java/com/google/android/ground/ui/offlinebasemap/viewer/OfflineAreaViewerFragment.kt, ground/src/main/java/com/google/android/ground/ui/offlinebasemap/viewer/OfflineAreaViewerViewModel.kt
=> [UI] Fix failing offline fragments

ground/build.gradle
=> Remove unused var in build.gradle

ground/src/main/java/com/google/android/ground/ui/home/HomeScreenFragment.kt, ground/src/main/java/com/google/android/ground/ui/home/HomeScreenViewModel.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/PolygonDrawingMapViewModel.kt, ground/src/main/res/layout/map_container_frag.xml
Towards #1351
This PR aims at removing current usages of PolygonDrawingView and move reusable code to a new VM. This is in preparation for adding support to draw polygon with data collection flow
@JSunde  PTAL?
=> [Cleanup] Remove usages of PolygonDrawingView and PolygonDrawingViewModel

ground/build.gradle, ground/src/main/java/com/google/android/ground/persistence/sync/SurveySyncService.kt, ground/src/main/java/com/google/android/ground/persistence/sync/SurveySyncWorker.kt, ground/src/main/java/com/google/android/ground/persistence/sync/SyncService.kt, ground/src/main/java/com/google/android/ground/repository/SurveyRepository.kt, ground/src/test/java/com/google/android/ground/persistence/sync/SurveySyncServiceTest.kt, ground/src/test/java/com/google/android/ground/persistence/sync/SurveySyncWorkerTest.kt
=> Add worker and service for syncing survey in background

ground/src/main/java/com/google/android/ground/persistence/local/LocalValueStore.kt, ground/src/main/java/com/google/android/ground/repository/MapsRepository.kt, ground/src/main/java/com/google/android/ground/ui/map/LocationController.kt, ground/src/test/java/com/google/android/ground/repository/MapsRepositoryTest.kt, ground/src/test/java/com/google/android/ground/ui/map/LocationControllerTest.kt
=> Persist location lock state across flows

ground/src/main/java/com/google/android/ground/repository/LocationOfInterestRepository.kt, ground/src/main/java/com/google/android/ground/ui/home/HomeScreenFragment.kt, ground/src/main/java/com/google/android/ground/ui/home/HomeScreenViewModel.kt, ground/src/main/res/layout/location_of_interest_details_chrome.xml, ground/src/main/res/navigation/nav_graph.xml, ground/src/test/java/com/google/android/ground/repository/LocationOfInterestRepositoryTest.kt
=> Remove logic related to adding LOIs

build.gradle, ground/build.gradle, ground/src/main/java/com/google/android/ground/ui/home/locationofinterestselector/LocationOfInterestSelectorFragment.java, ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorDialogFragment.java
Fixes #1292 
With migration to Kotlin, this isn't useful anymore.
@scolsen PTAL?
=> Remove nullness gradle plugin

ground/src/main/java/com/google/android/ground/repository/SurveyRepository.kt
=> Cleanup attachJobPermissions method

ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt, ground/src/main/res/layout/loi_card_item.xml
Fixes #1454 
@gino-m @JSunde   PTAL?
=> [BottomCards] Use PagerSnapHelper to snap to center card

build.gradle, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt
=> Upgrade ktfmt plugin to latest (0.11.0)

ground/src/test/java/com/google/android/ground/TestCoroutineDispatchersModule.kt, ground/src/test/java/com/google/android/ground/TestCoroutineScopesModule.kt, ground/src/test/java/com/google/android/ground/repository/SurveyRepositoryTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/DataCollectionFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/surveyselector/SurveySelectorFragmentTest.kt
Also removes some unused injected deps in the process.
=> [Code health] Make injection of TestDispatchers explicit

ground/src/androidTest/java/com/google/android/ground/AcceptTermsOfServiceTest.kt, ground/src/test/java/com/google/android/ground/MainViewModelTest.kt, ground/src/test/java/com/google/android/ground/repository/SurveyRepositoryTest.kt, ground/src/test/java/com/google/android/ground/repository/TermsOfServiceRepositoryTest.kt, sharedTest/src/main/kotlin/com/sharedtest/persistence/remote/FakeRemoteDataStore.kt
=> [Code health] Make FakeRemoteDataStore more realistic and idiomatic

ground/src/androidTest/java/com/google/android/ground/TestSharedPreferencesModule.kt, ground/src/main/java/com/google/android/ground/persistence/local/SharedPreferencesModule.kt, ground/src/test/java/com/google/android/ground/persistence/local/TestSharedPreferencesModule.kt
Fixes #1518 
@JSunde @scolsen or @shobhitagarwal1612 PTAL?
=> [Bug] Isolate shared prefs in tests

ground/src/main/java/com/google/android/ground/repository/OfflineAreaRepository.kt, ground/src/main/java/com/google/android/ground/repository/SubmissionRepository.kt, ground/src/main/java/com/google/android/ground/repository/TermsOfServiceRepository.kt, ground/src/main/java/com/google/android/ground/repository/UserRepository.kt
=> [Potential bug] Add missing @Singleton declarations to Repositories

ground/src/main/java/com/google/android/ground/model/locationofinterest/LocationOfInterest.kt
=> Add geometry to LOI mutations

ground/src/main/res/layout/submission_details_frag.xml, ground/src/main/res/layout/submission_list_item.xml
This was recommended by Android Studio. @scolsen PTAL?
=> [Code health] Move xml namespace declarations to start of file

ground/src/main/java/com/google/android/ground/ui/home/HomeScreenFragment.kt, ground/src/main/res/menu/nav_drawer_menu.xml, ground/src/main/res/values/strings.xml
Now that the actual data collection flow has been integrated, we don't need this.
This is a no-op change. Doesn't require any extra validation steps.
@JSunde PTAL?
=> Cleanup test data collection flow entrypoint

ground/src/main/java/com/google/android/ground/model/job/Job.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/fields/TaskEntityType.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/TaskConverter.kt, ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorViewModel.kt
Towards #1545
Verified by creating a new job with name "All tasks" and validating that a fragment is created for each task.
@JSunde  PTAL?
=> [Data Collection] Fix mapping for task type in local db

build.gradle, config/detekt/detekt.yml, ground/src/main/java/com/google/android/ground/model/submission/MultipleChoiceTaskData.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/entity/GeometryWrapper.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/GeometryConverter.kt, ground/src/main/java/com/google/android/ground/repository/SubmissionRepository.kt, ground/src/main/java/com/google/android/ground/ui/common/AbstractView.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/PolygonDrawingViewModel.kt, ground/src/main/java/com/google/android/ground/ui/editsubmission/AddPhotoDialogAdapter.kt, ground/src/main/java/com/google/android/ground/ui/editsubmission/PhotoTaskViewModel.kt, ground/src/main/java/com/google/android/ground/ui/home/BottomSheetMetrics.kt, ground/src/main/java/com/google/android/ground/ui/home/HomeScreenFragment.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/FeatureClusterManager.kt, ground/src/test/java/com/google/android/ground/MainViewModelTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/PolygonDrawingTaskFragmentModelTest.kt, ground/src/test/java/com/google/android/ground/ui/map/gms/FeatureClusterManagerTest.kt
Fixes #1560 
There are still a ton of configs that can be enabled. But I'm leaving them in favor of keeping this PR small.
@gino-m PTAL?
=> Integrate Detekt plugin

ground/src/main/java/com/google/android/ground/repository/SubmissionRepository.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt, ground/src/main/java/com/google/android/ground/ui/editsubmission/EditSubmissionViewModel.java, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt, ground/src/main/res/navigation/nav_graph.xml, ground/src/test/java/com/google/android/ground/ui/datacollection/DataCollectionFragmentTest.kt
Fixes #1574 
Correctly bind the submission id and cleanup used jobId param. Also replaces `Loadable<Submission>` with `Submission` to simplify the code.
@JSunde  PTAL?
=> Fix data collection flow

config/detekt/detekt.yml, ground/src/main/java/com/google/android/ground/persistence/local/room/entity/GeometryWrapper.kt, ground/src/main/java/com/google/android/ground/util/LiveDataExtensions.kt
Towards https://github.com/google/ground-android/issues/1580
Split from https://github.com/google/ground-android/pull/1570
@JSunde  PTAL?
=> [Code health] Enforce kotlin comments formatting

config/detekt/detekt.yml, ground/src/main/java/com/google/android/ground/persistence/local/room/converter/ConverterExt.kt, ground/src/main/java/com/google/android/ground/ui/common/AbstractFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionFragment.kt, ground/src/main/java/com/google/android/ground/ui/home/HomeScreenFragment.kt, ground/src/main/java/com/google/android/ground/ui/offlinebasemap/selector/OfflineAreaSelectorFragment.kt, ground/src/main/java/com/google/android/ground/ui/offlinebasemap/viewer/OfflineAreaViewerFragment.kt, ground/src/main/java/com/google/android/ground/ui/submissiondetails/SubmissionDetailsFragment.kt, ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorFragment.kt
Towards https://github.com/google/ground-android/issues/1580
Split from https://github.com/google/ground-android/pull/1570
https://detekt.dev/docs/rules/potential-bugs/#casttonullabletype
@JSunde PTAL?
=> [Code Health] Detect anti-pattern of casting to nullable types

ground/src/main/java/com/google/android/ground/ui/datacollection/DropAPinTaskFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/PolygonDrawingTaskFragment.kt
Fixes #1610
Initialises map type tasks using position
@JSunde  PTAL?
=> [Regression] Initialise VM for map type tasks

ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorViewModel.kt, ground/src/test/java/com/google/android/ground/ui/surveyselector/SurveySelectorFragmentTest.kt
=> Order surveys in the selector by offline availability

ground/src/main/java/com/google/android/ground/persistence/local/LocalDatabaseModule.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/dao/SurveyDao.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomSurveyStore.kt, ground/src/main/java/com/google/android/ground/persistence/local/stores/LocalSurveyStore.kt, ground/src/main/java/com/google/android/ground/repository/SurveyRepository.kt, ground/src/test/java/com/google/android/ground/persistence/local/LocalDataStoreTests.kt
First step towards migrating local db layer to Coroutines (#1581).
@JSunde PTAL?
=> Migrate fetch of surveys from local db to Coroutines Flow

ground/src/androidTest/java/com/google/android/ground/TestSchedulersModule.kt, ground/src/main/java/com/google/android/ground/MainViewModel.kt, ground/src/main/java/com/google/android/ground/domain/usecases/survey/ReactivateLastSurveyUseCase.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomUserStore.kt, ground/src/main/java/com/google/android/ground/persistence/local/stores/LocalUserStore.kt, ground/src/main/java/com/google/android/ground/repository/SurveyRepository.kt, ground/src/main/java/com/google/android/ground/repository/UserRepository.kt, ground/src/test/java/com/google/android/ground/MainViewModelTest.kt, ground/src/test/java/com/google/android/ground/TestSchedulersModule.kt, ground/src/test/java/com/google/android/ground/domain/usecase/ReactivateLastSurveyUseCaseTest.kt, sharedTest/src/main/kotlin/com/sharedtest/TestSchedulers.kt
Fixes #1612.
@scolsen and/or @shobhitagarwal1612 PTAL?
=> Reactivate last survey on sign in

ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionFragment.kt, ground/src/main/res/layout/data_collection_frag.xml
Towards https://github.com/google/ground-android/issues/1621
Adds a progress bar for representing the current task count
[Design Doc](https://docs.google.com/document/d/15CGT-9LvgarzBvrC8kPPAEHlrGuZCqVL0i9lpmya2dU/r/0-OLrHylzybpz6_mkioEm7og/edit#)
[Figma Mocks](https://www.figma.com/file/r2uGtyOiWoDa29za7DNuUc/Ground-Acacia-UX?node-id=1566%3A47266&t=dG3k5Uq9xfJLrC3s-0)
@scolsen @JSunde PTAL?
=> [Data Collection] Add a progress view for showing current progress 

ground/build.gradle, ground/src/main/java/com/google/android/ground/model/submission/MultipleChoiceTaskData.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/components/TaskButton.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskViewModel.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/date/DateTaskFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/time/TimeTaskFragment.kt, ground/src/test/java/com/google/android/ground/CustomViewActions.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/DataCollectionFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/NavControllerTestUtil.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/BaseTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/date/DateTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/number/NumberTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/point/DropAPinTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/polygon/PolygonDrawingTaskFragmentModelTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/text/TextTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/time/TimeTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragmentTest.kt
Fixes #1621 
This is the last PR for revamping UI for data collection tasks. Remaining P2 improvements will be tracked separately in their own bug and will be taken up separately after all other P1 are resolved.
@scolsen @JSunde  PTAL?
=> Add unit tests for data collection tasks

ground/src/main/java/com/google/android/ground/persistence/local/stores/LocalLocationOfInterestStore.kt, ground/src/main/java/com/google/android/ground/persistence/local/stores/LocalMutationStore.kt, ground/src/main/java/com/google/android/ground/persistence/local/stores/SubmissionStore.kt
=> Renamed MutationStore -> LocalMutationStore

ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorFragment.kt, ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorViewModel.kt, ground/src/main/res/values/strings.xml
=> Display a progress dialog when activating a survey

ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/point/DropAPinTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/polygon/PolygonDrawingTaskFragmentTest.kt
* Clicking task header should open a popup with task label
* Unit tests for polygon drawing task
@JSunde  PTAL?
=> Add more unit test coverage

ground/src/main/java/com/google/android/ground/MainViewModel.kt, ground/src/main/java/com/google/android/ground/repository/TermsOfServiceRepository.kt, ground/src/test/java/com/google/android/ground/MainViewModelTest.kt, ground/src/test/java/com/google/android/ground/repository/TermsOfServiceRepositoryTest.kt, sharedTest/src/main/kotlin/com/sharedtest/persistence/remote/FakeRemoteDataStore.kt
Fixes #1666 
@JSunde @gino-m  PTAL?
=> Prevent app crash when offline

ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskFragment.kt, ground/src/main/res/color/task_dark_green_btn_selector.xml, ground/src/main/res/color/task_light_green_btn_selector.xml, ground/src/main/res/color/task_transparent_btn_selector.xml, ground/src/main/res/drawable/task_dark_green_btn_selector.xml, ground/src/main/res/drawable/task_transparent_btn_selector.xml, ground/src/main/res/layout/task_frag_with_header.xml, ground/src/main/res/values-night/colors.xml, ground/src/main/res/values/colors.xml, ground/src/main/res/values/styles.xml
I also made some UX tweaks to bring the Task buttons in line with the mocks.
=> Clear Multiple Choice selection when user skips the task

ground/src/main/java/com/google/android/ground/ui/map/MapFragment.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/GoogleMapsFragment.kt, ground/src/main/java/com/google/android/ground/ui/offlinebasemap/selector/OfflineAreaSelectorFragment.kt
=> Rename "remote tile sets" to "web tile sets"

build.gradle, config/detekt/baseline.xml, config/detekt/detekt.yml, ground/src/main/java/com/google/android/ground/domain/usecases/submission/SubmitDataUseCase.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/converter/ResponseJsonConverter.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/LoiMutationConverter.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionMutationConverter.kt, ground/src/main/java/com/google/android/ground/persistence/sync/TileSetDownloadWorker.kt, ground/src/main/java/com/google/android/ground/repository/OfflineAreaRepository.kt, ground/src/main/java/com/google/android/ground/repository/UserMediaRepository.kt, ground/src/main/java/com/google/android/ground/system/GoogleApiManager.kt, ground/src/main/java/com/google/android/ground/system/NotificationManager.kt, ground/src/main/java/com/google/android/ground/system/PermissionsManager.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/map/MapType.kt, ground/src/main/java/com/google/android/ground/ui/util/BitmapUtil.kt, ground/src/main/java/com/google/android/ground/ui/util/FileUtil.kt, ground/src/test/java/com/google/android/ground/CustomViewActions.kt, ground/src/test/java/com/google/android/ground/UiTestHelper.kt
Routine task
This new [release](https://github.com/detekt/detekt/releases) also adds a bunch of new rules and bug fixes for existing ones.
=> Update detekt plugin to 1.23.0

ground/src/main/java/com/google/android/ground/repository/UserRepository.kt, ground/src/main/java/com/google/android/ground/system/auth/GoogleAuthenticationManager.kt, ground/src/main/java/com/google/android/ground/ui/home/HomeScreenFragment.kt, ground/src/main/java/com/google/android/ground/ui/signin/SignInViewModel.kt, ground/src/main/java/com/google/android/ground/ui/startup/StartupFragment.kt
=> Access AuthenticationManager via UserRepository in fragments

ground/src/main/java/com/google/android/ground/model/geometry/Geometry.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/FeatureClusterItem.kt
=> Add method center() to geometry instead of always using the first vertex

ground/src/main/java/com/google/android/ground/domain/usecases/submission/SubmitDataUseCase.kt, ground/src/main/java/com/google/android/ground/model/submission/DateTaskData.kt, ground/src/main/java/com/google/android/ground/model/submission/GeometryData.kt, ground/src/main/java/com/google/android/ground/model/submission/MultipleChoiceTaskData.kt, ground/src/main/java/com/google/android/ground/model/submission/NumberTaskData.kt, ground/src/main/java/com/google/android/ground/model/submission/TaskDataDelta.kt, ground/src/main/java/com/google/android/ground/model/submission/TaskDataMap.kt, ground/src/main/java/com/google/android/ground/model/submission/TextTaskData.kt, ground/src/main/java/com/google/android/ground/model/submission/TimeTaskData.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/converter/ResponseDeltasConverter.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/converter/ResponseJsonConverter.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/converter/ResponseMapConverter.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionConverter.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionMutationConverter.kt, ground/src/main/java/com/google/android/ground/persistence/sync/LocalMutationSyncWorker.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskViewModel.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/date/DateTaskViewModel.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/point/DropAPinTaskViewModel.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/PolygonDrawingViewModel.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/time/TimeTaskViewModel.kt, ground/src/main/java/com/google/android/ground/ui/editsubmission/EditSubmissionViewModel.java, ground/src/main/java/com/google/android/ground/ui/submissiondetails/SubmissionDetailsFragment.kt, ground/src/test/java/com/google/android/ground/persistence/local/LocalDataStoreTests.kt, ground/src/test/java/com/google/android/ground/persistence/local/room/converter/ResponseJsonConverterTest.kt, ground/src/test/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionMutationConverterTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/BaseTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/editsubmission/DateTaskViewModelTest.kt, ground/src/test/java/com/google/android/ground/ui/editsubmission/TimeTaskViewModelTest.kt
Fixes #1735
This PR aims at replacing usages of `Optional<TaskData>` with `TaskData?`. This 
@JSunde @gino-m  PTAL?
=> [Code health] Replace Optional<TaskData> with TaskData?

ground/src/main/java/com/google/android/ground/MainViewModel.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/dao/BaseDao.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/dao/UserDao.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomSurveyStore.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomUserStore.kt, ground/src/main/java/com/google/android/ground/persistence/local/stores/LocalSurveyStore.kt, ground/src/main/java/com/google/android/ground/persistence/local/stores/LocalUserStore.kt, ground/src/main/java/com/google/android/ground/repository/SurveyRepository.kt, ground/src/main/java/com/google/android/ground/repository/UserRepository.kt, ground/src/test/java/com/google/android/ground/MainViewModelTest.kt, ground/src/test/java/com/google/android/ground/persistence/local/LocalDataStoreTests.kt, ground/src/test/java/com/google/android/ground/repository/LocationOfInterestRepositoryTest.kt, ground/src/test/java/com/google/android/ground/repository/UserRepositoryTest.kt
Towards #1581 
Verified by running the app locally and verifying that user details are correctly shown in the navigation drawer.
=> [Rx -> Coroutine Migration] : Use coroutine for get/set user in local db

ground/src/main/java/com/google/android/ground/model/AuditInfo.kt, ground/src/main/java/com/google/android/ground/model/Survey.kt, ground/src/main/java/com/google/android/ground/model/job/Job.kt, ground/src/main/java/com/google/android/ground/model/submission/TaskDataMap.kt, ground/src/main/java/com/google/android/ground/model/task/MultipleChoice.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/converter/ConverterExt.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/converter/ResponseDeltasConverter.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/converter/ResponseMapConverter.kt, ground/src/main/java/com/google/android/ground/persistence/mbtiles/MbtilesFootprintParser.kt, ground/src/main/java/com/google/android/ground/persistence/mbtiles/TileSetJson.kt, ground/src/main/java/com/google/android/ground/persistence/remote/DataStoreException.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/AuditInfoConverter.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/JobConverter.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/LoiConverter.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionConverter.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/TaskConverter.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt, ground/src/main/java/com/google/android/ground/ui/editsubmission/EditSubmissionViewModel.java, ground/src/main/java/com/google/android/ground/ui/home/locationofinterestdetails/SubmissionListItemViewHolder.java, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/submissiondetails/SubmissionDetailsFragment.kt, ground/src/test/java/com/google/android/ground/persistence/local/LocalDataStoreTests.kt, ground/src/test/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionLocalDataStoreConverterTest.kt
Fixes https://github.com/google/ground-android/issues/1735
Replace usages of Optional<*> with kotlin nullable wherever possible. This doesn't remove all occurences of it since RxJava code still relies on it (null value throws an error).
@JSunde @gino-m  PTAL?
=> [Code health] Replace Optional with Kotlin nullable (?)

ground/src/main/java/com/google/android/ground/persistence/local/room/dao/BaseDao.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/dao/LocationOfInterestDao.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/dao/LocationOfInterestMutationDao.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/dao/SubmissionMutationDao.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomLocationOfInterestStore.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomSubmissionStore.kt, ground/src/main/java/com/google/android/ground/persistence/local/stores/LocalLocationOfInterestStore.kt, ground/src/main/java/com/google/android/ground/persistence/local/stores/LocalMutationStore.kt, ground/src/main/java/com/google/android/ground/persistence/local/stores/LocalSubmissionStore.kt, ground/src/main/java/com/google/android/ground/persistence/sync/LocalMutationSyncWorker.kt, ground/src/main/java/com/google/android/ground/repository/MutationRepository.kt, ground/src/test/java/com/google/android/ground/persistence/local/LocalDataStoreTests.kt
Towards https://github.com/google/ground-android/issues/1581
Verified changes by submitting data and confirming that it is getting written to firestore
@JSunde @gino-m PTAL?
=> [Rx -> Coroutine]: Migrate deleteLoi and findLoi to coroutine

ground/src/main/java/com/google/android/ground/rx/RxCompletable.kt, ground/src/main/java/com/google/android/ground/rx/RxTask.kt, ground/src/main/java/com/google/android/ground/system/LocationManager.kt, ground/src/main/java/com/google/android/ground/system/PermissionsManager.kt, ground/src/main/java/com/google/android/ground/system/SettingsManager.kt, ground/src/main/java/com/google/android/ground/system/rx/RxFusedLocationProviderClient.kt, ground/src/main/java/com/google/android/ground/system/rx/RxSettingsClient.kt, ground/src/main/java/com/google/android/ground/ui/common/BaseMapViewModel.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/photo/PhotoTaskFragment.kt, ground/src/test/java/com/google/android/ground/system/PermissionsManagerTest.kt
Towards #1851
Verified the changes by manually triggering camera and location updates in the app.
@... PTAL?
=> [Rx -> Coroutine] : Migrate PermissionsManager, LocationManager and LocationManager to coroutine

ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomOfflineAreaStore.kt, ground/src/main/java/com/google/android/ground/persistence/local/stores/LocalOfflineAreaStore.kt, ground/src/main/java/com/google/android/ground/repository/OfflineAreaRepository.kt, ground/src/main/java/com/google/android/ground/system/GeocodingManager.kt, ground/src/main/java/com/google/android/ground/system/SystemModule.kt, ground/src/main/java/com/google/android/ground/ui/common/AbstractMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/map/Bounds.kt, ground/src/main/java/com/google/android/ground/ui/offlinebasemap/selector/OfflineAreaSelectorFragment.kt, ground/src/main/java/com/google/android/ground/ui/offlinebasemap/selector/OfflineAreaSelectorViewModel.kt, ground/src/main/res/values-es/strings.xml, ground/src/main/res/values-pt/strings.xml, ground/src/main/res/values/strings.xml, ground/src/test/java/com/google/android/ground/system/GeocodingManagerTest.kt
Towards #1715.
Also deletes a few unused method and converts key functions to suspend functions in the process.
=> Generate human-readable name for downloaded offline map imagery

ground/src/main/java/com/google/android/ground/domain/usecases/survey/ActivateSurveyUseCase.kt, ground/src/main/java/com/google/android/ground/domain/usecases/survey/MakeSurveyAvailableOfflineUseCase.kt, ground/src/main/java/com/google/android/ground/domain/usecases/survey/SyncSurveyUseCase.kt, ground/src/main/java/com/google/android/ground/persistence/remote/RemoteDataStore.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/FirestoreDataStore.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/SurveyDocumentReference.kt, ground/src/main/java/com/google/android/ground/repository/SurveyRepository.kt, ground/src/test/java/com/google/android/ground/domain/usecase/ActivateSurveyUseCaseTest.kt, ground/src/test/java/com/google/android/ground/domain/usecase/MakeSurveyAvailableOfflineUseCaseTest.kt, ground/src/test/java/com/google/android/ground/domain/usecase/SyncSurveyUseCaseTest.kt, ground/src/test/java/com/google/android/ground/repository/SurveyRepositoryTest.kt, sharedTest/src/main/kotlin/com/sharedtest/persistence/remote/FakeRemoteDataStore.kt
Fixes #1763. Also migrated several functions to Coroutines and tweaked readability in the process.
=> Fix force quit on survey load when opened in offline mode

ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/point/DropAPinMapFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/point/LatLngConverter.kt, ground/src/test/java/com/google/android/ground/model/geometry/GeometryValidatorTest.kt, ground/src/test/java/com/google/android/ground/persistence/local/LocalDataStoreTests.kt, ground/src/test/java/com/google/android/ground/persistence/local/room/converter/GeometryTest.kt, ground/src/test/java/com/google/android/ground/persistence/local/room/converter/ResponseJsonConverterTest.kt, ground/src/test/java/com/google/android/ground/persistence/remote/firebase/schema/GeometryConverterTest.kt, ground/src/test/java/com/google/android/ground/persistence/remote/firebase/schema/GeometryModelToLocalDbConverterTest.kt, ground/src/test/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionLocalDataStoreConverterTest.kt, ground/src/test/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionMutationConverterTest.kt, ground/src/test/java/com/google/android/ground/repository/LocationOfInterestRepositoryTest.kt, ground/src/test/java/com/google/android/ground/system/GeocodingManagerTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/point/DropAPinTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/point/LatLngConverterTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/polygon/PolygonDrawingTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/polygon/PolygonDrawingViewModelTest.kt, ground/src/test/java/com/google/android/ground/ui/map/CameraPositionTest.kt, ground/src/test/java/com/google/android/ground/ui/map/MapControllerTest.kt, ground/src/test/java/com/google/android/ground/ui/map/gms/mog/MogSourceTest.kt
=> Replace remaining instances of `Coordinate`

ground/src/test/java/com/google/android/ground/persistence/local/room/converter/GeometryTest.kt, ground/src/test/java/com/google/android/ground/persistence/remote/firebase/schema/GeometryConverterTest.kt, ground/src/test/java/com/google/android/ground/system/GeocodingManagerTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/point/LatLngConverterTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/polygon/PolygonDrawingTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/polygon/PolygonDrawingViewModelTest.kt
Fixes #1775. Bizarre that the compile was misreporting this error.. 😕
=> Fix compile errors in tests

ground/src/main/java/com/google/android/ground/Config.kt, ground/src/main/java/com/google/android/ground/persistence/local/LocalValueStore.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/converter/ConverterExt.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/entity/TileSourceEntity.kt, ground/src/main/java/com/google/android/ground/repository/MapStateRepository.kt, ground/src/main/java/com/google/android/ground/ui/common/AbstractMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/common/BaseMapViewModel.kt, ground/src/main/java/com/google/android/ground/ui/common/MapConfig.kt, ground/src/main/java/com/google/android/ground/ui/common/ViewModelModule.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/MapTypeDialogFragment.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/MapTypeViewModel.kt, ground/src/main/java/com/google/android/ground/ui/map/Map.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/GoogleMapsFragment.kt, ground/src/main/java/com/google/android/ground/ui/offlinebasemap/selector/OfflineAreaSelectorFragment.kt, ground/src/main/java/com/google/android/ground/ui/offlinebasemap/selector/OfflineAreaSelectorViewModel.kt, ground/src/main/java/com/google/android/ground/ui/offlinebasemap/viewer/OfflineAreaViewerFragment.kt, ground/src/main/java/com/google/android/ground/ui/offlinebasemap/viewer/OfflineAreaViewerViewModel.kt, ground/src/main/res/layout/map_type_dialog_fragment.xml, ground/src/test/java/com/google/android/ground/repository/MapStateRepositoryTest.kt
Fixes #1782
Things done: 
* Fix mapping of source tile type when storing to local db
* Add method to clear tile overlays in GoogleMapFragment
* Create a new preference for displaying offline imagery
* Move the tileOverlay binding from HomeScreen to base fragment. Also create a config to disable overlay when needed.
https://github.com/google/ground-android/assets/8918023/54c5d947-527c-4a57-99f1-9e92161b274d
@gino-m  PTAL?
=> [Offline Map] Configure the toggle button to enable/disable basemap tile overlay in home screen and task views

ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionFragment.kt
Fixes #1794
https://github.com/google/ground-android/assets/9056308/76454515-d849-49bc-a70d-ef17c391359f
=> Animate progress bar changes in data collection flow

ground/src/main/java/com/google/android/ground/persistence/remote/RemoteDataStore.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/FirestoreDataStore.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/base/FluentCollectionReference.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/SurveysCollectionReference.kt, ground/src/main/java/com/google/android/ground/repository/SurveyRepository.kt, ground/src/main/java/com/google/android/ground/system/NetworkManager.kt, ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorFragment.kt, ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorViewModel.kt, ground/src/test/java/com/google/android/ground/repository/SurveyRepositoryTest.kt, ground/src/test/java/com/google/android/ground/ui/surveyselector/SurveySelectorFragmentTest.kt, sharedTest/src/main/kotlin/com/sharedtest/persistence/remote/FakeRemoteDataStore.kt
=> [Survey List] Show offline surveys when network is not available

config/detekt/detekt.yml, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt
=> Only show Suggest LOI job cards when zoomed in

ground/src/main/java/com/google/android/ground/model/geometry/Geometry.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/LoiMutationConverter.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/PolygonDrawingTaskFragment.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/ConverterExt.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/GmsExt.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/GoogleMapsFragment.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/renderer/FeatureRenderer.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/renderer/PolygonRenderer.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/renderer/PolylineRenderer.kt, ground/src/test/java/com/google/android/ground/persistence/local/LocalDataStoreTests.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/polygon/PolygonDrawingViewModelTest.kt
Fixes #1736
Verified the changes locally that bounds are getting computed correctly and polyline/polygons are being rendered as well.
@gino-m @JSunde   PTAL?
=> Replace usages of `Geometry.vertices` with appropriate fields on each subclass

ground/src/main/res/drawable/offline_area_viewport_outline.xml, ground/src/main/res/layout/offline_base_map_selector_frag.xml, ground/src/main/res/values/colors.xml
Towards #1822 
[Screen_recording_20230908_150736.webm](https://github.com/google/ground-android/assets/228050/4a59bda2-16ff-4c4f-a9ca-11cd549278f9)
@JSunde PTAL?
@vittorino FYI
=> Add  mask and outline to offline area map selector

ground/src/main/java/com/google/android/ground/ui/common/AbstractMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/common/MapConfig.kt, ground/src/main/java/com/google/android/ground/ui/offlinebasemap/selector/OfflineAreaSelectorFragment.kt, ground/src/main/java/com/google/android/ground/ui/offlinebasemap/selector/OfflineAreaSelectorViewModel.kt, ground/src/main/java/com/google/android/ground/ui/offlinebasemap/viewer/OfflineAreaViewerFragment.kt
Introduce a new config `overrideMapType` in MapConfig and use ROAD type for offline fragment
@gino-m PTAL?
=> Use ROAD map type in Offline Fragment

ground/src/main/java/com/google/android/ground/ui/offlinebasemap/selector/DownloadProgressDialogFragment.kt
Workaround for #1860 until we implement our own download dialog
=> Disable tap outside offline area download dialog

ground/src/main/java/com/google/android/ground/repository/LocationOfInterestRepository.kt, ground/src/main/java/com/google/android/ground/ui/common/AbstractMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/common/BaseMapViewModel.kt, ground/src/main/java/com/google/android/ground/ui/common/MapConfig.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt, ground/src/main/java/com/google/android/ground/ui/offlineareas/OfflineAreaListAdapter.kt, ground/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorFragment.kt, ground/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorViewModel.kt, ground/src/main/java/com/google/android/ground/ui/offlineareas/viewer/OfflineAreaViewerFragment.kt, ground/src/main/java/com/google/android/ground/ui/offlineareas/viewer/OfflineAreaViewerViewModel.kt, ground/src/test/java/com/google/android/ground/repository/LocationOfInterestRepositoryTest.kt
This reverts commit 779c72ebbfbd5c7d3627eb8dac5516f92e22149f
@gino-m @shobhitagarwal1612  PTAL
=> Revert "[Refactor] Simplify home screen features and cards update logic (#1857)"

ground/src/main/java/com/google/android/ground/ui/common/AbstractMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/common/BaseMapViewModel.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt
Fixes #1880
https://github.com/google/ground-android/assets/8918023/436071be-26bd-4b67-a194-55de22bb72ec
@gino-m  PTAL?
=> Fix suggest loi cards not showing

ground/src/main/java/com/google/android/ground/ui/common/BaseMapViewModel.kt
=> Prevent app crash on clicking "current location" button when system location setting is disabled

ground/src/main/java/com/google/android/ground/ui/common/AbstractMapContainerFragment.kt
This was probably introduced back while reverting the PR. This already happens in `applyMapConfig` in the same class
@JSunde  PTAL?
=> Remove duplicate binding for maptype

ground/src/main/java/com/google/android/ground/GroundApplication.kt
Fixes #1758
@shobhitagarwal1612 @JSunde PTAL?
=> Disable strict thread policy to prevent Maps SDK lags

ground/src/main/java/com/google/android/ground/GroundApplication.kt
=> Revert "Log StrictMode thread warnings except reads (#1901)"

ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/cards/MapCardAdapter.kt
Fixes #1904
@shobhitagarwal1612 PTAL
=> Use cached submission count instead of counting submissions.

ground/src/main/java/com/google/android/ground/persistence/remote/firebase/base/FluentCollectionReference.kt
As discussed offline
@gino-m  PTAL?
=> Prevent app crash when attempting to parse corrupt remote data

ground/src/main/java/com/google/android/ground/repository/OfflineAreaRepository.kt
=> Fix offline map imagery viewer

ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/LoiMutationConverter.kt
=> Fix polygon firestore conversion

ground/src/main/res/layout/survey_card_item.xml
=> Fix overlapping of survey title with offline icon in SurveySelectorList

ground/src/main/java/com/google/android/ground/ui/map/gms/FeatureClusterRenderer.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/renderer/FeatureRenderer.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/renderer/PolygonRenderer.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/renderer/PolylineRenderer.kt
=> Increase stroke width of selected polygon

ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/photo/PhotoTaskFragment.kt
=> Fix header not being included for photo tasks

ground/src/main/res/layout/survey_card_item.xml
=> Tweak survey list layout

ground/src/main/java/com/google/android/ground/ui/IconFactory.kt, ground/src/main/java/com/google/android/ground/ui/MarkerIconFactory.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/point/DropAPinTaskFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/PolygonDrawingTaskFragment.kt, ground/src/main/java/com/google/android/ground/ui/home/locationofinterestdetails/LocationOfInterestDetailsViewModel.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/FeatureClusterRenderer.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/GoogleMapsFragment.kt, ground/src/main/java/com/google/android/ground/ui/util/ContextExt.kt, ground/src/main/res/drawable/cluster_marker.xml, ground/src/main/res/values/colors.xml, ground/src/main/res/values/styles.xml, ground/src/test/java/com/google/android/ground/ui/MarkerIconFactoryTest.kt
Includes some minor cleanup and refactors. Towards #1910.
@JSunde @shobhitagarwal1612 PTAL? @vittorino FYI.
=> Improve cluster marker styling

ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/location/CaptureLocationTaskFragmentTest.kt
=> Add unit tests for capture location task

ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/cards/LoiCardUtil.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/cards/MapCardAdapter.kt, ground/src/main/res/values/strings.xml, ground/src/test/java/com/google/android/ground/ui/home/mapcontainer/LoiCardUtilTest.kt
=> Display customId in job card name, if available

ground/src/main/res/layout/loi_card_item.xml, ground/src/main/res/layout/suggest_loi_card_item.xml
Fixes #1922
Adds 4dp margin between vertically placed components
=> Fix spacing for job cards

ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/cards/MapCardAdapter.kt
Fixes #1925
https://github.com/google/ground-android/assets/8918023/01d69cc9-2ca5-4408-ac8f-9d51160a65af
=> Update selected job card and highlight map feature on tapping point or polygon

ground/src/main/java/com/google/android/ground/ui/common/AbstractMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/common/BaseMapViewModel.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt, ground/src/main/java/com/google/android/ground/ui/map/CameraUpdateRequest.kt, ground/src/main/java/com/google/android/ground/ui/map/MapFragment.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/GoogleMapsFragment.kt
=> Only animate the camera when device location is updated or user clicks

ground/src/main/java/com/google/android/ground/model/job/Job.kt
=> Catch all exceptions from Color.parseColor, returning default value of 0

ground/src/main/res/layout/survey_card_item.xml, ground/src/main/res/layout/survey_selector_frag.xml
=> Adjust height/width of survey item cards

ground/src/main/java/com/google/android/ground/ui/common/BaseMapViewModel.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/location/CaptureLocationMapFragment.kt
=> Fix bug in capture location task

ground/src/main/java/com/google/android/ground/persistence/remote/firebase/FirestoreDataStore.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/base/FluentCollectionReference.kt, ground/src/main/java/com/google/android/ground/repository/TermsOfServiceRepository.kt, ground/src/main/java/com/google/android/ground/repository/UserRepository.kt, ground/src/main/java/com/google/android/ground/system/NetworkManager.kt, ground/src/main/java/com/google/android/ground/system/auth/SignInState.kt, ground/src/test/java/com/google/android/ground/repository/TermsOfServiceRepositoryTest.kt, ground/src/test/java/com/google/android/ground/repository/UserRepositoryTest.kt
Fixes #1985
The issue was happening because 2 remote requests were failing. 
* Refresh user profile data
* Terms of service 
Verified the changes by opening the app in airplane mode after first signin.
=> Prevent users from getting signed out when opening the app in offline mode

ground/src/main/java/com/google/android/ground/ui/map/gms/GoogleMapsFragment.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/renderer/PolylineFeatureManager.kt
Closes #816. @shobhitagarwal1612 PTAL?
=> Render polyline while drawing area over tile overlays

ground/src/main/java/com/google/android/ground/system/SettingsManager.kt, ground/src/test/java/com/google/android/ground/system/SettingsManagerTest.kt
Fixes #1868
Also adds some unit test coverage.
@gino-m  PTAL?
=> Request for location settings if disabled

ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorFragment.kt, ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorViewModel.kt, ground/src/main/res/layout/survey_selector_frag.xml, ground/src/main/res/values/strings.xml, ground/src/test/java/com/google/android/ground/ui/surveyselector/SurveySelectorFragmentTest.kt
=> Allow users to signout if surveys are not available

cloudbuild.yaml, config/jacoco/jacoco.gradle
Fixes #1791
Fixes #1023
Verified by manually uploading the coverage report via CLI tool
https://app.codecov.io/github/google/ground-android/commit/c187d98224242492fe1f544c37acf6188b7ff756/tree
@gino-m  PTAL?
=> Fix codecov plugin

ground/src/main/java/com/google/android/ground/persistence/local/stores/LocalSubmissionStore.kt, ground/src/main/java/com/google/android/ground/repository/SubmissionRepository.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/cards/MapCardAdapter.kt
Fixes #1998
When the device is offline, then the loi entity in the table doesn't get updated. Therefore, the submission count in the bottom loi cards doesn't include the pending submissions when offline.
@gino-m  PTAL?
=> Include pending submissions as well when displaying the bottom loi cards

ground/src/main/java/com/google/android/ground/ui/common/AbstractMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/common/BaseMapViewModel.kt, ground/src/main/java/com/google/android/ground/ui/map/CameraPosition.kt, ground/src/main/java/com/google/android/ground/ui/map/CameraUpdateRequest.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/GoogleMapsFragment.kt, ground/src/test/java/com/google/android/ground/ui/map/CameraPositionTest.kt
=> Pull isAllowZoomOut out of CameraPosition class

ground/src/main/java/com/google/android/ground/ui/map/MapType.kt, ground/src/test/java/com/google/android/ground/ui/home/mapcontainer/MapTypeDialogFragmentTest.kt
=> Change default map type to terrain

ground/src/main/java/com/google/android/ground/persistence/local/LocalValueStore.kt, ground/src/main/java/com/google/android/ground/ui/settings/Keys.kt, ground/src/main/java/com/google/android/ground/ui/settings/SettingsFragment.kt, ground/src/main/res/xml/preferences.xml
=> Remove unused preference for offline download

ground/src/main/java/com/google/android/ground/persistence/local/room/dao/UserDao.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomUserStore.kt
=> Remove unused method in UserDao

ground/src/main/java/com/google/android/ground/ui/common/BindingAdapters.java, ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/components/ButtonAction.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/location/CaptureLocationTaskFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/photo/PhotoTaskFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/point/DropAPinTaskFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/PolygonDrawingTaskFragment.kt, ground/src/main/res/values/strings.xml, ground/src/test/java/com/google/android/ground/ui/datacollection/DataCollectionFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/date/DateTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/location/CaptureLocationTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/number/NumberTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/photo/PhotoTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/point/DropAPinTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/polygon/PolygonDrawingTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/text/TextTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/time/TimeTaskFragmentTest.kt
Fixes #1980
[take_a_photo_button_fixes.webm](https://github.com/google/ground-android/assets/8918023/78105b91-892d-4950-8959-a504ae836bec)
This screencast was taken before renaming the button to "next"
@gino-m  PTAL?
=> Apply minor changes to action buttons in data collection flow

ground/src/main/java/com/google/android/ground/persistence/local/room/dao/OfflineAreaDao.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomOfflineAreaStore.kt, ground/src/main/java/com/google/android/ground/persistence/local/stores/LocalOfflineAreaStore.kt, ground/src/main/java/com/google/android/ground/repository/OfflineAreaRepository.kt, ground/src/main/java/com/google/android/ground/ui/offlineareas/viewer/OfflineAreaViewerViewModel.kt
Towards #1581
Verified the changes for regression manually:
* Opening the offline selector fragment
* Ensuring that the size preview is shown correctly
* Ensuring that I'm able to download offline area, view it in basemap on homescreen and delete it
@gino-m  PTAL?
=> Use coroutine instead of Rx when fetching offlineArea from local db

ground/src/main/java/com/google/android/ground/MainActivity.kt, ground/src/main/java/com/google/android/ground/ui/common/Navigator.kt, ground/src/test/java/com/google/android/ground/MainViewModelTest.kt, ground/src/test/java/com/google/android/ground/ui/home/HomeScreenFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/tos/TermsOfServiceFragmentTest.kt
Towards #1581
Verified the changes for regression by opening various screens
@gino-m  PTAL?
=> Use coroutine in Navigator

ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/components/ButtonAction.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/location/CaptureLocationTaskFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/point/DropAPinTaskFragment.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/DataCollectionFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskFragmentTest.kt
Fixes #1982
[done_button.webm](https://github.com/google/ground-android/assets/8918023/25d8cd3e-5060-45fe-88b9-dc7c0783e501)
@gino-m  PTAL?
=> [Data Collection] Update "Next" to "Done" when on last task

ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomLocationOfInterestStore.kt, ground/src/main/java/com/google/android/ground/persistence/local/stores/LocalLocationOfInterestStore.kt, ground/src/main/java/com/google/android/ground/repository/LocationOfInterestRepository.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt, ground/src/test/java/com/google/android/ground/persistence/local/LocalDataStoreTests.kt, ground/src/test/java/com/google/android/ground/repository/LocationOfInterestRepositoryTest.kt
Towards #1581
Verified for regression by checking the affected code paths:
* Default map camera viewport when switching to a new survey
* Bottom job cards on home screen
@gino-m  PTAL?
=> [Rx -> Coroutine] Use coroutine when fetching LOIs from local db

ground/src/main/java/com/google/android/ground/persistence/local/room/dao/BaseDao.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomLocationOfInterestStore.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomSubmissionStore.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomSurveyStore.kt
=> [Cleanup] Remove unused rx based method from BaseDao

ground/src/main/java/com/google/android/ground/model/User.kt, ground/src/main/java/com/google/android/ground/repository/UserRepository.kt, ground/src/test/java/com/google/android/ground/repository/UserRepositoryTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskFragmentTest.kt
Fixes #2014
Tested for regression via unit tests
@gino-m  PTAL?
=> Prevent app crash when checking for current user's permissions

ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/cards/MapCardAdapter.kt
=> Switch to main thread when updating submission count

config/jacoco/jacoco.gradle
=> Fix source config for code coverage plugin

ground/src/main/res/layout/offline_area_viewer_frag.xml, ground/src/main/res/values/strings.xml
Fixes #611 
Before:
After:
@scolsen PTAL?
=> Tweak downloaded area screen

ground/build.gradle, ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/components/ButtonAction.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/components/TaskView.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt, ground/src/main/res/layout/task_frag_action_buttons.xml, ground/src/main/res/layout/task_frag_with_combined_header.xml, ground/src/main/res/layout/task_frag_with_header.xml, ground/src/main/res/values/strings.xml, ground/src/test/java/com/google/android/ground/ui/datacollection/DataCollectionFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/BaseTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/date/DateTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/location/CaptureLocationTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/number/NumberTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/photo/PhotoTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/point/DropAPinTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/polygon/PolygonDrawingTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/text/TextTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/time/TimeTaskFragmentTest.kt
Fixes #1981
[previous_button.webm](https://github.com/google/ground-android/assets/8918023/b6b5412b-388a-43d6-a542-f5f378fac050)
@gino-m PTAL?
=> Add "Previous" button to data collection tasks

ground/src/main/java/com/google/android/ground/persistence/local/LocalValueStore.kt, ground/src/main/java/com/google/android/ground/repository/MapStateRepository.kt, ground/src/main/java/com/google/android/ground/ui/common/AbstractMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/common/BaseMapViewModel.kt, ground/src/test/java/com/google/android/ground/repository/MapStateRepositoryTest.kt
Towards https://github.com/google/ground-android/issues/1593
@scolsen PTAL?
=> Convert rx flowable to flow when changing basemap type

ground/src/test/java/com/google/android/ground/BaseHiltTest.kt
=> Close the database in unit tests to prevent memory leak

ground/src/main/res/layout/loi_cards_recycler_view.xml
=> Add some padding to prevent clipping of job cards

ground/src/main/java/com/google/android/ground/persistence/local/room/dao/LocationOfInterestMutationDao.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomLocationOfInterestStore.kt, ground/src/main/java/com/google/android/ground/persistence/local/stores/LocalLocationOfInterestStore.kt, ground/src/main/java/com/google/android/ground/repository/LocationOfInterestRepository.kt, ground/src/main/java/com/google/android/ground/repository/SurveyRepository.kt, ground/src/test/java/com/google/android/ground/persistence/local/LocalDataStoreTests.kt, ground/src/test/java/com/google/android/ground/repository/LocationOfInterestRepositoryTest.kt, ground/src/test/java/com/google/android/ground/repository/SurveyRepositoryTest.kt
Remove unused code and update unit tests
=> Cleanup obsolete flowables

ground/src/main/java/com/google/android/ground/ui/home/HomeScreenFragment.kt, ground/src/main/java/com/google/android/ground/ui/home/HomeScreenViewModel.kt
Replaces `PublishProcessor` with `SharedFlow` for handling navigation drawer requests.
Tested by running the app locally.
=> Use SharedFlow for handling openDrawer requests

ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt
=> Use sharedFlow for handling zoom level threshold events

ground/src/main/java/com/google/android/ground/MainViewModel.kt, ground/src/main/java/com/google/android/ground/system/PermissionsManager.kt, ground/src/main/java/com/google/android/ground/ui/common/AbstractViewModel.kt
=> Replace observable with flow in MainViewModel 

ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskViewModel.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/photo/PhotoTaskViewModel.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/BaseTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/editsubmission/DateTaskViewModelTest.kt, ground/src/test/java/com/google/android/ground/ui/editsubmission/TimeTaskViewModelTest.kt
Replaces Flowable to Coroutine Flow
Reduce complexity by reducing states maintained in view model 
=> Migrate DataCollection package to coroutine

ground/src/main/java/com/google/android/ground/model/task/Task.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/converter/ValueJsonConverter.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/fields/TaskEntityType.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionConverter.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/TaskConverter.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewPagerAdapter.kt, ground/src/test/java/com/google/android/ground/persistence/local/room/converter/ValueJsonConverterTest.kt, ground/src/test/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionLocalDataStoreConverterTest.kt, ground/src/test/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionMutationConverterTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/point/DropAPinTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/polygon/PolygonDrawingTaskFragmentTest.kt
Fixes #2083.
@rfontanarosa FYI
@scolsen PTAL?
=> Sync geometry task types with web

ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/location/CaptureLocationMapFragment.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/location/CaptureLocationTaskFragmentTest.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/point/DropAPinTaskFragmentTest.kt
Fixes #2088
Hides the hint icon for capture location task and adds some unit test coverage
@gino-m  PTAL?
=> Hide hint icon for "Capture Location" task

ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/cards/MapCardAdapter.kt
=> Refactor MapCardAdapter

ground/src/main/java/com/google/android/ground/model/job/Job.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/cards/MapCardAdapter.kt, ground/src/main/res/values/strings.xml
=> Hide "Collect data" button if the job doesn't have any tasks

ground/src/main/java/com/google/android/ground/model/job/Job.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/cards/MapCardAdapter.kt
=> Don't hide "collect" button if the job has any tasks

gradle.properties, ground/build.gradle, ground/src/main/java/com/google/android/ground/persistence/local/room/dao/SurveyDao.kt
Fixes warnings reported in the gradle build logs
@gino-m  PTAL?
=> Fix build warnings

.gitignore, ground/src/debug/local/google-services.json
=> Add dummy config for local emu

.gitignore, ground/src/debug/local/google-services.json
@shobhitagarwal1612 I missed this commit in the previous. PTAL?
=> Replace local dev OAuth id

ground/build.gradle, ground/src/main/java/com/google/android/ground/MainActivity.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/FirebaseStorageManager.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/base/FluentCollectionReference.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionConverter.kt, ground/src/main/java/com/google/android/ground/system/ActivityStreams.kt, ground/src/main/java/com/google/android/ground/ui/common/BindingAdapters.java, ground/src/main/java/com/google/android/ground/ui/common/LocationOfInterestHelper.kt, ground/src/main/java/com/google/android/ground/ui/syncstatus/SyncStatusListAdapter.kt, ground/src/test/java/com/google/android/ground/ui/common/LocationOfInterestHelperTest.kt, sharedTest/build.gradle
=> Replace usages of java8 stream support library

ground/src/main/java/com/google/android/ground/ui/map/gms/GoogleMapsFragment.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/features/FeatureClusterManager.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/features/FeatureManager.kt, ground/src/test/java/com/google/android/ground/ui/map/gms/FeatureClusterManagerTest.kt
=> Select LOI on clicking map markers

ground/src/main/java/com/google/android/ground/repository/SurveyRepository.kt, ground/src/main/java/com/google/android/ground/ui/common/BaseMapViewModel.kt
Fixes #2198
Verified the change by opening the app locally and activating a survey.
@gino-m  PTAL?
=> Fix regression when attempting to update camera position on survey activation

ground/src/main/java/com/google/android/ground/ui/common/SignOutConfirmationDialogViewModel.kt, ground/src/main/java/com/google/android/ground/ui/home/HomeScreenFragment.kt
FIxes minor regression in code styling 
@justinkimtang  PTAL?
=> Fix build failure due to unused imports

ground/src/main/res/layout/sign_out_confirmation_dialog.xml
This fixes lint issues causing build failures in other PRs
@gino-m @scolsen @justinkimtang  PTAL?
=> Fix build failures due to missing text id

ground/src/main/res/drawable/baseline_close_24.xml, ground/src/main/res/layout/data_collection_frag.xml
=> Replace "up" button with "x" in data collection screen

ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/cards/MapCardAdapter.kt
=> Reduce "Collect data" tap target to button

ground/src/main/java/com/google/android/ground/GroundApplication.kt
=> Fix crash on app start 

ground/src/main/res/layout/sign_out_confirmation_dialog.xml, ground/src/main/res/values/strings.xml
=> Update message string for sign out dialog

ground/src/main/java/com/google/android/ground/ui/common/AbstractMapFragmentWithControls.kt, ground/src/main/res/values/strings.xml
=> Use label "map location" when location lock is not enabled

ground/src/main/java/com/google/android/ground/persistence/sync/MediaUploadWorkManager.kt, ground/src/main/java/com/google/android/ground/persistence/sync/MutationSyncWorkManager.kt, ground/src/main/java/com/google/android/ground/persistence/sync/SurveySyncService.kt, ground/src/main/java/com/google/android/ground/persistence/sync/SurveySyncWorker.kt, ground/src/main/java/com/google/android/ground/persistence/sync/WorkRequestBuilder.kt
=> Convert SyncService to a builder

ground/src/main/java/com/google/android/ground/MainViewModel.kt
Fixes #2260
@gino-m @scolsen @sufyanAbbasi  PTAL?
=> Directly open home screen if active survey available

build.gradle, config/detekt/detekt.yml, ground/src/main/java/com/google/android/ground/Config.kt, ground/src/main/java/com/google/android/ground/domain/usecases/survey/ActivateSurveyUseCase.kt, ground/src/main/java/com/google/android/ground/model/AuditInfo.kt, ground/src/main/java/com/google/android/ground/model/submission/Submission.kt, ground/src/main/java/com/google/android/ground/model/submission/SubmissionData.kt, ground/src/main/java/com/google/android/ground/persistence/local/LocalDataStoreModule.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/LocalDatabase.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/converter/ConverterExt.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomSubmissionStore.kt, ground/src/main/java/com/google/android/ground/repository/LocationOfInterestRepository.kt, ground/src/main/java/com/google/android/ground/repository/TermsOfServiceRepository.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/mog/MogClient.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/mog/MogImageMetadata.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/mog/MogTileMetadata.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/mog/MogTilesRequest.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/mog/UrlInputStream.kt, ground/src/test/java/com/google/android/ground/TestRemoteStorageModule.kt
Routine update of code check plugins
=> Update ktfmt and detekt plugins

ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt
=> Workaround undismissable snackbar data collection hint by setting to short duration

cloudbuild.yaml, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerFragment.kt
=> Generate code coverage reports only on merge

build.gradle
Fixes #2207
Suggested solution taken from https://github.com/ben-manes/gradle-versions-plugin/issues/746
@gino-m  PTAL?
=> Fix dependencyUpdates plugin

ground/src/test/java/com/google/android/ground/ui/home/HomeScreenFragmentTest.kt
- `Sync Status` --> `Sync status`: https://github.com/google/ground-android/commit/1ced50ec1354fb32babb55cce8cc0c1efa063c94
@gino-m PTAL?
=> Fix broken test due to commit 1ced50ec1354fb32babb55cce8cc0c1efa063c94

ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/photo/PhotoTaskFragment.kt, ground/src/main/res/drawable/outline_photo_library.xml, ground/src/main/res/layout/photo_task_frag.xml, ground/src/main/res/values/strings.xml
Fixes #1792
Fixes #2323
Fix crash in photo fragment due to binding registerForActivityResult outside of onCreate/onAttach.
Also adds support for selecting a photo from gallery (as per figma mocks)
@gino-m  PTAL?
=> Fix crash in photo fragment when rotating the device and allow selecting a photo from gallery

ground/src/main/java/com/google/android/ground/Config.kt, ground/src/main/java/com/google/android/ground/model/task/MultipleChoice.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/converter/ConverterExt.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/entity/MultipleChoiceEntity.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/MultipleChoiceConverter.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/TaskNestedObject.kt
Towards #794 
Updating MultipleChoiceEntity to include newly added "hasOtherOption" field read from  the TaskNestedObject.
@gino-m  PTAL?
=> Updating MultipleChoiceSchema to include other option

ground/src/main/java/com/google/android/ground/MainActivity.kt
Addresses #620
Forces light theme until we have a better dark theme story.
PTAL @gino-m @scolsen !
=> Force light theme (sorry!)

ground/src/main/res/values/strings.xml
Fixes #2345 
Replaces placeholder text from `This is an explanation of the offline overlay. \nThe images come from this source.` to `Offline map imagery` 
PTAL @gino-m @amegantz  ?
=> Replace offline imagery toggle placeholder text

ground/src/main/res/values/colors.xml, ground/src/main/res/values/styles.xml
Fixes #2346
@sufyanAbbasi @rfontanarosa FYI
=> [UX] Define missing Material 3 surface colors

ground/src/main/res/layout/nav_drawer_header.xml
Towards #2136
Hide description placeholder if survey doesn't have one. Otherwise we see blank space between title and change survey button
@gino-m  PTAL?
=> Hide textview placeholder if survey doesn't contain a description

ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/LoiCollectionReference.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/LoiConverter.kt
=> Allow dev / pilot LOIs without `predefined` field to be shown

ground/src/main/java/com/google/android/ground/AbstractActivity.kt, ground/src/main/java/com/google/android/ground/ui/home/HomeScreenFragment.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/GoogleMapsFragment.kt, ground/src/main/java/com/google/android/ground/util/InsetExt.kt
=> Fix build warning due to usage of deprecated window insets

ground/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorViewModel.kt, ground/src/main/res/layout/offline_area_selector_frag.xml
Fixes #739
Adds "location lock" button to offline area selector and some minor code cleanup.
@gino-m  PTAL?
=> Show location lock button in offline area selector

ground/src/main/java/com/google/android/ground/repository/OfflineAreaRepository.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/mog/MogClient.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/mog/MogProviderModule.kt, ground/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorFragment.kt, ground/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorViewModel.kt
Towards #1754
This also speeds up "updateDownloadSize" task as the client is not generated on each map camera move
@gino-m  PTAL?
=> Inject MogClient instead of building a new instance each time

ground/src/main/java/com/google/android/ground/persistence/local/LocalValueStore.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt
=> Remove last usage of lastActiveSurveyId to get current survey id

ground/src/main/java/com/google/android/ground/repository/UserRepository.kt
This prevents app from crashing if the remote call to update user's profile fails.
=> Handle exception when refreshing user's profile

ground/src/main/java/com/google/android/ground/persistence/remote/RemoteDataStore.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/FirestoreDataStore.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/base/FluentCollectionReference.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionCollectionReference.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionMutationConverter.kt, sharedTest/src/main/kotlin/com/sharedtest/persistence/remote/FakeRemoteDataStore.kt
=> Remove unused code related to loading submissions

ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/MapTypeDialogFragment.kt
Removes obsolete TODOs. Gradle dependencies are already updated to the required version & the help icon was also removed some time back
=> Remove obsolete TODOs

ground/src/test/java/com/google/android/ground/model/geometry/GeometryTest.kt
Fixes #2512 
Added two unit tests for Point data class
- isEmpty()
- getArea()
These tests confirm that if in future the hardcoded value of Point changes, these test will fail and notify team to update test or to make sure the changes are correct or not.
=> Added two unit test for point

.github/actions/submit-test/action.yml, ground/src/debug/local/google-services.json, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/LoiCollectionReference.kt
=> Fix emu project name

ground/src/main/java/com/google/android/ground/MainActivity.kt, ground/src/main/java/com/google/android/ground/system/NetworkManager.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/point/DropPinTaskFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/DrawAreaTaskFragment.kt, ground/src/main/java/com/google/android/ground/ui/home/HomeScreenFragment.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/GoogleMapsFragment.kt, ground/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorFragment.kt, ground/src/main/java/com/google/android/ground/ui/syncstatus/SyncStatusFragment.kt, sharedTest/src/main/kotlin/com/sharedtest/FakeData.kt
Used android studio's inspection tool to identify all unused hilt injections.
=> Cleanup unused hilt dependencies

ground/src/main/java/com/google/android/ground/ui/common/LocationOfInterestHelper.kt, ground/src/main/res/values-es/strings.xml, ground/src/main/res/values/strings.xml, ground/src/test/java/com/google/android/ground/ui/common/LocationOfInterestHelperTest.kt
Removes the unused method and it's only usage in unit test
=> Remove unused method from LocationOfInterestHelper

ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt
Towards https://github.com/google/ground-android/issues/2539
Adds more logging to identify the root cause for #2539
=> Throw error if task list is empty or task not found

ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/JobConverter.kt
=> Ignore unsupported tasks

cloudbuild.yaml
...using defaults defined in https://docs.codecov.com/docs/quick-start
=> [Code health] Enable codecov for all PRs

ground/src/test/java/com/google/android/ground/repository/UserRepositoryTest.kt
Fixes #2569 
@sufyanAbbasi  PTAL?
=> Added a unit test for UserRepository SignOut 

ground/src/test/java/com/google/android/ground/ui/common/LocationOfInterestHelperTest.kt, sharedTest/src/main/kotlin/com/sharedtest/FakeData.kt
Fixes #2560 
Following the test naming as per the other test functions in the file, we can convert them as a statement in later PR to keep things pr specific. 
@sufyanAbbasi  PTAL?
=> Added unit test for LocationOfInterestHelper

ground/src/main/res/layout/multiple_choice_checkbox_item.xml, ground/src/main/res/layout/multiple_choice_radiobutton_item.xml
Fixes #2549
Use default theme's text size for multiple choice task
@sufyanAbbasi @scolsen  PTAL?
=> Fix text size for multiple choice tasks

ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveyListAdapter.kt, ground/src/main/res/layout/survey_card_item.xml
Fixes #2558
Due to data binding, there was a delay in offline icon's visibility change. Doing it manually resolves the issue.
[Before](https://github.com/user-attachments/assets/065375ae-c91f-460c-bb86-1a69146dca4a)
[After](https://github.com/user-attachments/assets/392acf70-e278-4385-90ed-f8d3576c8e4d)
@gino-m  PTAL?
=> Fix flickering of offline icon in survey selector screen

ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/SurveysCollectionReference.kt
Fixes #2500 
Use the ACL_FIELD_NUMBER instead of "acl" to query for accessible surveys.
@shobhitagarwal1612  PTAL!
=> Use ACL_FIELD_NUMBER instead of "acl" for querying.

ground/src/main/java/com/google/android/ground/ui/settings/SettingsFragment.kt, ground/src/main/res/values/strings.xml, ground/src/main/res/xml/preferences.xml, ground/src/test/java/com/google/android/ground/ui/settings/SettingsFragmentTest.kt
Fixes #2590 
@shobhitagarwal1612 @sufyanAbbasi
=> Added SettingsFragment test cases

build.gradle
..to a version which is still available in Maven Central.
Fixes #2594
=> Upgrade versioner plugin

ground/src/main/java/com/google/android/ground/ui/compose/Toolbar.kt, ground/src/main/java/com/google/android/ground/ui/home/AboutFragment.kt
Fixes #2580 
This is the first PR in order to bring al our composable components under one place which can be accessible on any screen.
This will reduce the effort of creating the component again and again.
This will keep the UI consistency.
=> Common Toolbar

ground/src/test/java/com/google/android/ground/ui/home/HomeScreenViewModelTest.kt, sharedTest/src/main/kotlin/com/sharedtest/FakeData.kt
Fixes #2599 
@sufyanAbbasi @shobhitagarwal1612  PTAL?
Looks like the codecov is visible after the PR get's merge for outside contributors
=> Added test cases for HomeScreenViewModel

ground/src/main/java/com/google/android/ground/ui/home/HomeScreenFragment.kt, ground/src/main/java/com/google/android/ground/ui/home/HomeScreenViewModel.kt, ground/src/test/java/com/google/android/ground/BaseHiltTest.kt, ground/src/test/java/com/google/android/ground/ui/home/HomeScreenFragmentTest.kt
Fixes #2583 
- This is a part 1 PR for HomeScreenFragment test coverage
- Move few logics to ViewModel as Fragment is not a correct place to do that stuff
@shobhitagarwal1612  @sufyanAbbasi  PTAL?
=> Added test for HomeScreenFragment

ground/src/main/res/layout/nav_drawer_header.xml
Fixes #2444 
@shobhitagarwal1612  @sufyanAbbasi  PTAL?
=> Fixed Survey Title max lines to 3 in Nav Drawer

ground/src/main/java/com/google/android/ground/LocalDatabaseModule.kt
Fixes #2551
@sufyanAbbasi @gino-m  PTAL?
=> [Crash] Re-enable destructive migration

ground/src/main/java/com/google/android/ground/model/submission/MultipleChoiceTaskData.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/protobuf/ModelToProtoExt.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskViewModel.kt, ground/src/test/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionMutationConverterTest.kt
Fixes https://github.com/google/ground-android/issues/2618
Exclude "other" value from selected ids list and set it to correct field
Verified changes via unit tests and testing locally.
@gino-m  PTAL?
=> Fix value for multiple choice tasks with "other" option selected

ground/src/main/res/layout/sync_status_frag.xml, ground/src/main/res/values/strings.xml, ground/src/test/java/com/google/android/ground/ui/home/HomeScreenFragmentTest.kt
=> Harmonize "Data sync status" label

ground/src/main/java/com/google/android/ground/persistence/remote/firebase/protobuf/ModelToProtoExt.kt, ground/src/test/java/com/google/android/ground/persistence/remote/firebase/protobuf/LoiMutationConverterTest.kt
Fixes #2577
Undo https://github.com/google/ground-android/pull/2577
@gino-m PTAL?
=> Don't set customTag with property name value.

ground/src/test/java/com/google/android/ground/ui/offlineareas/OfflineAreasViewModelTest.kt
=> Add Test cases for OfflineAreasViewModel

ground/src/main/java/com/google/android/ground/ui/offlineareas/selector/DownloadProgressDialogFragment.kt, ground/src/main/res/layout/offline_area_selector_frag.xml, ground/src/main/res/values/strings.xml, ground/src/test/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorFragmentTest.kt
=> Added test cases for OfflineAreaSelectorFragmentTest

ground/src/main/java/com/google/android/ground/ui/compose/HtmlText.kt, ground/src/main/java/com/google/android/ground/ui/home/DataSharingTermsDialog.kt
Fill the content to the width of the dialog. Verified via the previews in the right pane in AS.
@sufyanAbbasi  PTAL?
=> [Data sharing] Minor tweak to data sharing dialog

ground/src/main/java/com/google/android/ground/MainActivity.kt, ground/src/main/java/com/google/android/ground/system/channel/LocationSharedFlowCallback.kt, ground/src/main/java/com/google/android/ground/ui/common/AbstractMapContainerFragment.kt, ground/src/main/java/com/google/android/ground/ui/common/BaseMapViewModel.kt
=> Move some log messages to `verbose` to make logs less noisy

ground/src/main/res/layout/number_task_frag.xml, ground/src/test/java/com/google/android/ground/ui/datacollection/TaskFragmentRunner.kt, ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/number/NumberTaskFragmentTest.kt
=> Allow decimal points in number tasks

ground/src/main/java/com/google/android/ground/ui/map/Feature.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/features/FeatureClusterRenderer.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/features/LineStringRenderer.kt, ground/src/main/java/com/google/android/ground/ui/map/gms/features/PolygonRenderer.kt
=> Pull "flag" from Feature.Tag to Feature

ground/src/main/res/drawable/offline_map_imagery.xml, ground/src/main/res/layout/offline_areas_frag.xml, ground/src/main/res/values/strings.xml
=> hint text on offline map imagery list

.editorconfig, .idea/ktfmt.xml, build.gradle, ground/src/main/java/com/google/android/ground/Config.kt, ground/src/test/java/com/google/android/ground/persistence/remote/firebase/schema/TaskConverterTest.kt
https://github.com/cortinico/ktfmt-gradle/releases
@gino-m  PTAL?
=> Update ktfmt to 0.20.0

ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/GeometryConverter.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/LoiConverter.kt, ground/src/test/java/com/google/android/ground/persistence/remote/firebase/schema/GeometryConverterTest.kt
These were being used for converting geometry model to firebase map.
@gino-m  PTAL?
=> [Cleanup] Remove unused geometry converters 

ground/src/main/java/com/google/android/ground/ui/tos/TermsOfServiceViewModel.kt
Fixes #2703 
A workaround to catch TermsOfServiceFragment crash
@shobhitagarwal1612 @gino-m  PTAL?
=> A workaround to catch TermsOfServiceFragment crash

ground/src/main/java/com/google/android/ground/ui/tos/TermsOfServiceViewModel.kt, ground/src/test/java/com/google/android/ground/ui/tos/TermsOfServiceFragmentTest.kt
Fixes #2707.
I added at least a minimal unit test, but it'd be good if we could find a better solution here.
=> Render Markdown in Terms of Service

ground/src/main/java/com/google/android/ground/persistence/local/room/converter/ValueJsonConverter.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/CaptureLocationResultConverter.kt
Pulls all related JsonObject to task data converters (and vice versa) to CaptureLocationResultConverter
@gino-m @anandwana001  PTAL?
=> [Refactor] Move converters for CaptureLocationTaskData to related class

config/detekt/baseline.xml, ground/src/main/java/com/google/android/ground/model/submission/SkippedTaskData.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/converter/ValueJsonConverter.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/protobuf/ModelToProtoExt.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/protobuf/ProtobufToFirestoreExt.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskViewModel.kt, ground/src/test/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionMutationConverterTest.kt
Towards #2717
Set "skipped" field when user skips a task 
@gino-m  PTAL?
=> [Data submission] Set "skipped" to true when user skips a task 

ground/src/main/java/com/google/android/ground/persistence/local/room/converter/ValueJsonConverter.kt
Fixes #2746 
if skip key is not found, json parse goes to error quietly and tell user that the data has been synch, but in reality, the entry got created in web and all the data shows as SKIPPED
=> JSON Parsing SKIPPED Task error

ground/src/main/java/com/google/android/ground/ui/common/LocationOfInterestHelper.kt, ground/src/main/res/values/strings.xml, ground/src/test/java/com/google/android/ground/ui/common/LocationOfInterestHelperTest.kt
=> Fix LOI name for map cards

ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/date/DateTaskFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/date/DateTaskViewModel.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/time/TimeTaskFragment.kt, ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/time/TimeTaskViewModel.kt
Cleanup of https://github.com/google/ground-android/pull/2720
=> Cleanup unused param from date/time task VMs

ground/src/main/java/com/google/android/ground/ui/home/HomeScreenFragment.kt
Fixes #2774 
Collect `openDrawerRequestsFlow` after the binding variable gets initialised 
=> Collect after Binding initialization

ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/MapTypeAdapter.kt, ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/MapTypeDialogFragment.kt
=> [MapTypeAdapter]: Position should be greater than -1

ground/src/test/java/com/google/android/ground/ui/datacollection/tasks/date/DateTaskFragmentTest.kt
=> Added a test for DateTaskFragment

ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/number/NumberTaskFragment.kt
=> [NumberTaskFragment - Landscape Support] Set ViewModel before UI initialisation 

ground/src/main/java/com/google/android/ground/ui/home/HomeScreenFragment.kt, ground/src/main/java/com/google/android/ground/ui/home/SignOutConfirmationDialog.kt, ground/src/main/java/com/google/android/ground/ui/home/UserDetailsDialog.kt, ground/src/main/res/values/strings.xml
Fixes #2643
This PR updates the message in signout dialog to warn users regarding not being able to sign in again when in offline mode.
Also adds some minor readability refactors in the related dialog composable code.
[signout_dialog_message.webm](https://github.com/user-attachments/assets/d5bd3484-6b3f-4fa9-a5ed-5a7c4d11ed45)
@anandwana001 @gino-m  PTAL?
=> Adds offline warning to signout dialog and minor refactors

ground/src/main/java/com/google/android/ground/persistence/remote/firebase/FirebaseFirestoreProvider.kt
Fixes #2801 
java/com/google/android/ground/persistence/remote/firebase/FirebaseFirestoreProvider.kt:33:15: Expression with labels increase complexity and affect maintainability.
Removed the Expression by dividing it to the separate function.
=> Removed Expression with labels

ground/src/test/java/com/google/android/ground/ui/home/DataSharingTermsDialogTest.kt
=> Added DataSharingTermsDialog  test cases

ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorFragment.kt
=> Do Not Show Back Button if Nothing in backstack

ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomSurveyStore.kt
=> Run survey updates in a transaction

ground/src/main/java/com/google/android/ground/Config.kt, ground/src/main/java/com/google/android/ground/FirebaseCrashLogger.kt, ground/src/main/java/com/google/android/ground/MainViewModel.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/converter/ConverterExt.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/converter/ValueJsonConverter.kt, ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomSubmissionStore.kt, ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/LoiCollectionReference.kt, ground/src/main/java/com/google/android/ground/persistence/sync/LocalMutationSyncWorker.kt, ground/src/main/java/com/google/android/ground/persistence/sync/MediaUploadWorker.kt, ground/src/main/java/com/google/android/ground/persistence/sync/SurveySyncWorker.kt, ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorViewModel.kt, ground/src/main/java/com/google/android/ground/ui/syncstatus/SyncStatusViewModel.kt, ground/src/main/java/com/google/android/ground/ui/tos/TermsOfServiceViewModel.kt, ground/src/test/java/com/google/android/ground/persistence/sync/LocalMutationSyncWorkerTest.kt, ground/src/test/java/com/google/android/ground/persistence/sync/SurveySyncWorkerTest.kt
Fixes #2850
Fixes #2851
Fixes #2849
Fixes #2853
Fixes #2856
=> [Code health] Clean up and improve error logging

ground/src/main/res/values-es/strings.xml, ground/src/main/res/values-fr/strings.xml
Few new strings added to french strings.xml.
Spanish strings.xml completely updated to match English strings.xml.
Spanish translations kindly provided by PilarValbuena <pilar.valbuena.perez@gmail.com >
=> Updated French & Spanish translations

ground/src/main/res/values-pt/strings.xml
And.....we got Portuguese!! :D
Translations into Brazilian Portuguese kindly provided by Daniel Dionisio of FAO-OCBD.
=> Portuguese translations

.editorconfig, .github/workflows/todo-to-issue.yml, ground/src/main/java/com/google/android/ground/Config.kt
https://github.com/marketplace/actions/todo-to-issue
Fixes #2922
@gino-m  PTAL?
Auto-created bug: https://github.com/google/ground-android/issues/2930
=> Add workflow for creating bugs from TODOs

ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskFragment.kt
Create a todo to test if the bug url is inserted back into the code.
=> Create a todo for replacing multiple choice ux with compose

.github/workflows/todo-to-issue.yml
Workflow can't insert the bug urls back into the code. So disabling until that is resolved.
@gino-m  PTAL?
=> Disable todo-to-issue.yml temporarily

ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/SurveyConverter.kt
Fixes #2857 
@gino-m  @shobhitagarwal1612  PTAL?
=> Modularize SurveyConverter.toSurvey()

ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionFragment.kt
Fixes #2829 
@shobhitagarwal1612 @gino-m  PTAL?
https://github.com/user-attachments/assets/3047ddc2-7d69-48fc-b304-945a63a6354c
=> [Data collection flow] Disable animation on previous/next

.github/workflows/todo-to-issue.yml
Do not auto-close the issues linked to TODOs with the todo-to-issue workflow.
This is to prevent the issues from getting closed even before the PR is merged.
Example: https://github.com/google/ground-android/issues/1733#issuecomment-2560054435
@gino-m  PTAL?
=> Do not auto-close the issues when TODO is cleaned up

ground/src/main/java/com/google/android/ground/persistence/local/room/converter/GeometryWrapperTypeConverter.kt
Fixes #2971 
Parent Ticket #2338 
Added Missing Annotations `ExperimentalSerializationApi`
=> added missing annotation

CONTRIBUTING.md
Removes documentation for setting with GCB. We have already deprecated GCB with Github actions. 
@gino-m @anandwana001  PTAL?
=> Remove documentation for GCB setup

app/src/main/java/com/google/android/ground/ui/home/mapcontainer/jobs/ActionButton.kt, app/src/main/java/com/google/android/ground/ui/home/mapcontainer/jobs/JobMapComposables.kt, app/src/main/java/com/google/android/ground/ui/home/mapcontainer/jobs/JobSelectionModal.kt, app/src/main/java/com/google/android/ground/ui/home/mapcontainer/jobs/JobSelectionRow.kt, app/src/main/java/com/google/android/ground/ui/home/mapcontainer/jobs/LoiJobSheet.kt
Reduces complexity of JobMapComposables class by moving composable components to separate files. Also adds preview to each and simplifies the composable logic wherever possible.
Verified for regressions using previews.
@anandwana001 @gino-m @sufyanAbbasi  PTAL?
=> Separate UI and logic by moving composable components out of JobMapComposables class

build.gradle
Fixes #3041 
Target SDK is updated to level 34
@rfontanarosa Anything specific we need to test as mentioned in issue description?
@shobhitagarwal1612  @rfontanarosa  PTAL?
=> Target SDK updated to 34

app/src/main/java/com/google/android/ground/MainActivity.kt, app/src/main/java/com/google/android/ground/MainViewModel.kt
Fixes #3053 
@gino-m @shobhitagarwal1612  PTAL?
=> Auth status in MainViewModel when app is resumed

app/src/main/java/com/google/android/ground/ui/datacollection/tasks/date/DateTaskFragment.kt, app/src/main/java/com/google/android/ground/ui/datacollection/tasks/time/TimeTaskFragment.kt, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values/strings.xml, app/src/test/java/com/google/android/ground/ui/datacollection/tasks/date/DateTaskFragmentTest.kt
Fixes #3049 
Adds support for clearing date and time task responses.
https://github.com/user-attachments/assets/d7559de0-df1a-4dc1-9850-f68de6618f5c
@gino-m  PTAL?
=> Adds support for clearing date and time task responses

app/src/main/AndroidManifest.xml, app/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/DrawAreaTaskFragment.kt, app/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/DrawAreaTaskViewModel.kt, app/src/main/java/com/google/android/ground/ui/util/VibrationHelper.kt
Fixes #2674 
Added vibration on every point added to screen.
Need to add visual effect feedback.
@shobhitagarwal1612  @gino-m  PTAL?
=> Added vibrate function when pressing "Add point" 

app/src/main/java/org/groundplatform/android/ui/map/gms/GoogleMapsFragment.kt
=> Check viewLifecycleOwner is available

app/src/main/java/org/groundplatform/android/ui/util/VibrationHelper.kt
=> Half vibration duration on tap "Add point"

app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/point/DropPinTaskFragment.kt
Fixes #2982
Remove TODO added by mistake.
=> Cleanup invalid TODO

app/src/main/java/org/groundplatform/android/ui/home/mapcontainer/jobs/LoiJobSheet.kt
Fixes #3092 
@shobhitagarwal1612  @sufyanAbbasi  PTAL?
=> Added System Bar padding

app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/multiplechoice/MultipleChoiceItemView.kt
=> Remove keyboard focus when "other" option is deselected

app/src/main/java/org/groundplatform/android/ui/home/mapcontainer/jobs/JobMapComposables.kt
=> Added bottom padding to Add Button

app/src/main/java/org/groundplatform/android/ui/syncstatus/SyncListItem.kt, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values/strings.xml
=> Improve sync status labels

app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/AbstractTaskFragment.kt, app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskFragment.kt
=> Added ViewModel Initialise Check

app/src/main/java/org/groundplatform/android/MainActivity.kt, app/src/main/java/org/groundplatform/android/ui/home/mapcontainer/jobs/JobSelectionModal.kt, app/src/main/java/org/groundplatform/android/ui/home/mapcontainer/jobs/LoiJobSheet.kt
Fixes #3113
@shobhitagarwal1612  @sufyanAbbasi  PTAL?
=> Added Bottom Space for new Buttons on Home Screen

app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/point/DropPinTaskMapFragment.kt
Fixes #3088 
Disable pan/zoom gestures if drop pin marker is selected
Verified by running the app locally. Couldn't add test cases as this involves google maps which doesn't work in unit tests.
@gino-m @anandwana001  PTAL?
=> Disable pan/zoom gestures if drop pin marker is selected

.github/workflows/ci.yml
Running unit tests takes ~5 mins but code quality checks take ~2 mins. Running code quality checks first would allow for faster failures of builds
=> Run code quality checks before unit tests in CI

app/src/main/java/org/groundplatform/android/ui/datacollection/DataCollectionViewModel.kt
=> Fix NoSuchElementException in getTaskViewModel by Handling Empty Collection

app/src/main/java/org/groundplatform/android/ui/datacollection/DataCollectionViewModel.kt
Towards #2998 
Adds more info to the error message for debugging the exception. 
Also moves statements not related to creating view model from factory out of the try-catch block.
=> Add details to error message for debugging

app/src/main/java/org/groundplatform/android/ui/tos/TermsOfServiceFragment.kt
=> Fixed TermsOfService Formatting

app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/polygon/DrawAreaTaskFragment.kt, app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/polygon/DrawAreaTaskViewModel.kt, app/src/test/java/org/groundplatform/android/ui/datacollection/tasks/polygon/DrawAreaTaskFragmentTest.kt
Fixes #3131 
@shobhitagarwal1612 @gino-m   PTAL?
https://github.com/user-attachments/assets/3d523429-c47e-476e-8422-5cfac7608bed
=> Added Too Close check when drawing Polygon

app/src/main/java/org/groundplatform/android/model/Role.kt
=> Removed valueStrings method

app/src/main/java/org/groundplatform/android/persistence/local/room/converter/ConverterExt.kt, app/src/main/java/org/groundplatform/android/persistence/local/room/converter/SubmissionDataConverter.kt, app/src/main/java/org/groundplatform/android/persistence/local/room/entity/JobEntity.kt, app/src/main/java/org/groundplatform/android/persistence/local/room/entity/MultipleChoiceEntity.kt, app/src/main/java/org/groundplatform/android/persistence/local/room/entity/OptionEntity.kt, app/src/main/java/org/groundplatform/android/persistence/local/room/entity/SubmissionEntity.kt, app/src/main/java/org/groundplatform/android/persistence/local/room/entity/SubmissionMutationEntity.kt, app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/polygon/DrawAreaTaskViewModel.kt, app/src/main/java/org/groundplatform/android/ui/map/gms/features/MapsItemManager.kt, app/src/main/java/org/groundplatform/android/ui/map/gms/mog/MogClient.kt, app/src/main/java/org/groundplatform/android/ui/map/gms/mog/MogMetadata.kt, app/src/main/java/org/groundplatform/android/ui/map/gms/mog/MogMetadataReader.kt, app/src/test/java/org/groundplatform/android/persistence/remote/firebase/FirebaseMessagingSurveyTest.kt, app/src/test/java/org/groundplatform/android/ui/home/mapcontainer/HomeScreenMapContainerFragmentTest.kt, build.gradle, config/detekt/baseline.xml, config/detekt/detekt.yml, config/jacoco/jacoco.gradle, config/lint/lint.xml
Follow up to https://github.com/google/ground-android/pull/3139
Updates configs for code analysis tools and also fixes some of the findings.
=> Update code analysis tools

app/build.gradle
- Updated `composeUi` to `1.8.2`
- Updated `fragmentVersion` to `1.8.7`
- Updated `constraintlayout` to `2.2.1`
- Updated `play-services-auth` to `21.3.0`
- Updated `play-services-maps` to `19.2.0`
- Updated `gson` to `2.11.0`
Verified for regressions by running the app locally.
=> Updated versions for several dependencies

app/src/main/java/org/groundplatform/android/ui/home/mapcontainer/jobs/LoiJobSheet.kt, app/src/test/java/org/groundplatform/android/FakeData.kt, app/src/test/java/org/groundplatform/android/ui/home/mapcontainer/jobs/LoiJobSheetTest.kt
=> Hide add data button

app/build.gradle
Removes java-only gradle dependencies
=> Remove java only gradle dependencies

app/src/test/java/org/groundplatform/android/persistence/local/LocalLocationOfInterestStoreTest.kt, app/src/test/java/org/groundplatform/android/persistence/local/LocalOfflineAreaStore.kt, app/src/test/java/org/groundplatform/android/persistence/local/LocalSubmissionStoreTest.kt, app/src/test/java/org/groundplatform/android/persistence/local/LocalUserStoreTest.kt
=> [Code health] Split up LocalDataStoreTests

build.gradle
=> Remove overriden gradle task

app/src/main/java/org/groundplatform/android/persistence/remote/firebase/schema/SurveysCollectionReference.kt
Fixes #2445
Incomplete draft surveys are visible in the app to the survey organizer, we are preventing the survey which are in draft state to be in the app.
=> Not including Incomplete draft surveys 

app/src/test/java/org/groundplatform/android/persistence/local/LocalLocationOfInterestStoreTest.kt
=> Copyright Date revert

README.md
=> Correct ci link

app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/AbstractTaskMapFragment.kt, app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/polygon/DrawAreaTaskFragment.kt, app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/polygon/DrawAreaTaskMapFragment.kt, app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/polygon/DrawAreaTaskViewModel.kt
Fixes #3168 
| Before  | After |
| --- | --- |
| <img width="426" alt="Screenshot 2025-07-07 at 12 23 15 PM" src="https://github.com/user-attachments/assets/49a7c849-2a30-46c2-a1a6-5ac7da61ef37" /> | <img width="429" alt="Screenshot 2025-07-07 at 12 21 57 PM" src="https://github.com/user-attachments/assets/09e239cc-ad58-428f-9bd9-1b4c1206e1e0" /> |
=> [DrawAreaTaskMapFragment] Hide add marker when point too close

app/schemas/org.groundplatform.android.persistence.local.room.LocalDatabase/122.json, app/schemas/org.groundplatform.android.persistence.local.room.LocalDatabase/123.json, app/src/main/java/org/groundplatform/android/Config.kt, app/src/main/java/org/groundplatform/android/model/Survey.kt, app/src/main/java/org/groundplatform/android/persistence/local/room/converter/ConverterExt.kt, app/src/main/java/org/groundplatform/android/persistence/local/room/entity/SurveyEntity.kt, app/src/main/java/org/groundplatform/android/persistence/remote/firebase/schema/SurveyConverter.kt, app/src/main/java/org/groundplatform/android/repository/UserRepository.kt, app/src/test/java/org/groundplatform/android/FakeData.kt, app/src/test/java/org/groundplatform/android/model/SurveyTest.kt, app/src/test/java/org/groundplatform/android/persistence/local/LocalLocationOfInterestStoreTest.kt, app/src/test/java/org/groundplatform/android/persistence/local/LocalSubmissionStoreTest.kt, app/src/test/java/org/groundplatform/android/persistence/remote/firebase/schema/LoiConverterTest.kt, app/src/test/java/org/groundplatform/android/persistence/remote/firebase/schema/SurveyConverterTest.kt, app/src/test/java/org/groundplatform/android/repository/UserRepositoryTest.kt, app/src/test/java/org/groundplatform/android/usecases/survey/ListAvailableSurveysUseCaseTest.kt, app/src/test/java/org/groundplatform/android/usecases/survey/ReactivateLastSurveyUseCaseTest.kt
Fixes #3157
We might need migration here as well
WDYT?
=> [UserRepository] User can submit to Public as well as Unlisted survey

app/src/main/java/org/groundplatform/android/repository/UserMediaRepository.kt, app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskFragment.kt, app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskViewModel.kt, app/src/main/java/org/groundplatform/android/ui/util/BitmapUtil.kt
Fixes #3102 
@shobhitagarwal1612 @rfontanarosa  PTAL?
=> [PhotoTaskFragment] Remove decodeBitmap approach

app/src/main/java/org/groundplatform/android/MainActivity.kt, app/src/main/java/org/groundplatform/android/MainUiState.kt, app/src/main/java/org/groundplatform/android/MainViewModel.kt, app/src/test/java/org/groundplatform/android/MainActivityTest.kt
Fixes #3176 
@rfontanarosa @shobhitagarwal1612  PTAL?
=> [MainActivity] Fix Deeplink for both cases, With/Without Activated Survey

app/src/main/res/values-fr/strings.xml, app/src/main/res/values-vi/strings.xml, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml
=> Add vietnamese translation

app/src/main/java/org/groundplatform/android/ui/home/mapcontainer/MapTypeDialogFragment.kt, app/src/test/java/org/groundplatform/android/ui/home/mapcontainer/MapTypeDialogFragmentTest.kt
Fixes #2562
https://github.com/user-attachments/assets/7001604f-0057-4831-8a0b-c245ba6d1896
@jo-spek @shobhitagarwal1612  PTAL?
=> [MapTypeDialogFragment] Dismiss base map post selection

app/src/main/java/org/groundplatform/android/coroutines/CoroutineDispatchersModule.kt, app/src/main/java/org/groundplatform/android/ui/common/AbstractMapContainerFragment.kt, app/src/test/java/org/groundplatform/android/TestCoroutineDispatchersModule.kt
Removes `DefaultDispatcher` and `MainImmediateDispatcher` from `CoroutineDispatchersModule` as they were not being used. The corresponding annotations were also removed.
@gino-m @anandwana001  PTAL?
=> Removes unused coroutine dispatchers

app/src/main/java/org/groundplatform/android/data/local/room/LocalDatabase.kt
The schema version was updated in https://github.com/google/ground-android/pull/3143
=> Define schema auto-migration entry for version 124

app/build.gradle, build.gradle, gradle/libs.versions.toml, settings.gradle
Fixes #3291
This is a non-user facing change. Verified for regressions by running the app locally. 
@anandwana001 @gino-m  PTAL?
=> Migrate from kapt to KSP
